-- AUTOGENERATED CODE BY export_accountitems.lua

CLOTHING =
{
	body_buttons_black_jet =
	{
		type = "body",
		skin_tags = { "BLACK", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 7,
	},
	body_buttons_blue_sky =
	{
		type = "body",
		skin_tags = { "BLUE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 0,
	},
	body_buttons_green_laurel =
	{
		type = "body",
		skin_tags = { "GREEN", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 0,
	},
	body_buttons_pink_hibiscus =
	{
		type = "body",
		skin_tags = { "PINK", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 0,
	},
	body_buttons_white_ghost =
	{
		type = "body",
		skin_tags = { "WHITE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 0,
	},
	body_cardigan_black_jet =
	{
		type = "body",
		skin_tags = { "LUNAR", "BLACK", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "arm_lower", },
		torso_tuck = "untucked",
		rarity = "Classy",
		marketable = true,
		release_group = 3,
	},
	body_cardigan_red_cardinal =
	{
		type = "body",
		skin_tags = { "LUNAR", "RED", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "arm_lower", },
		torso_tuck = "untucked",
		rarity = "Classy",
		marketable = true,
		release_group = 3,
	},
	body_cardigan_teal_jade =
	{
		type = "body",
		skin_tags = { "LUNAR", "TEAL", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "arm_lower", },
		torso_tuck = "untucked",
		rarity = "Classy",
		marketable = true,
		release_group = 3,
	},
	body_cardigan_white_ghost =
	{
		type = "body",
		skin_tags = { "LUNAR", "WHITE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "arm_lower", },
		torso_tuck = "untucked",
		rarity = "Classy",
		marketable = true,
		release_group = 3,
	},
	body_catcoon_costume =
	{
		type = "body",
		skin_tags = { "COSTUME", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper_skin", "hand", "torso", "torso_pelvis", "leg", "foot", "tail", },
		symbol_hides = { "skirt", "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 15,
	},
	body_chester_costume =
	{
		type = "body",
		skin_tags = { "COSTUME", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "hand", "torso", "torso_pelvis", "leg", "foot", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 15,
	},
	body_coatdress_red_higgsbury =
	{
		type = "body",
		skin_tags = { "LUNAR", "RED", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "foot", "leg", "skirt", "torso", "torso_pelvis", },
		torso_tuck = "skirt",
		rarity = "Spiffy",
		marketable = true,
		release_group = 23,
	},
	body_dancer_dragon =
	{
		type = "body",
		skin_tags = { "LUNAR", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "foot", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "arm_upper", "skirt", },
		torso_tuck = "untucked",
		rarity = "Event",
		release_group = 23,
	},
	body_dancer_lion =
	{
		type = "body",
		skin_tags = { "LUNAR", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_lower_cuff", "arm_upper", "foot", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Event",
		release_group = 23,
	},
	body_dress_flouncy_tan_cream =
	{
		type = "body",
		skin_tags = { "TAN", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "arm_upper", "torso", "torso_pelvis", "skirt", "foot", },
		torso_tuck = "full",
		rarity = "Distinguished",
		marketable = true,
		release_group = 10,
	},
	body_dress_yachtsuit_white_pure =
	{
		type = "body",
		skin_tags = { "WHITE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "skirt", "leg", "foot", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		marketable = true,
		release_group = 10,
	},
	body_expo_letterman_yellow_beige =
	{
		type = "body",
		skin_tags = { "PROMOTION", "YELLOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "arm_lower", "arm_lower_cuff", },
		torso_tuck = "untucked",
		rarity = "Spiffy",
		marketable = true,
		release_group = 8,
	},
	body_expo_sweater_blue_agean =
	{
		type = "body",
		skin_tags = { "PROMOTION", "BLUE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "arm_lower", "arm_lower_cuff", },
		torso_tuck = "untucked",
		rarity = "Spiffy",
		marketable = true,
		release_group = 8,
	},
	body_flannel_blue_snowbird =
	{
		type = "body",
		skin_tags = { "BLUE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 0,
	},
	body_flannel_green_napier =
	{
		type = "body",
		skin_tags = { "GREEN", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 7,
	},
	body_flannel_orange_lumberjack =
	{
		type = "body",
		skin_tags = { "ORANGE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 0,
	},
	body_flannel_purple_grape =
	{
		type = "body",
		skin_tags = { "PURPLE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 0,
	},
	body_glommer_costume =
	{
		type = "body",
		skin_tags = { "COSTUME", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper_skin", "arm_lower", "hand", "torso", "torso_pelvis", "leg", "foot", },
		symbol_hides = { "skirt", "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 15,
	},
	body_hutch_costume =
	{
		type = "body",
		skin_tags = { "COSTUME", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "torso_pelvis", "leg", "foot", "tail", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 15,
	},
	body_jacket_shearling_orange_salmon =
	{
		type = "body",
		skin_tags = { "ORANGE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "torso", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 10,
	},
	body_jacket_toggle_navy_phthalo =
	{
		type = "body",
		skin_tags = { "NAVY", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "torso", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 10,
	},
	body_outerwear_quilted_red_cardinal =
	{
		type = "body",
		skin_tags = { "LUNAR", "RED", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_lower_cuff", "arm_upper", "foot", "leg", "skirt", "torso", "torso_pelvis", },
		torso_tuck = "skirt",
		rarity = "Spiffy",
		marketable = true,
		release_group = 23,
	},
	body_overalls_black_scribble =
	{
		type = "body",
		skin_tags = { "BLACK", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Spiffy",
		legs_cuff_size = 2,
		marketable = true,
		release_group = 7,
	},
	body_overalls_blue_denim =
	{
		type = "body",
		skin_tags = { "BLUE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Spiffy",
		legs_cuff_size = 2,
		marketable = true,
		release_group = 7,
	},
	body_overalls_navy_ocean =
	{
		type = "body",
		skin_tags = { "NAVY", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Spiffy",
		legs_cuff_size = 2,
		marketable = true,
		release_group = 7,
	},
	body_pj_blue_agean =
	{
		type = "body",
		skin_tags = { "BLUE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "arm_lower", "arm_lower_cuff", },
		torso_tuck = "untucked",
		rarity = "Spiffy",
		marketable = true,
		release_group = 20,
	},
	body_pj_purple_mauve =
	{
		type = "body",
		skin_tags = { "PURPLE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "arm_lower", "arm_lower_cuff", },
		torso_tuck = "untucked",
		rarity = "Spiffy",
		marketable = true,
		release_group = 7,
	},
	body_pj_silk_teal_jade =
	{
		type = "body",
		skin_tags = { "LUNAR", "TEAL", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_lower_cuff", "arm_upper", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Event",
		legs_cuff_size = 5,
		release_group = 23,
	},
	body_polo_blue_denim =
	{
		type = "body",
		skin_tags = { "BLUE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 3,
	},
	body_polo_orange_salmon =
	{
		type = "body",
		skin_tags = { "ORANGE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 7,
	},
	body_polo_red_higgsbury =
	{
		type = "body",
		skin_tags = { "RED", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 0,
	},
	body_polo_white_marble =
	{
		type = "body",
		skin_tags = { "WHITE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 0,
	},
	body_polo_yellow_goldenrod =
	{
		type = "body",
		skin_tags = { "YELLOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 0,
	},
	body_silk_eveningrobe_blue_frost =
	{
		type = "body",
		skin_tags = { "LUNAR", "BLUE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "skirt", },
		torso_tuck = "skirt",
		rarity = "Spiffy",
		marketable = true,
		release_group = 3,
	},
	body_silk_eveningrobe_pink_ewecus =
	{
		type = "body",
		skin_tags = { "LUNAR", "PINK", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "skirt", },
		torso_tuck = "skirt",
		rarity = "Spiffy",
		marketable = true,
		release_group = 3,
	},
	body_silk_eveningrobe_red_rump =
	{
		type = "body",
		skin_tags = { "LUNAR", "RED", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "skirt", },
		torso_tuck = "skirt",
		rarity = "Spiffy",
		marketable = true,
		release_group = 3,
	},
	body_silk_eveningrobe_yellow_goldenrod =
	{
		type = "body",
		skin_tags = { "LUNAR", "YELLOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "skirt", },
		torso_tuck = "skirt",
		rarity = "Spiffy",
		marketable = true,
		release_group = 3,
	},
	body_silk_loungewear_black_davys =
	{
		type = "body",
		skin_tags = { "LUNAR", "BLACK", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "skirt", "torso_pelvis", "leg", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		legs_cuff_size = 5,
		marketable = true,
		release_group = 3,
	},
	body_silk_loungewear_green_laurel =
	{
		type = "body",
		skin_tags = { "LUNAR", "GREEN", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "skirt", "torso_pelvis", "leg", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		legs_cuff_size = 5,
		marketable = true,
		release_group = 3,
	},
	body_silk_loungewear_red_cranberry =
	{
		type = "body",
		skin_tags = { "LUNAR", "RED", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "skirt", "torso_pelvis", "leg", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		legs_cuff_size = 5,
		marketable = true,
		release_group = 3,
	},
	body_silk_loungewear_white_marble =
	{
		type = "body",
		skin_tags = { "LUNAR", "WHITE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "skirt", "torso_pelvis", "leg", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		legs_cuff_size = 5,
		marketable = true,
		release_group = 3,
	},
	body_silkbrocade_coat_green_laurel =
	{
		type = "body",
		skin_tags = { "LUNAR", "GREEN", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_lower_cuff", "arm_upper", "leg", "skirt", "torso", "torso_pelvis", },
		torso_tuck = "skirt",
		rarity = "Event",
		legs_cuff_size = 2,
		release_group = 23,
	},
	body_sleepgown_blue_ice =
	{
		type = "body",
		skin_tags = { "BLUE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "torso_pelvis", "arm_upper", "skirt", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		marketable = true,
		release_group = 7,
	},
	body_sleepgown_purple_lavender =
	{
		type = "body",
		skin_tags = { "PURPLE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "torso_pelvis", "arm_upper", "skirt", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		marketable = true,
		release_group = 20,
	},
	body_suspenders_pink_pearl =
	{
		type = "body",
		skin_tags = { "PINK", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Classy",
		marketable = true,
		release_group = 0,
	},
	body_suspenders_white_pure =
	{
		type = "body",
		skin_tags = { "WHITE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Classy",
		marketable = true,
		release_group = 1,
	},
	body_suspenders_yellow_flax =
	{
		type = "body",
		skin_tags = { "YELLOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Classy",
		marketable = true,
		release_group = 0,
	},
	body_sweatervest_blue_snowbird =
	{
		type = "body",
		skin_tags = { "BLUE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Classy",
		marketable = true,
		release_group = 0,
	},
	body_sweatervest_brown_beaver =
	{
		type = "body",
		skin_tags = { "BROWN", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Classy",
		marketable = true,
		release_group = 0,
	},
	body_sweatervest_green_forest =
	{
		type = "body",
		skin_tags = { "GREEN", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Classy",
		marketable = true,
		release_group = 7,
	},
	body_sweatervest_grey_silver =
	{
		type = "body",
		skin_tags = { "GREY", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Classy",
		marketable = true,
		release_group = 0,
	},
	body_sweatervest_red_firehound =
	{
		type = "body",
		skin_tags = { "RED", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Classy",
		marketable = true,
		release_group = 0,
	},
	body_tanktop_tiecollar_yellow_goldenrod =
	{
		type = "body",
		skin_tags = { "YELLOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", },
		symbol_hides = { "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Spiffy",
		marketable = true,
		release_group = 10,
	},
	body_toga_white_pure =
	{
		type = "body",
		skin_tags = { "WHITE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "torso_pelvis", "arm_upper", "skirt", },
		torso_tuck = "skirt",
		rarity = "Spiffy",
		marketable = true,
		release_group = 14,
	},
	body_trenchcoat_brown_fawn =
	{
		type = "body",
		skin_tags = { "BROWN", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "arm_lower", "skirt", },
		torso_tuck = "skirt",
		rarity = "Spiffy",
		marketable = true,
		release_group = 1,
	},
	body_trenchcoat_yellow_straw =
	{
		type = "body",
		skin_tags = { "YELLOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "arm_lower", "skirt", },
		torso_tuck = "skirt",
		rarity = "Spiffy",
		marketable = true,
		release_group = 1,
	},
	body_trimmed_blouse_red_higgsbury =
	{
		type = "body",
		skin_tags = { "RED", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 0,
	},
	body_trimmed_blouse_white_pure =
	{
		type = "body",
		skin_tags = { "WHITE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 0,
	},
	body_trimmed_blouse_yellow_flax =
	{
		type = "body",
		skin_tags = { "YELLOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 0,
	},
	body_tshirt_grey_battleship =
	{
		type = "body",
		skin_tags = { "GREY", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 0,
	},
	body_tshirt_purple_mauve =
	{
		type = "body",
		skin_tags = { "PURPLE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 3,
	},
	body_tshirt_red_higgsbury =
	{
		type = "body",
		skin_tags = { "RED", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 0,
	},
	body_tshirt_white_smoke =
	{
		type = "body",
		skin_tags = { "WHITE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		marketable = true,
		release_group = 0,
	},
	body_tweedvest_blue_lightning =
	{
		type = "body",
		skin_tags = { "BLUE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Classy",
		marketable = true,
		release_group = 7,
	},
	body_tweedvest_brown_chocolate =
	{
		type = "body",
		skin_tags = { "BROWN", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Classy",
		marketable = true,
		release_group = 0,
	},
	body_tweedvest_green_hunters =
	{
		type = "body",
		skin_tags = { "GREEN", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Classy",
		marketable = true,
		release_group = 0,
	},
	body_tweedvest_grey_steel =
	{
		type = "body",
		skin_tags = { "GREY", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Classy",
		marketable = true,
		release_group = 0,
	},
	body_tweedvest_tan_grass =
	{
		type = "body",
		skin_tags = { "TAN", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Classy",
		marketable = true,
		release_group = 0,
	},
	body_wathgrithr_deerclops =
	{
		type = "body",
		skin_tags = { "COSTUME", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_lower_cuff", "arm_upper_skin", "foot", "hand", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "arm_upper", "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		legs_cuff_size = 3,
		marketable = true,
		release_group = 31,
	},
	body_wathgrithr_formal =
	{
		type = "body",
		skin_tags = { "FORMAL", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "torso_pelvis", "arm_upper", "skirt", "leg", "foot", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 2,
	},
	body_wathgrithr_gladiator =
	{
		type = "body",
		skin_tags = { "LAVA", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "torso", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	body_wathgrithr_nature =
	{
		type = "body",
		skin_tags = { "VARG", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", },
		symbol_hides = { "arm_upper", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	body_wathgrithr_rose =
	{
		type = "body",
		skin_tags = { "ROSE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "hand", "arm_lower", "arm_lower_cuff", "arm_upper", "torso", "torso_pelvis", "leg", "foot", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 10,
	},
	body_wathgrithr_shadow =
	{
		type = "body",
		skin_tags = { "SHADOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "torso_pelvis", "arm_upper", "arm_upper_skin", "skirt", "torso_pelvis", "leg", "foot", "arm_lower", "hand", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 6,
	},
	body_wathgrithr_survivor =
	{
		type = "body",
		skin_tags = { "SURVIVOR", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "torso_pelvis", "arm_upper", "leg", "foot", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 4,
	},
	body_waxwell_formal =
	{
		type = "body",
		skin_tags = { "FORMAL", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 5,
	},
	body_waxwell_gladiator =
	{
		type = "body",
		skin_tags = { "LAVA", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "torso", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	body_waxwell_krampus =
	{
		type = "body",
		skin_tags = { "COSTUME", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_lower_cuff", "arm_upper_skin", "foot", "hand", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "arm_upper", "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		legs_cuff_size = 3,
		marketable = true,
		release_group = 31,
	},
	body_waxwell_nature =
	{
		type = "body",
		skin_tags = { "VARG", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	body_waxwell_rose =
	{
		type = "body",
		skin_tags = { "ROSE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "hand", "arm_lower", "arm_lower_cuff", "arm_upper", "torso", "torso_pelvis", "leg", "foot", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 10,
	},
	body_waxwell_survivor =
	{
		type = "body",
		skin_tags = { "SURVIVOR", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "torso_pelvis", "leg", "foot", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 5,
	},
	body_waxwell_unshadow =
	{
		type = "body",
		skin_tags = { "SHADOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "torso_pelvis", "leg", "foot", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 6,
	},
	body_webber_bat =
	{
		type = "body",
		skin_tags = { "COSTUME", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "foot", "hand", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 31,
	},
	body_webber_formal =
	{
		type = "body",
		skin_tags = { "FORMAL", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 2,
	},
	body_webber_gladiator =
	{
		type = "body",
		skin_tags = { "LAVA", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper_skin", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	body_webber_ice =
	{
		type = "body",
		skin_tags = { "ICE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "hand", "torso", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	body_webber_rose =
	{
		type = "body",
		skin_tags = { "ROSE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 10,
	},
	body_webber_shadow =
	{
		type = "body",
		skin_tags = { "SHADOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 6,
	},
	body_webber_survivor =
	{
		type = "body",
		skin_tags = { "SURVIVOR", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "foot", "hand", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 4,
	},
	body_wendy_formal =
	{
		type = "body",
		skin_tags = { "FORMAL", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "skirt", "leg", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 2,
	},
	body_wendy_gladiator =
	{
		type = "body",
		skin_tags = { "LAVA", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "leg", "skirt", "torso", "torso_pelvis", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	body_wendy_ice =
	{
		type = "body",
		skin_tags = { "ICE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "leg", "skirt", "torso", "torso_pelvis", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	body_wendy_lureplant =
	{
		type = "body",
		skin_tags = { "COSTUME", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "foot", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		legs_cuff_size = 2,
		marketable = true,
		release_group = 31,
	},
	body_wendy_rose =
	{
		type = "body",
		skin_tags = { "ROSE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "hand", "arm_lower", "arm_upper", "arm_upper_skin", "torso", "torso_pelvis", "leg", "skirt", "foot", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		marketable = true,
		release_group = 10,
	},
	body_wendy_shadow =
	{
		type = "body",
		skin_tags = { "SHADOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "foot", "hand", "leg", "skirt", "torso", "torso_pelvis", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		marketable = true,
		release_group = 6,
	},
	body_wendy_survivor =
	{
		type = "body",
		skin_tags = { "SURVIVOR", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "skirt", "leg", "foot", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		marketable = true,
		release_group = 4,
	},
	body_wes_formal =
	{
		type = "body",
		skin_tags = { "FORMAL", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "arm_upper", "arm_lower", "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		torso_tuck = "full",
		rarity = "Distinguished",
		marketable = true,
		release_group = 2,
	},
	body_wes_gladiator =
	{
		type = "body",
		skin_tags = { "LAVA", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "full",
		rarity = "Distinguished",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	body_wes_mandrake =
	{
		type = "body",
		skin_tags = { "COSTUME", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "arm_upper_skin", "foot", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "full",
		rarity = "Distinguished",
		legs_cuff_size = 2,
		marketable = true,
		release_group = 31,
	},
	body_wes_nature =
	{
		type = "body",
		skin_tags = { "VARG", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "leg", "skirt", "torso", "torso_pelvis", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	body_wes_rose =
	{
		type = "body",
		skin_tags = { "ROSE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "torso", "torso_pelvis", "leg", "foot", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 10,
	},
	body_wes_shadow =
	{
		type = "body",
		skin_tags = { "SHADOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper_skin", "foot", "hand", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", "arm_upper", },
		torso_tuck = "full",
		rarity = "Distinguished",
		marketable = true,
		release_group = 6,
	},
	body_wes_survivor =
	{
		type = "body",
		skin_tags = { "SURVIVOR", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "torso_pelvis", "leg", "foot", },
		symbol_hides = { "skirt", "arm_upper", },
		torso_tuck = "full",
		rarity = "Distinguished",
		marketable = true,
		release_group = 4,
	},
	body_wickerbottom_formal =
	{
		type = "body",
		skin_tags = { "FORMAL", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "skirt", },
		torso_tuck = "full",
		rarity = "Distinguished",
		marketable = true,
		release_group = 2,
	},
	body_wickerbottom_gladiator =
	{
		type = "body",
		skin_tags = { "LAVA", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "leg", "skirt", "torso", "torso_pelvis", },
		torso_tuck = "full",
		rarity = "Distinguished",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	body_wickerbottom_ice =
	{
		type = "body",
		skin_tags = { "ICE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "skirt", "torso", "torso_pelvis", },
		symbol_hides = { "arm_upper", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	body_wickerbottom_lightninggoat =
	{
		type = "body",
		skin_tags = { "COSTUME", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper_skin", "foot", "hand", "leg", "skirt", "torso", "torso_pelvis", },
		symbol_hides = { "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 31,
	},
	body_wickerbottom_rose =
	{
		type = "body",
		skin_tags = { "ROSE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "torso", "torso_pelvis", "leg", "skirt", "foot", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		marketable = true,
		release_group = 10,
	},
	body_wickerbottom_shadow =
	{
		type = "body",
		skin_tags = { "SHADOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_lower_cuff", "arm_upper", "arm_upper_skin", "foot", "leg", "skirt", "torso", "torso_pelvis", },
		torso_tuck = "full",
		rarity = "Distinguished",
		marketable = true,
		release_group = 6,
	},
	body_wickerbottom_survivor =
	{
		type = "body",
		skin_tags = { "SURVIVOR", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "skirt", "leg", "foot", },
		torso_tuck = "full",
		rarity = "Distinguished",
		marketable = true,
		release_group = 4,
	},
	body_willow_dragonfly =
	{
		type = "body",
		skin_tags = { "COSTUME", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "foot", "hand", "leg", "skirt", "torso", "torso_pelvis", },
		torso_tuck = "full",
		rarity = "Distinguished",
		marketable = true,
		release_group = 31,
	},
	body_willow_formal =
	{
		type = "body",
		skin_tags = { "FORMAL", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 2,
	},
	body_willow_gladiator =
	{
		type = "body",
		skin_tags = { "LAVA", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", },
		symbol_hides = { "arm_upper", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	body_willow_ice =
	{
		type = "body",
		skin_tags = { "ICE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper_skin", "skirt", "torso", },
		symbol_hides = { "arm_upper", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	body_willow_rose =
	{
		type = "body",
		skin_tags = { "ROSE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "hand", "arm_upper", "torso", "torso_pelvis", "skirt", "leg", "hand", "foot", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		marketable = true,
		release_group = 10,
	},
	body_willow_shadow =
	{
		type = "body",
		skin_tags = { "SHADOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "torso_pelvis", "arm_upper", "leg", "skirt", "foot", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 6,
	},
	body_willow_survivor =
	{
		type = "body",
		skin_tags = { "SURVIVOR", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "torso_pelvis", "arm_upper", "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 4,
	},
	body_wilson_formal =
	{
		type = "body",
		skin_tags = { "FORMAL", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "arm_lower", "leg", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 2,
	},
	body_wilson_gladiator =
	{
		type = "body",
		skin_tags = { "LAVA", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", },
		symbol_hides = { "arm_upper", },
		torso_tuck = "full",
		rarity = "Distinguished",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	body_wilson_ice =
	{
		type = "body",
		skin_tags = { "ICE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	body_wilson_pigguard =
	{
		type = "body",
		skin_tags = { "COSTUME", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "foot", "hand", "leg", "skirt", "torso", "torso_pelvis", },
		symbol_hides = { "arm_upper", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		legs_cuff_size = 3,
		feet_cuff_size = 3,
		marketable = true,
		release_group = 31,
	},
	body_wilson_rose =
	{
		type = "body",
		skin_tags = { "ROSE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "hand", "arm_lower", "arm_upper", "torso", "torso_pelvis", "leg", "foot", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 10,
	},
	body_wilson_shadow =
	{
		type = "body",
		skin_tags = { "SHADOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "torso_pelvis", "leg", "arm_upper", "arm_upper_skin", "arm_lower", "foot", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 6,
	},
	body_wilson_survivor =
	{
		type = "body",
		skin_tags = { "SURVIVOR", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "torso_pelvis", "leg", "arm_upper", "foot", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 4,
	},
	body_winona_formal =
	{
		type = "body",
		skin_tags = { "FORMAL", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "foot", "hand", "leg", "skirt", "torso", "torso_pelvis", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 30,
	},
	body_winona_gladiator =
	{
		type = "body",
		skin_tags = { "LAVA", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	body_winona_grassgecko =
	{
		type = "body",
		skin_tags = { "COSTUME", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "foot", "hand", "leg", "skirt", "torso", "torso_pelvis", },
		torso_tuck = "full",
		rarity = "Distinguished",
		legs_cuff_size = 5,
		feet_cuff_size = 5,
		marketable = true,
		release_group = 31,
	},
	body_winona_nature =
	{
		type = "body",
		skin_tags = { "VARG", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	body_winona_rose =
	{
		type = "body",
		skin_tags = { "ROSE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "foot", "hand", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		legs_cuff_size = 4,
		feet_cuff_size = 5,
		marketable = true,
		release_group = 30,
	},
	body_winona_shadow =
	{
		type = "body",
		skin_tags = { "SHADOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "foot", "hand", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		has_leg_boot = true,
		marketable = true,
		release_group = 30,
	},
	body_winona_survivor =
	{
		type = "body",
		skin_tags = { "SURVIVOR", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper_skin", "foot", "hand", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", "arm_upper", "arm_lower_cuff", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		legs_cuff_size = 4,
		feet_cuff_size = 5,
		marketable = true,
		release_group = 30,
	},
	body_wolfgang_formal =
	{
		type = "body",
		skin_tags = { "FORMAL", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "arm_upper_skin", "arm_lower", "torso", "torso_pelvis", "leg", "foot", },
		symbol_overrides_skinny = { arm_lower = "arm_lower_skinny", arm_upper = "arm_upper_skinny", arm_upper_skin = "arm_upper_skin_skinny", },
		symbol_overrides_mighty = { arm_lower = "arm_lower_mighty", arm_upper = "arm_upper_mighty", arm_upper_skin = "arm_upper_skin_mighty", torso = "torso_mighty", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 2,
	},
	body_wolfgang_gladiator =
	{
		type = "body",
		skin_tags = { "LAVA", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper_skin", "torso", },
		symbol_overrides_skinny = { arm_lower = "arm_lower_skinny", arm_upper_skin = "arm_upper_skin_skinny", },
		symbol_overrides_mighty = { arm_lower = "arm_lower_mighty", torso = "torso_mighty", },
		symbol_hides = { "arm_upper", },
		torso_tuck = "full",
		rarity = "Distinguished",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	body_wolfgang_ice =
	{
		type = "body",
		skin_tags = { "ICE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "skirt", "torso", },
		symbol_overrides_mighty = { arm_lower = "arm_lower_mighty", arm_upper = "arm_upper_mighty", arm_upper_skin = "arm_upper_skin_mighty", torso = "torso_mighty", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	body_wolfgang_rose =
	{
		type = "body",
		skin_tags = { "ROSE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "hand", "arm_lower", "arm_upper", "torso", "torso_pelvis", "leg", "foot", },
		symbol_overrides_skinny = { arm_lower = "arm_lower_skinny", arm_upper = "arm_upper_mighty", },
		symbol_overrides_mighty = { arm_lower = "arm_lower_mighty", arm_upper = "arm_upper_skinny", torso = "torso_mighty", },
		symbol_hides = { "skirt", "arm_upper_skin", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 10,
	},
	body_wolfgang_shadow =
	{
		type = "body",
		skin_tags = { "SHADOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "torso", "torso_pelvis", "leg", "foot", },
		symbol_overrides_skinny = { torso = "torso_skinny", torso_pelvis = "torso_pelvis_skinny", },
		symbol_overrides_mighty = { torso = "torso_mighty", torso_pelvis = "torso_pelvis_mighty", },
		symbol_hides = { "skirt", "arm_upper", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 6,
	},
	body_wolfgang_survivor =
	{
		type = "body",
		skin_tags = { "SURVIVOR", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "torso_pelvis", "leg", "foot", },
		symbol_overrides_skinny = { },
		symbol_overrides_mighty = { torso = "torso_mighty", torso_pelvis = "torso_pelvis_mighty", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		legs_cuff_size = 2,
		marketable = true,
		release_group = 4,
	},
	body_wolfgang_walrus =
	{
		type = "body",
		skin_tags = { "COSTUME", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "skirt", "torso", "torso_pelvis", },
		symbol_overrides_skinny = { torso_pelvis = "torso_pelvis_skinny", },
		symbol_overrides_mighty = { torso = "torso_mighty", torso_pelvis = "torso_pelvis_mighty", },
		symbol_hides = { "arm_upper", },
		torso_tuck = "full",
		rarity = "Distinguished",
		marketable = true,
		release_group = 31,
	},
	body_woodie_formal =
	{
		type = "body",
		skin_tags = { "FORMAL", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "arm_upper_skin", "arm_lower", "torso", "torso_pelvis", "skirt", "leg", },
		torso_tuck = "full",
		rarity = "Distinguished",
		marketable = true,
		release_group = 2,
	},
	body_woodie_gladiator =
	{
		type = "body",
		skin_tags = { "LAVA", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "torso", },
		torso_tuck = "full",
		rarity = "Distinguished",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	body_woodie_nature =
	{
		type = "body",
		skin_tags = { "VARG", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	body_woodie_rose =
	{
		type = "body",
		skin_tags = { "ROSE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "leg", "foot", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 10,
	},
	body_woodie_shadow =
	{
		type = "body",
		skin_tags = { "SHADOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_lower_cuff", "arm_upper", "arm_upper_skin", "foot", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 6,
	},
	body_woodie_survivor =
	{
		type = "body",
		skin_tags = { "SURVIVOR", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "torso", "torso_pelvis", "leg", "foot", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 4,
	},
	body_woodie_treeguard =
	{
		type = "body",
		skin_tags = { "COSTUME", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "foot", "hand", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		legs_cuff_size = 5,
		feet_cuff_size = 5,
		marketable = true,
		release_group = 31,
	},
	body_wx78_formal =
	{
		type = "body",
		skin_tags = { "FORMAL", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		marketable = true,
		release_group = 2,
	},
	body_wx78_gladiator =
	{
		type = "body",
		skin_tags = { "LAVA", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	body_wx78_nature =
	{
		type = "body",
		skin_tags = { "VARG", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	body_wx78_rhinorook =
	{
		type = "body",
		skin_tags = { "COSTUME", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "arm_upper", "foot", "hand", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		feet_cuff_size = 5,
		marketable = true,
		release_group = 31,
	},
	body_wx78_rose =
	{
		type = "body",
		skin_tags = { "ROSE", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 10,
	},
	body_wx78_shadow =
	{
		type = "body",
		skin_tags = { "SHADOW", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		marketable = true,
		release_group = 6,
	},
	body_wx78_survivor =
	{
		type = "body",
		skin_tags = { "SURVIVOR", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		marketable = true,
		release_group = 4,
	},
	body_yule_coat =
	{
		type = "body",
		skin_tags = { "WINTER", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "foot", "hand", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Event",
		release_group = 22,
	},
	body_yule_dress =
	{
		type = "body",
		skin_tags = { "WINTER", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_lower_cuff", "arm_upper", "foot", "hand", "leg", "skirt", "torso", "torso_pelvis", },
		torso_tuck = "skirt",
		rarity = "Event",
		release_group = 22,
	},
	body_yuled_coat =
	{
		type = "body",
		skin_tags = { "WINTER", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "foot", "hand", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		torso_tuck = "untucked",
		rarity = "Distinguished",
		marketable = true,
		release_group = 35,
	},
	body_yuled_dress =
	{
		type = "body",
		skin_tags = { "WINTER", "CLOTHING_BODY", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_lower_cuff", "arm_upper", "foot", "hand", "leg", "skirt", "torso", "torso_pelvis", },
		torso_tuck = "skirt",
		rarity = "Distinguished",
		marketable = true,
		release_group = 35,
	},
	feet_bootie_black_scribble =
	{
		type = "feet",
		skin_tags = { "BLACK", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		marketable = true,
		release_group = 7,
	},
	feet_bunnyslippers_purple_mauve =
	{
		type = "feet",
		skin_tags = { "PURPLE", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Distinguished",
		feet_cuff_size = 3,
		marketable = true,
		release_group = 7,
	},
	feet_fleece_boot_brown_sepia =
	{
		type = "feet",
		skin_tags = { "FORMAL", "BROWN", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		feet_cuff_size = 5,
		marketable = true,
		release_group = 2,
	},
	feet_formal_highheel_white_pure =
	{
		type = "feet",
		skin_tags = { "FORMAL", "WHITE", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		feet_cuff_size = 5,
		marketable = true,
		release_group = 2,
	},
	feet_formal_lowheel_black_scribble =
	{
		type = "feet",
		skin_tags = { "FORMAL", "BLACK", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		marketable = true,
		release_group = 2,
	},
	feet_formal_stiletto_black_scribble =
	{
		type = "feet",
		skin_tags = { "FORMAL", "BLACK", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		marketable = true,
		release_group = 2,
	},
	feet_fuzzyslippers_blue_ice =
	{
		type = "feet",
		skin_tags = { "BLUE", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Distinguished",
		feet_cuff_size = 5,
		marketable = true,
		release_group = 7,
	},
	feet_maryjanes_white_pure =
	{
		type = "feet",
		skin_tags = { "FORMAL", "WHITE", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		marketable = true,
		release_group = 2,
	},
	feet_ridingboot_white_pure =
	{
		type = "feet",
		skin_tags = { "FORMAL", "WHITE", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		feet_cuff_size = 10,
		marketable = true,
		release_group = 2,
	},
	feet_sandals_blue_catcoon =
	{
		type = "feet",
		skin_tags = { "BLUE", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		feet_cuff_size = 5,
		marketable = true,
		release_group = 14,
	},
	feet_slippers_rooster_white_pure =
	{
		type = "feet",
		skin_tags = { "LUNAR", "WHITE", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Event",
		feet_cuff_size = 3,
		release_group = 23,
	},
	feet_sneakers_blue_catcoon =
	{
		type = "feet",
		skin_tags = { "BLUE", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		marketable = true,
		release_group = 3,
	},
	feet_sneakers_green_cactus =
	{
		type = "feet",
		skin_tags = { "GREEN", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		marketable = true,
		release_group = 3,
	},
	feet_sneakers_orange_carrot =
	{
		type = "feet",
		skin_tags = { "ORANGE", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		marketable = true,
		release_group = 7,
	},
	feet_sneakers_red_auburn =
	{
		type = "feet",
		skin_tags = { "RED", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		marketable = true,
		release_group = 3,
	},
	feet_wathgrithr_gladiator =
	{
		type = "feet",
		skin_tags = { "LAVA", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	feet_wathgrithr_nature =
	{
		type = "feet",
		skin_tags = { "VARG", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	feet_waxwell_gladiator =
	{
		type = "feet",
		skin_tags = { "LAVA", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	feet_waxwell_nature =
	{
		type = "feet",
		skin_tags = { "VARG", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		feet_cuff_size = 5,
		release_group = 40,
	},
	feet_webber_gladiator =
	{
		type = "feet",
		skin_tags = { "LAVA", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	feet_webber_ice =
	{
		type = "feet",
		skin_tags = { "ICE", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		feet_cuff_size = 3,
		release_group = 36,
	},
	feet_wendy_gladiator =
	{
		type = "feet",
		skin_tags = { "LAVA", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		feet_cuff_size = 5,
		release_group = 32,
	},
	feet_wendy_ice =
	{
		type = "feet",
		skin_tags = { "ICE", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		feet_cuff_size = 3,
		release_group = 36,
	},
	feet_wes_gladiator =
	{
		type = "feet",
		skin_tags = { "LAVA", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	feet_wes_nature =
	{
		type = "feet",
		skin_tags = { "VARG", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		feet_cuff_size = 5,
		release_group = 40,
	},
	feet_wickerbottom_gladiator =
	{
		type = "feet",
		skin_tags = { "LAVA", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	feet_wickerbottom_ice1 =
	{
		type = "feet",
		skin_tags = { "ICE", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		feet_cuff_size = 5,
		release_group = 36,
	},
	feet_willow_gladiator =
	{
		type = "feet",
		skin_tags = { "LAVA", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		feet_cuff_size = 5,
		release_group = 32,
	},
	feet_willow_ice =
	{
		type = "feet",
		skin_tags = { "ICE", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		feet_cuff_size = 5,
		release_group = 36,
	},
	feet_wilson_gladiator =
	{
		type = "feet",
		skin_tags = { "LAVA", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		feet_cuff_size = 5,
		release_group = 32,
	},
	feet_wilson_ice =
	{
		type = "feet",
		skin_tags = { "ICE", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		feet_cuff_size = 5,
		release_group = 36,
	},
	feet_winona_gladiator =
	{
		type = "feet",
		skin_tags = { "LAVA", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		feet_cuff_size = 5,
		release_group = 32,
	},
	feet_winona_nature =
	{
		type = "feet",
		skin_tags = { "VARG", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		feet_cuff_size = 5,
		release_group = 40,
	},
	feet_wolfgang_gladiator =
	{
		type = "feet",
		skin_tags = { "LAVA", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		feet_cuff_size = 5,
		release_group = 32,
	},
	feet_wolfgang_ice =
	{
		type = "feet",
		skin_tags = { "ICE", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		feet_cuff_size = 5,
		release_group = 36,
	},
	feet_woodie_gladiator =
	{
		type = "feet",
		skin_tags = { "LAVA", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	feet_woodie_nature =
	{
		type = "feet",
		skin_tags = { "VARG", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		feet_cuff_size = 4,
		release_group = 40,
	},
	feet_workboot_brown_chocolate =
	{
		type = "feet",
		skin_tags = { "BROWN", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		feet_cuff_size = 5,
		marketable = true,
		release_group = 7,
	},
	feet_workboot_tan_clay =
	{
		type = "feet",
		skin_tags = { "TAN", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		feet_cuff_size = 5,
		marketable = true,
		release_group = 7,
	},
	feet_wx78_gladiator =
	{
		type = "feet",
		skin_tags = { "LAVA", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		feet_cuff_size = 5,
		release_group = 32,
	},
	feet_wx78_nature =
	{
		type = "feet",
		skin_tags = { "VARG", "CLOTHING_FEET", "CLOTHING", },
		symbol_overrides = { "foot", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		feet_cuff_size = 5,
		release_group = 40,
	},
	hand_beltedgloves_brown_beaver =
	{
		type = "hand",
		skin_tags = { "BROWN", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		rarity = "Classy",
		marketable = true,
		release_group = 1,
	},
	hand_beltedgloves_red_firehound =
	{
		type = "hand",
		skin_tags = { "RED", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		rarity = "Classy",
		marketable = true,
		release_group = 7,
	},
	hand_beltedgloves_teal_jungle =
	{
		type = "hand",
		skin_tags = { "TEAL", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		rarity = "Classy",
		marketable = true,
		release_group = 7,
	},
	hand_drivergloves_white_ivory =
	{
		type = "hand",
		skin_tags = { "WHITE", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		rarity = "Classy",
		marketable = true,
		release_group = 1,
	},
	hand_longgloves_green_hunters =
	{
		type = "hand",
		skin_tags = { "GREEN", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "hand", },
		marketable = true,
		release_group = 3,
	},
	hand_longgloves_grey_battleship =
	{
		type = "hand",
		skin_tags = { "GREY", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "hand", },
		marketable = true,
		release_group = 0,
	},
	hand_longgloves_white_pure =
	{
		type = "hand",
		skin_tags = { "WHITE", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "hand", },
		marketable = true,
		release_group = 7,
	},
	hand_longgloves_yellow_straw =
	{
		type = "hand",
		skin_tags = { "YELLOW", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "hand", },
		marketable = true,
		release_group = 0,
	},
	hand_shortgloves_black_scribble =
	{
		type = "hand",
		skin_tags = { "BLACK", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		marketable = true,
		release_group = 0,
	},
	hand_shortgloves_blue_cornflower =
	{
		type = "hand",
		skin_tags = { "BLUE", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		marketable = true,
		release_group = 3,
	},
	hand_shortgloves_red_higgsbury =
	{
		type = "hand",
		skin_tags = { "RED", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		marketable = true,
		release_group = 0,
	},
	hand_shortgloves_white_smoke =
	{
		type = "hand",
		skin_tags = { "WHITE", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		marketable = true,
		release_group = 0,
	},
	hand_wathgrithr_gladiator =
	{
		type = "hand",
		skin_tags = { "LAVA", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	hand_wathgrithr_nature =
	{
		type = "hand",
		skin_tags = { "VARG", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "arm_upper", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	hand_waxwell_formal =
	{
		type = "hand",
		skin_tags = { "FORMAL", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", "arm_lower_cuff", },
		rarity = "Classy",
		marketable = true,
		release_group = 5,
	},
	hand_waxwell_gladiator =
	{
		type = "hand",
		skin_tags = { "LAVA", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "hand", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	hand_waxwell_nature =
	{
		type = "hand",
		skin_tags = { "VARG", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	hand_webber_gladiator =
	{
		type = "hand",
		skin_tags = { "LAVA", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	hand_wendy_gladiator =
	{
		type = "hand",
		skin_tags = { "LAVA", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "hand", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	hand_wendy_ice =
	{
		type = "hand",
		skin_tags = { "ICE", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	hand_wes_gladiator =
	{
		type = "hand",
		skin_tags = { "LAVA", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	hand_wes_nature =
	{
		type = "hand",
		skin_tags = { "VARG", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	hand_wickerbottom_gladiator =
	{
		type = "hand",
		skin_tags = { "LAVA", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	hand_wickerbottom_ice =
	{
		type = "hand",
		skin_tags = { "ICE", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "arm_lower", "arm_upper_skin", "hand", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	hand_willow_gladiator =
	{
		type = "hand",
		skin_tags = { "LAVA", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "arm_upper", },
		base_fallbacks = { "arm_lower", "arm_upper_skin", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	hand_willow_ice =
	{
		type = "hand",
		skin_tags = { "ICE", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	hand_wilson_formal =
	{
		type = "hand",
		skin_tags = { "FORMAL", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", "arm_lower_cuff", },
		rarity = "Classy",
		marketable = true,
		release_group = 2,
	},
	hand_wilson_gladiator =
	{
		type = "hand",
		skin_tags = { "LAVA", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	hand_wilson_ice =
	{
		type = "hand",
		skin_tags = { "ICE", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "hand", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	hand_winona_gladiator =
	{
		type = "hand",
		skin_tags = { "LAVA", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	hand_winona_nature =
	{
		type = "hand",
		skin_tags = { "VARG", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "hand", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	hand_wolfgang_gladiator =
	{
		type = "hand",
		skin_tags = { "LAVA", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	hand_wolfgang_ice =
	{
		type = "hand",
		skin_tags = { "ICE", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "hand", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	hand_woodie_gladiator =
	{
		type = "hand",
		skin_tags = { "LAVA", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "hand", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	hand_woodie_nature =
	{
		type = "hand",
		skin_tags = { "VARG", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "hand", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	hand_wx78_gladiator =
	{
		type = "hand",
		skin_tags = { "LAVA", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "hand", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	hand_wx78_nature =
	{
		type = "hand",
		skin_tags = { "VARG", "CLOTHING_HAND", "CLOTHING", },
		symbol_overrides = { "arm_lower_cuff", "hand", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	legs_checkered_pleats_blue_cornflower =
	{
		type = "legs",
		skin_tags = { "BLUE", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		rarity = "Classy",
		legs_cuff_size = 2,
		marketable = true,
		release_group = 0,
	},
	legs_checkered_pleats_green_laurel =
	{
		type = "legs",
		skin_tags = { "GREEN", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		rarity = "Classy",
		legs_cuff_size = 2,
		marketable = true,
		release_group = 1,
	},
	legs_pants_basic_black_scribble =
	{
		type = "legs",
		skin_tags = { "BLACK", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		legs_cuff_size = 2,
		marketable = true,
		release_group = 1,
	},
	legs_pants_basic_brown_sepia =
	{
		type = "legs",
		skin_tags = { "BROWN", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		legs_cuff_size = 2,
		marketable = true,
		release_group = 0,
	},
	legs_pants_basic_green_forest =
	{
		type = "legs",
		skin_tags = { "GREEN", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		legs_cuff_size = 2,
		marketable = true,
		release_group = 7,
	},
	legs_pants_basic_grey_dark =
	{
		type = "legs",
		skin_tags = { "GREY", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		legs_cuff_size = 2,
		marketable = true,
		release_group = 0,
	},
	legs_pants_basic_tan_cream =
	{
		type = "legs",
		skin_tags = { "TAN", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		legs_cuff_size = 2,
		marketable = true,
		release_group = 0,
	},
	legs_pj_blue_agean =
	{
		type = "legs",
		skin_tags = { "BLUE", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		rarity = "Spiffy",
		legs_cuff_size = 2,
		marketable = true,
		release_group = 20,
	},
	legs_pj_purple_mauve =
	{
		type = "legs",
		skin_tags = { "PURPLE", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		rarity = "Spiffy",
		legs_cuff_size = 2,
		marketable = true,
		release_group = 7,
	},
	legs_skirt_basic_black_scribble =
	{
		type = "legs",
		skin_tags = { "BLACK", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "skirt", },
		marketable = true,
		release_group = 1,
	},
	legs_skirt_basic_brown_sepia =
	{
		type = "legs",
		skin_tags = { "BROWN", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "skirt", },
		marketable = true,
		release_group = 0,
	},
	legs_skirt_basic_grey_dark =
	{
		type = "legs",
		skin_tags = { "GREY", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "skirt", },
		marketable = true,
		release_group = 0,
	},
	legs_skirt_basic_pink_pigman =
	{
		type = "legs",
		skin_tags = { "PINK", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "skirt", },
		marketable = true,
		release_group = 7,
	},
	legs_skirt_basic_tan_cream =
	{
		type = "legs",
		skin_tags = { "TAN", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "skirt", },
		marketable = true,
		release_group = 0,
	},
	legs_skirt_plaid_blue_cornflower =
	{
		type = "legs",
		skin_tags = { "BLUE", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "skirt", },
		rarity = "Classy",
		marketable = true,
		release_group = 0,
	},
	legs_skirt_plaid_green_pistachio =
	{
		type = "legs",
		skin_tags = { "GREEN", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "skirt", },
		rarity = "Classy",
		marketable = true,
		release_group = 1,
	},
	legs_tweed_knickerbocker_green_hunters =
	{
		type = "legs",
		skin_tags = { "GREEN", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		rarity = "Classy",
		marketable = true,
		release_group = 7,
	},
	legs_tweed_knickerbocker_tan_grass =
	{
		type = "legs",
		skin_tags = { "TAN", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		rarity = "Classy",
		marketable = true,
		release_group = 7,
	},
	legs_wathgrithr_gladiator =
	{
		type = "legs",
		skin_tags = { "LAVA", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "leg", "torso_pelvis", },
		symbol_hides = { "skirt", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	legs_wathgrithr_nature =
	{
		type = "legs",
		skin_tags = { "VARG", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "leg", "skirt", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		legs_cuff_size = 3,
		release_group = 40,
	},
	legs_waxwell_gladiator =
	{
		type = "legs",
		skin_tags = { "LAVA", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "leg", "skirt", "torso_pelvis", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	legs_waxwell_nature =
	{
		type = "legs",
		skin_tags = { "VARG", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "leg", "skirt", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	legs_webber_ice =
	{
		type = "legs",
		skin_tags = { "ICE", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "leg", "torso_pelvis", },
		symbol_hides = { "skirt", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		legs_cuff_size = 3,
		release_group = 36,
	},
	legs_willow_gladiator =
	{
		type = "legs",
		skin_tags = { "LAVA", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "skirt", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	legs_wilson_gladiator =
	{
		type = "legs",
		skin_tags = { "LAVA", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "leg", "torso_pelvis", },
		symbol_hides = { "skirt", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	legs_wilson_ice =
	{
		type = "legs",
		skin_tags = { "ICE", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "leg", "torso_pelvis", },
		symbol_hides = { "skirt", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	legs_winona_gladiator =
	{
		type = "legs",
		skin_tags = { "LAVA", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "leg", "torso_pelvis", },
		symbol_hides = { "skirt", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		legs_cuff_size = 3,
		release_group = 32,
	},
	legs_winona_nature =
	{
		type = "legs",
		skin_tags = { "VARG", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "leg", "torso_pelvis", },
		symbol_hides = { "skirt", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		legs_cuff_size = 3,
		release_group = 40,
	},
	legs_wolfgang_gladiator =
	{
		type = "legs",
		skin_tags = { "LAVA", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "torso_pelvis", },
		symbol_hides = { "skirt", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	legs_wolfgang_ice =
	{
		type = "legs",
		skin_tags = { "ICE", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "leg", "torso_pelvis", },
		symbol_hides = { "skirt", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		legs_cuff_size = 3,
		release_group = 36,
	},
	legs_woodie_gladiator =
	{
		type = "legs",
		skin_tags = { "LAVA", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "leg", "torso_pelvis", },
		symbol_hides = { "skirt", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		legs_cuff_size = 2,
		release_group = 32,
	},
	legs_woodie_nature =
	{
		type = "legs",
		skin_tags = { "VARG", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "leg", "torso_pelvis", },
		symbol_hides = { "skirt", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		legs_cuff_size = 5,
		release_group = 40,
	},
	legs_wx78_gladiator =
	{
		type = "legs",
		skin_tags = { "LAVA", "CLOTHING_LEGS", "CLOTHING", },
		symbol_overrides = { "leg", "torso_pelvis", },
		symbol_hides = { "skirt", },
		rarity = "Spiffy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
}

CLOTHING_SYMBOLS = {}
HIDE_SYMBOLS = {}
for _,v in pairs(CLOTHING) do
	for _,sym in pairs(v.symbol_overrides) do
		table.insert( CLOTHING_SYMBOLS, sym )
	end
	if v.symbol_hides then
		for _,sym in pairs(v.symbol_hides) do
			table.insert( HIDE_SYMBOLS, sym )
		end
	end
end