-- AUTOGENERATED CODE BY export_accountitems.lua

EMOJI_ITEMS =
{
	emoji_arcane =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "arcane",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_arcane",
			requires_validation = true,
			utf8_str = "󰀀",
		},
	},
	emoji_beefalo =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "beefalo",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_beefalo",
			requires_validation = true,
			utf8_str = "󰀁",
		},
	},
	emoji_chest =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "chest",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_chest",
			requires_validation = true,
			utf8_str = "󰀂",
		},
	},
	emoji_chester =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "chester",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_chester",
			requires_validation = true,
			utf8_str = "󰀃",
		},
	},
	emoji_crockpot =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "crockpot",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_crockpot",
			requires_validation = true,
			utf8_str = "󰀄",
		},
	},
	emoji_eyeball =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "eyeball",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_eyeball",
			requires_validation = true,
			utf8_str = "󰀅",
		},
	},
	emoji_faketeeth =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "faketeeth",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_faketeeth",
			requires_validation = true,
			utf8_str = "󰀆",
		},
	},
	emoji_farm =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "farm",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_farm",
			requires_validation = true,
			utf8_str = "󰀇",
		},
	},
	emoji_fire =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "fire",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_fire",
			requires_validation = true,
			utf8_str = "󰀈",
		},
	},
	emoji_ghost =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "ghost",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_ghost",
			requires_validation = true,
			utf8_str = "󰀉",
		},
	},
	emoji_grave =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "grave",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_grave",
			requires_validation = true,
			utf8_str = "󰀊",
		},
	},
	emoji_hambat =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "hambat",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_hambat",
			requires_validation = true,
			utf8_str = "󰀋",
		},
	},
	emoji_hammer =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "hammer",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_hammer",
			requires_validation = true,
			utf8_str = "󰀌",
		},
	},
	emoji_heart =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "heart",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_heart",
			requires_validation = true,
			utf8_str = "󰀍",
		},
	},
	emoji_hunger =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "hunger",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_hunger",
			requires_validation = true,
			utf8_str = "󰀎",
		},
	},
	emoji_lightbulb =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "lightbulb",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_lightbulb",
			requires_validation = true,
			utf8_str = "󰀏",
		},
	},
	emoji_pig =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "pig",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_pig",
			requires_validation = true,
			utf8_str = "󰀐",
		},
	},
	emoji_poop =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "poop",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_poop",
			requires_validation = true,
			utf8_str = "󰀑",
		},
	},
	emoji_redgem =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "redgem",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_redgem",
			requires_validation = true,
			utf8_str = "󰀒",
		},
	},
	emoji_sanity =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "sanity",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_sanity",
			requires_validation = true,
			utf8_str = "󰀓",
		},
	},
	emoji_sciencemachine =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "sciencemachine",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_sciencemachine",
			requires_validation = true,
			utf8_str = "󰀔",
		},
	},
	emoji_skull =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "skull",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_skull",
			requires_validation = true,
			utf8_str = "󰀕",
		},
	},
	emoji_tophat =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "tophat",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_tophat",
			requires_validation = true,
			utf8_str = "󰀖",
		},
	},
	emoji_web =
	{
		rarity = "Common",
		rarity_modifier = "EventModifier",
		input_name = "web",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_web",
			requires_validation = true,
			utf8_str = "󰀗",
		},
	},
}

