local function FinalOffset1(inst)
    inst.AnimState:SetFinalOffset(1)
end

local function FinalOffset2(inst)
    inst.AnimState:SetFinalOffset(2)
end

local function FinalOffset3(inst)
    inst.AnimState:SetFinalOffset(3)
end
local fx =
{
    {
        name = "sanity_raise",
        bank = "blocker_sanity_fx",
        build = "blocker_sanity_fx",
        anim = "raise",
        tintalpha = 0.5,
    },
    {
        name = "sanity_lower",
        bank = "blocker_sanity_fx",
        build = "blocker_sanity_fx",
        anim = "lower",
        tintalpha = 0.5,
    },
    {
        name = "die_fx",
        bank = "die_fx",
        build = "die",
        anim = "small",
        sound = "dontstarve/common/deathpoof",
        tint = Vector3(90/255, 66/255, 41/255),
    },
    {
        name = "lightning_rod_fx",
        bank = "lightning_rod_fx",
        build = "lightning_rod_fx",
        anim = "idle",
    },
    {
        name = "splash",
        bank = "splash",
        build = "splash",
        anim = "splash",
        fn = FinalOffset1,
    },
    {
        name = "frogsplash",
        bank = "splash",
        build = "splash",
        anim = "splash",
        sound = "dontstarve/frog/splash",
        fn = FinalOffset1,
    },
    {
        name = "waterballoon_splash",
        bank = "waterballoon",
        build = "waterballoon",
        anim = "used",
        sound = "dontstarve/creatures/pengull/splash",
    },
    {
        name = "spat_splat_fx",
        bank = "spat_splat",
        build = "spat_splat",
        anim = "idle",
    },
    {
        name = "spat_splash_fx_full",
        bank = "spat_splash",
        build = "spat_splash",
        anim = "full",
    },
    {
        name = "spat_splash_fx_med",
        bank = "spat_splash",
        build = "spat_splash",
        anim = "med",
    },
    {
        name = "spat_splash_fx_low",
        bank = "spat_splash",
        build = "spat_splash",
        anim = "low",
    },
    {
        name = "spat_splash_fx_melted", 
        bank = "spat_splash", 
        build = "spat_splash", 
        anim = "melted",
    },
    {
        name = "small_puff",
        bank = "small_puff",
        build = "smoke_puff_small",
        anim = "puff",
        sound = "dontstarve/common/deathpoof",
    },
    {
        name = "sand_puff",
        bank = "sand_puff",
        build = "sand_puff",
        anim = "forage_out",
        sound = "dontstarve/common/deathpoof",
    },
    {
        name = "sand_puff_large_front",
        bank = "sand_puff",
        build = "sand_puff",
        anim = "forage_out",
        sound = "dontstarve/common/deathpoof",
        transform = Vector3(1.5, 1.5, 1.5),
        fn = function(inst)
            inst.AnimState:SetFinalOffset(2)
            inst.AnimState:Hide("back")
        end,
    },
    {
        name = "sand_puff_large_back",
        bank = "sand_puff",
        build = "sand_puff",
        anim = "forage_out",
        transform = Vector3(1.5, 1.5, 1.5),
        fn = function(inst)
            inst.AnimState:Hide("front")
        end,
    },
    {
        name = "shadow_puff_large_front",
        bank = "sand_puff",
        build = "sand_puff",
        anim = "forage_out",
        sound = "dontstarve/common/deathpoof",
        transform = Vector3(1.5, 1.5, 1.5),
        tint = Vector3(0, 0, 0),
        tintalpha = .5,
        fn = function(inst)
            inst.AnimState:SetFinalOffset(2)
            inst.AnimState:Hide("back")
        end,
    },
    {
        name = "shadow_puff_large_back",
        bank = "sand_puff",
        build = "sand_puff",
        anim = "forage_out",
        transform = Vector3(1.5, 1.5, 1.5),
        tint = Vector3(0, 0, 0),
        tintalpha = .5,
        fn = function(inst)
            inst.AnimState:Hide("front")
        end,
    },
    {
        name = "splash_ocean",
        bank = "splash",
        build = "splash_ocean",
        anim = "idle",
    },
    {
        name = "maxwell_smoke",
        bank = "max_fx",
        build = "max_fx",
        anim = "anim",
    },
    {
        name = "shovel_dirt",
        bank = "shovel_dirt",
        build = "shovel_dirt",
        anim = "anim",
    },
    {
        name = "mining_fx",
        bank = "mining_fx",
        build = "mining_fx",
        anim = "anim",
    },
    {
        name = "mining_ice_fx",
        bank = "mining_fx",
        build = "mining_ice_fx",
        anim = "anim",
    },
    --[[{
        name = "pine_needles",
        bank = "pine_needles",
        build = "pine_needles",
        anim = "fall",
    },]]
    {
        name = "pine_needles_chop",
        bank = "pine_needles",
        build = "pine_needles",
        anim = "chop",
    },
    {
        name = "green_leaves_chop",
        bank = "tree_leaf_fx",
        build = "tree_leaf_fx_green",
        anim = "chop",
        sound = "dontstarve_DLC001/fall/leaf_rustle",
    },
    {
        name = "red_leaves_chop",
        bank = "tree_leaf_fx",
        build = "tree_leaf_fx_red",
        anim = "chop",
        sound = "dontstarve_DLC001/fall/leaf_rustle",
    },
    {
        name = "orange_leaves_chop",
        bank = "tree_leaf_fx",
        build = "tree_leaf_fx_orange",
        anim = "chop",
        sound = "dontstarve_DLC001/fall/leaf_rustle",
    },
    {
        name = "yellow_leaves_chop",
        bank = "tree_leaf_fx",
        build = "tree_leaf_fx_yellow",
        anim = "chop",
        sound = "dontstarve_DLC001/fall/leaf_rustle",
    },
    {
        name = "purple_leaves_chop",
        bank = "tree_monster_fx",
        build = "tree_monster_fx",
        anim = "chop",
        sound = "dontstarve_DLC001/fall/leaf_rustle",
    },
    {
        name = "green_leaves",
        bank = "tree_leaf_fx",
        build = "tree_leaf_fx_green",
        anim = "fall",
        sound = "dontstarve_DLC001/fall/leaf_rustle",
    },
    {
        name = "red_leaves",
        bank = "tree_leaf_fx",
        build = "tree_leaf_fx_red",
        anim = "fall",
        sound = "dontstarve_DLC001/fall/leaf_rustle",
    },
    {
        name = "orange_leaves",
        bank = "tree_leaf_fx",
        build = "tree_leaf_fx_orange",
        anim = "fall",
        sound = "dontstarve_DLC001/fall/leaf_rustle",
    },
    {
        name = "yellow_leaves",
        bank = "tree_leaf_fx",
        build = "tree_leaf_fx_yellow",
        anim = "fall",
        sound = "dontstarve_DLC001/fall/leaf_rustle",
    },
    {
        name = "purple_leaves",
        bank = "tree_monster_fx",
        build = "tree_monster_fx",
        anim = "fall",
        sound = "dontstarve_DLC001/fall/leaf_rustle",
    },
    {
        name = "sugarwood_leaf_fx",
        bank = "tree_leaf_fx_quagmire",
        build = "tree_leaf_fx_quagmire",
        anim = "fall",
        sound = "dontstarve_DLC001/fall/leaf_rustle",
    },
    {
        name = "sugarwood_leaf_fx_chop",
        bank = "tree_leaf_fx_quagmire",
        build = "tree_leaf_fx_quagmire",
        anim = "chop",
        sound = "dontstarve_DLC001/fall/leaf_rustle",
    },
    {
        name = "sugarwood_leaf_withered_fx",
        bank = "tree_leaf_fx_quagmire_withered",
        build = "tree_leaf_fx_quagmire_withered",
        anim = "fall",
        sound = "dontstarve_DLC001/fall/leaf_rustle",
    },
    {
        name = "sugarwood_leaf_withered_fx_chop",
        bank = "tree_leaf_fx_quagmire_withered",
        build = "tree_leaf_fx_quagmire_withered",
        anim = "chop",
        sound = "dontstarve_DLC001/fall/leaf_rustle",
    },
    {
        name = "dr_warm_loop_1",
        bank = "diviningrod_fx",
        build = "diviningrod_fx",
        anim = "warm_loop",
        tint = Vector3(105/255, 160/255, 255/255),
    },
    {
        name = "dr_warm_loop_2",
        bank = "diviningrod_fx",
        build = "diviningrod_fx",
        anim = "warm_loop",
        tint = Vector3(105/255, 182/255, 239/255),
    },
    {
        name = "dr_warmer_loop",
        bank = "diviningrod_fx",
        build = "diviningrod_fx",
        anim = "warmer_loop",
        tint = Vector3(255/255, 163/255, 26/255),
    },
    {
        name = "dr_hot_loop",
        bank = "diviningrod_fx",
        build = "diviningrod_fx",
        anim = "hot_loop",
        tint = Vector3(181/255, 32/255, 32/255),
    },
    {
        name = "statue_transition",
        bank = "statue_ruins_fx",
        build = "statue_ruins_fx",
        anim = "transform_nightmare",
        tintalpha = 0.6,
    },
    {
        name = "statue_transition_2",
        bank = "die_fx",
        build = "die",
        anim = "small",
        sound = "dontstarve/common/deathpoof",
        tint = Vector3(0, 0, 0),
        tintalpha = 0.6,
    },
    {
        name = "slurper_respawn",
        bank = "die_fx",
        build = "die",
        anim = "small",
        sound = "dontstarve/common/deathpoof",
        tint = Vector3(0, 0, 0),
        tintalpha = 1.0,
    },
    {
        name = "pandorachest_reset",
        bank = "attune_fx",
        build = "attune_fx",
        anim = "attune_in",
        --sound = "dontstarve/maxwell/shadowmax_despawn",
        tint = Vector3(0, 0, 0),
        tintalpha = 0.6,
    },
    {
        name = "shadow_despawn",
        bank = "statue_ruins_fx",
        build = "statue_ruins_fx",
        anim = "transform_nightmare",
        sound = "dontstarve/maxwell/shadowmax_despawn",
        tintalpha = 0.6,
    },
    {
        name = "mole_move_fx",
        bank = "mole_fx",
        build = "mole_move_fx",
        anim = "move",
        nameoverride = STRINGS.NAMES.MOLE_UNDERGROUND,
        description = function(inst, viewer)
            return GetString(viewer, "DESCRIBE", { "MOLE", "UNDERGROUND" })
        end,
    },
    --[[{
        name = "sparklefx",
        bank = "sparklefx",
        build = "sparklefx",
        anim = "sparkle",
        sound = "dontstarve/common/chest_positive",
        tintalpha = 0.6,
    },]]
    {
        name = "chester_transform_fx",
        bank = "die_fx",
        build = "die",
        anim = "small",
    },
    {
        name = "emote_fx",
        bank = "emote_fx",
        build = "emote_fx",
        anim = "emote_fx",
        autorotate = true,
        fn = FinalOffset1,
    },
    {
        name = "tears",
        bank = "tears_fx",
        build = "tears",
        anim = "tears_fx",
        autorotate = true,
        fn = FinalOffset1,
    },
    {
        name = "spawn_fx_tiny",
        bank = "spawn_fx",
        build = "puff_spawning",
        anim = "tiny",
        sound = "dontstarve/common/spawn/spawnportal_spawnplayer",
    },
    {
        name = "spawn_fx_small",
        bank = "spawn_fx",
        build = "puff_spawning",
        anim = "small",
        sound = "dontstarve/common/spawn/spawnportal_spawnplayer",
    },
    {
        name = "spawn_fx_medium",
        bank = "spawn_fx",
        build = "puff_spawning",
        anim = "medium",
        sound = "dontstarve/common/spawn/spawnportal_spawnplayer",
    },
    --[[{
        name = "spawn_fx_large",
        bank = "spawn_fx",
        build = "puff_spawning",
        anim = "large",
        sound = "dontstarve/common/spawn/spawnportal_spawnplayer",
    },]]
    --[[{
        name = "spawn_fx_huge",
        bank = "spawn_fx",
        build = "puff_spawning",
        anim = "huge",
        sound = "dontstarve/common/spawn/spawnportal_spawnplayer",
    },]]
    {
        name = "spawn_fx_small_high",
        bank = "spawn_fx",
        build = "puff_spawning",
        anim = "small_high",
        sound = "dontstarve/common/spawn/spawnportal_spawnplayer",
    },
    {
        name = "splash_snow_fx",
        bank = "splash",
        build = "splash_snow",
        anim = "idle",
        sound = "dontstarve_DLC001/common/firesupressor_impact",
    },
    {
        name = "icespike_fx_1",
        bank = "deerclops_icespike",
        build = "deerclops_icespike",
        anim = "spike1",
        sound = "dontstarve/creatures/deerclops/ice_small",
    },
    {
        name = "icespike_fx_2",
        bank = "deerclops_icespike",
        build = "deerclops_icespike",
        anim = "spike2",
        sound = "dontstarve/creatures/deerclops/ice_small",
    },
    {
        name = "icespike_fx_3",
        bank = "deerclops_icespike",
        build = "deerclops_icespike",
        anim = "spike3",
        sound = "dontstarve/creatures/deerclops/ice_small",
    },
    {
        name = "icespike_fx_4",
        bank = "deerclops_icespike",
        build = "deerclops_icespike",
        anim = "spike4",
        sound = "dontstarve/creatures/deerclops/ice_small",
    },
    {
        name = "shock_fx",
        bank = "shock_fx",
        build = "shock_fx",
        anim = "shock",
        sound = "dontstarve_DLC001/common/shocked",
        autorotate = true,
        fn = FinalOffset1,
    },
    {
        name = "groundpound_fx",
        bank = "bearger_ground_fx",
        build = "bearger_ground_fx",
        sound = "dontstarve_DLC001/creatures/bearger/dustpoof",
        anim = "idle",
    },
    {
        name = "lavaarena_portal_player_fx",
        bank = "lavaarena_player_teleport",
        build = "lavaarena_player_teleport",
        anim = "idle", --NOTE: 6 blank frames at the start for audio syncing
        sound = "dontstarve/common/lava_arena/portal_player",
        bloom = true,
    },
    {
        name = "lavaarena_player_revive_from_corpse_fx",
        bank = "lavaarena_player_revive_fx",
        build = "lavaarena_player_revive_fx",
        anim = "player_revive",
        sound = "dontstarve/common/revive",
        bloom = true,
        fourfaced = true,
        autorotate = true,
        fn = FinalOffset1,
    },
    {
        name = "ember_short_fx",
        bank = "ember_particles",
        build = "lavaarena_ember_particles_fx",
        anim = "pre",
        bloom = true,
        animqueue = true,
        fn = function(inst) inst.AnimState:PushAnimation("loop", false) inst.AnimState:PushAnimation("pst", false) end,
    },
    {
        name = "lavaarena_creature_teleport_smoke_fx_1",
        bank = "lavaarena_creature_teleport_smoke_fx",
        build = "lavaarena_creature_teleport_smoke_fx",
        anim = "smoke_1",
    },
    {
        name = "lavaarena_creature_teleport_smoke_fx_2",
        bank = "lavaarena_creature_teleport_smoke_fx",
        build = "lavaarena_creature_teleport_smoke_fx",
        anim = "smoke_2",
    },
    {
        name = "lavaarena_creature_teleport_smoke_fx_3",
        bank = "lavaarena_creature_teleport_smoke_fx",
        build = "lavaarena_creature_teleport_smoke_fx",
        anim = "smoke_3",
    },
    {
        name = "shadowstrike_slash_fx",
        bank = "lavaarena_shadow_lunge_fx",
        build = "lavaarena_shadow_lunge_fx",
        anim = "line",
        transform = Vector3(1.25, 1.25, 1.25),
        eightfaced = true,
        fn = FinalOffset1,
    },
    {
        name = "shadowstrike_slash2_fx",
        bank = "lavaarena_shadow_lunge_fx",
        build = "lavaarena_shadow_lunge_fx",
        anim = "curve",
        transform = Vector3(1.25, 1.25, 1.25),
        eightfaced = true,
        fn = FinalOffset1,
    },
    {
        name = "firesplash_fx",
        bank = "dragonfly_ground_fx",
        build = "dragonfly_ground_fx",
        anim = "idle",
        bloom = true,
    },
    {
        name = "tauntfire_fx",
        bank = "dragonfly_fx",
        build = "dragonfly_fx",
        anim = "taunt",
        bloom = true,
    },
    {
        name = "attackfire_fx",
        bank = "dragonfly_fx",
        build = "dragonfly_fx",
        anim = "atk",
        bloom = true,
    },
    {
        name = "vomitfire_fx",
        bank = "dragonfly_fx",
        build = "dragonfly_fx",
        anim = "vomit",
        twofaced = true,
        bloom = true,
    },
    {
        name = "wathgrithr_spirit",
        bank = "wathgrithr_spirit",
        build = "wathgrithr_spirit",
        anim = "wathgrithr_spirit",
        sound = "dontstarve_DLC001/characters/wathgrithr/valhalla",
        sounddelay = .2,
    },
    {
        name = "lucy_ground_transform_fx",
        bank = "lucy_axe_fx",
        build = "axe_transform_fx",
        anim = "transform_ground",
    },
    {
        name = "lucy_transform_fx",
        bank = "lucy_axe_fx",
        build = "axe_transform_fx",
        anim = "transform_chop",
    },
    {
        name = "werebeaver_transform_fx",
        bank = "werebeaver_fx",
        build = "werebeaver_fx",
        anim = "transform_back",
    },
    {
        name = "attune_out_fx",
        bank = "attune_fx",
        build = "attune_fx",
        anim = "attune_out",
        sound = "dontstarve/ghost/ghost_haunt",
    },
    {
        name = "attune_in_fx",
        bank = "attune_fx",
        build = "attune_fx",
        anim = "attune_in",
        sound = "dontstarve/ghost/ghost_haunt",
    },
    {
        name = "attune_ghost_in_fx",
        bank = "attune_fx",
        build = "attune_fx",
        anim = "attune_ghost_in",
        sound = "dontstarve/ghost/ghost_haunt",
    },
    {
        name = "beefalo_transform_fx",
        bank = "beefalo_fx",
        build = "beefalo_fx",
        anim = "transform",
        --#TODO: this one
        sound = "dontstarve/ghost/ghost_haunt",
    },
    {
        name = "disease_puff",
        bank = "flies",
        build = "flies",
        anim = "flies_puff",
        sound = "dontstarve/common/flies_appear",
    },
    --[[{
        name = "disease_fx_small",
        bank = "disease_fx",
        build = "disease_fx",
        anim = "disease_small",
        sound = "dontstarve/common/together/diseased/small",
    },
    {
        name = "disease_fx",
        bank = "disease_fx",
        build = "disease_fx",
        anim = "disease",
        sound = "dontstarve/common/together/diseased/small",
    },
    {
        name = "disease_fx_tall",
        bank = "disease_fx",
        build = "disease_fx",
        anim = "disease_tall",
        sound = "dontstarve/common/together/diseased/big",
    },]]
    {
        name = "bee_poof_big",
        bank = "bee_poof",
        build = "bee_poof",
        anim = "anim",
        sound = "dontstarve/common/deathpoof",
        transform = Vector3(1.4, 1.4, 1.4),
        fn = function(inst)
            inst.AnimState:SetFinalOffset(1)
            inst.SoundEmitter:PlaySound("dontstarve/creatures/together/bee_queen/beeguard/puff", nil, .6)
        end,
    },
    {
        name = "bee_poof_small",
        bank = "bee_poof",
        build = "bee_poof",
        anim = "anim",
        sound = "dontstarve/common/deathpoof",
        transform = Vector3(1.4, 1.4, 1.4),
        fn = FinalOffset1,
    },
    {
        name = "honey_splash",
        bank = "honey_splash",
        build = "honey_splash",
        anim = "anim",
        nofaced = true,
        transform = Vector3(1.4, 1.4, 1.4),
        fn = FinalOffset1,
    },
    {
        name = "bundle_unwrap",
        bank = "bundle",
        build = "bundle",
        anim = "unwrap",
    },
    {
        name = "gift_unwrap",
        bank = "gift",
        build = "gift",
        anim = "unwrap",
    },
    {
        name = "redpouch_unwrap",
        bank = "redpouch",
        build = "redpouch",
        anim = "unwrap",
    },
    {
        name = "redpouch_yotp_unwrap",
        bank = "redpouch",
        build = "redpouch",
        anim = "unwrap",
    },
    {
        name = "wetpouch_unwrap",
        bank = "wetpouch",
        build = "wetpouch",
        anim = "unwrap",
    },
    {
        name = "quagmire_seedpacket_unwrap",
        bank = "quagmire_seedpacket",
        build = "quagmire_seedpacket",
        anim = "unwrap",
    },
    {
        name = "quagmire_crate_unwrap",
        bank = "quagmire_crate",
        build = "quagmire_crate", 
        anim = "unwrap",
    },
    {
        name = "sinkhole_spawn_fx_1",
        bank = "sinkhole_spawn_fx",
        build = "sinkhole_spawn_fx",
        anim = "idle1",
    },
    {
        name = "sinkhole_spawn_fx_2",
        bank = "sinkhole_spawn_fx",
        build = "sinkhole_spawn_fx",
        anim = "idle2",
    },
    {
        name = "sinkhole_spawn_fx_3",
        bank = "sinkhole_spawn_fx",
        build = "sinkhole_spawn_fx",
        anim = "idle3",
    },
    {
        name = "sinkhole_warn_fx_1",
        bank = "sinkhole_spawn_fx",
        build = "sinkhole_spawn_fx",
        anim = "idle1",
        transform = Vector3(0.75, 0.75, 0.75),
        fn = function(inst) inst.entity:AddSoundEmitter():PlaySoundWithParams("dontstarve/creatures/together/antlion/sfx/ground_break", { size = 0.01 }) end,
    },
    {
        name = "sinkhole_warn_fx_2",
        bank = "sinkhole_spawn_fx",
        build = "sinkhole_spawn_fx",
        anim = "idle2",
        transform = Vector3(0.75, 0.75, 0.75),
        fn = function(inst) inst.entity:AddSoundEmitter():PlaySoundWithParams("dontstarve/creatures/together/antlion/sfx/ground_break", { size = 0.01 }) end,
    },
    {
        name = "sinkhole_warn_fx_3",
        bank = "sinkhole_spawn_fx",
        build = "sinkhole_spawn_fx",
        anim = "idle3",
        transform = Vector3(0.75, 0.75, 0.75),
        fn = function(inst) inst.entity:AddSoundEmitter():PlaySoundWithParams("dontstarve/creatures/together/antlion/sfx/ground_break", { size = 0.01 }) end,
    },
    {
        name = "cavein_debris",
        bank = "cavein_debris_fx",
        build = "cavein_debris_fx",
        anim = "anim",
        fn = function(inst) inst.entity:AddSoundEmitter():PlaySoundWithParams("dontstarve/creatures/together/antlion/sfx/ground_break", { size = 0 }) end,
    },
    {
        name = "glass_fx",
        bank = "mining_fx",
        build = "mining_ice_fx",
        anim = "anim",
        sound = "dontstarve/creatures/together/antlion/sfx/sand_to_glass",
    },
    {
        name = "erode_ash",
        bank = "erode_ash",
        build = "erode_ash",
        anim = "idle",
        sound = "dontstarve/common/dust_blowaway",
    },
    {
        name = "sleepbomb_burst",
        bank = "sleepbomb",
        build = "sleepbomb",
        anim = "used",
        sound = "dontstarve/common/together/infection_burst",
    },
    {
        name = "quagmire_portal_player_fx",
        bank = "quagmire_portalspawn_fx",
        build = "quagmire_portalspawn_fx",
        anim = "idle",
        sound = "dontstarve/quagmire/common/portal/spawn",
        fn = FinalOffset1,
    },
    {
        name = "quagmire_portal_playerdrip_fx",
        bank = "quagmire_portaldrip_fx",
        build = "quagmire_portaldrip_fx",
        anim = "idle",
    },
    {
        name = "quagmire_portal_player_splash_fx",
        bank = "quagmire_portalspawn_fx",
        build = "quagmire_portalspawn_fx",
        anim = "exit",
        sound = "dontstarve/creatures/pengull/splash",
        fn = FinalOffset1,
    },
    {
        name = "quagmire_salting_plate_fx",
        bank = "quagmire_salting_fx",
        build = "quagmire_salting_fx",
        anim = "plate",
        sound = "dontstarve/quagmire/common/cooking/salt_shake",
        fn = FinalOffset1,
    },
    {
        name = "quagmire_salting_bowl_fx",
        bank = "quagmire_salting_fx",
        build = "quagmire_salting_fx",
        anim = "bowl",
        sound = "dontstarve/quagmire/common/cooking/salt_shake",
        fn = FinalOffset1,
    },
    {
        name = "halloween_firepuff_1",
        bank = "halloween_embers",
        build = "halloween_embers",
        anim = "puff_1",
        bloom = true,
        sound = "dontstarve/common/fireAddFuel",
        fn = FinalOffset3,
    },
    {
        name = "halloween_firepuff_2",
        bank = "halloween_embers",
        build = "halloween_embers",
        anim = "puff_2",
        bloom = true,
        sound = "dontstarve/common/fireAddFuel",
        fn = FinalOffset3,
    },
    {
        name = "halloween_firepuff_3",
        bank = "halloween_embers",
        build = "halloween_embers",
        anim = "puff_3",
        bloom = true,
        sound = "dontstarve/common/fireAddFuel",
        fn = FinalOffset3,
    },
    {
        name = "halloween_firepuff_cold_1",
        bank = "halloween_embers_cold",
        build = "halloween_embers_cold",
        anim = "puff_1",
        bloom = true,
        sound = "dontstarve/common/fireAddFuel",
        fn = FinalOffset3,
    },
    {
        name = "halloween_firepuff_cold_2",
        bank = "halloween_embers_cold",
        build = "halloween_embers_cold",
        anim = "puff_2",
        bloom = true,
        sound = "dontstarve/common/fireAddFuel",
        fn = FinalOffset3,
    },
    {
        name = "halloween_firepuff_cold_3",
        bank = "halloween_embers_cold",
        build = "halloween_embers_cold",
        anim = "puff_3",
        bloom = true,
        sound = "dontstarve/common/fireAddFuel",
        fn = FinalOffset3,
    },
    {
        name = "mudpuddle_splash",
        bank = "mudsplash",
        build = "mudsplash",
        anim = "anim",
        sound = "dontstarve/creatures/pengull/splash",
        fn = FinalOffset3,
    },
    {
        name = "slide_puff",
        bank = "fx_slidepuff",
        build = "slide_puff",
        anim = "anim",
        fn = FinalOffset1,
    },
}

for j = 0, 3, 3 do
    for i = 1, 3 do
        table.insert(fx, {
            name = "shadow_shield"..tostring(j + i),
            bank = "stalker_shield",
            build = "stalker_shield",
            anim = "idle"..tostring(i),
            sound = "dontstarve/creatures/together/stalker/shield",
            transform = j > 0 and Vector3(-1, 1, 1) or nil,
            fn = FinalOffset2,
        })
    end
end

FinalOffset1 = nil
FinalOffset2 = nil

return fx
