-- AUTOGENERATED CODE BY export_accountitems.lua

ITEM_DISPLAY_BLACKLIST =
{
	armor_dragonfly_fangedcollar = true,
	armor_dragonfly_haramaki = true,
	armor_dragonfly_lamellar = true,
	dragonling_bat_builder = true,
	dragonling_winter_builder = true,
	dragonling_wyvern_builder = true,
	firestaff_bee = true,
	firestaff_rose = true,
	glomling_beardeddragon_builder = true,
	glomling_winter_builder = true,
	icestaff_bee = true,
	icestaff_rose = true,
	kitten_winter_builder = true,
	lamb_winter_builder = true,
	minerhat_floppy = true,
	orangestaff_ancient = true,
	perdling_rooster_builder = true,
	perdling_winter_builder = true,
	puppy_winter_builder = true,
	rainhat_floppy = true,
	researchlab4_catcoon_costume = true,
	researchlab4_chester_costume = true,
	researchlab4_derby = true,
	researchlab4_festive_bell_red_firehound = true,
	researchlab4_glommer_costume = true,
	researchlab4_hutch_costume = true,
	backpack_mushy = true,
	researchlab2_pod_alt = true,
}

