-- AUTOGENERATED CODE BY export_accountitems.lua

MISC_ITEMS =
{
	emoji_arcane =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_battle =
	{
		type = "emoji",
		skin_tags = { "VARG", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	emoji_beefalo =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_chest =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_chester =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_crockpot =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_eyeball =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_faketeeth =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_farm =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_fire =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_flex =
	{
		type = "emoji",
		skin_tags = { "VARG", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	emoji_ghost =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_gold =
	{
		type = "emoji",
		skin_tags = { "VARG", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	emoji_grave =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_hambat =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_hammer =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_heart =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_hunger =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_lightbulb =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_pig =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_poop =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_redgem =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_sanity =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_sciencemachine =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_skull =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_tophat =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	emoji_torch =
	{
		type = "emoji",
		skin_tags = { "VARG", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	emoji_web =
	{
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	loading_bearger_yule =
	{
		type = "loading",
		skin_tags = { "ICE", "LOADING", },
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	loading_critters =
	{
		type = "loading",
		skin_tags = { "VARG", "LOADING", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	loading_deerclops_yule =
	{
		type = "loading",
		skin_tags = { "ICE", "LOADING", },
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	loading_dragonfly_yule =
	{
		type = "loading",
		skin_tags = { "ICE", "LOADING", },
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	loading_goosemoose_yule =
	{
		type = "loading",
		skin_tags = { "ICE", "LOADING", },
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	loading_maxwell =
	{
		type = "loading",
		skin_tags = { "LAVA", "LOADING", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	loading_merm =
	{
		type = "loading",
		skin_tags = { "LAVA", "LOADING", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	loading_pigking =
	{
		type = "loading",
		skin_tags = { "LAVA", "LOADING", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	loading_webber =
	{
		type = "loading",
		skin_tags = { "LAVA", "LOADING", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	loading_wendy =
	{
		type = "loading",
		skin_tags = { "LAVA", "LOADING", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	loading_wickerbottom =
	{
		type = "loading",
		skin_tags = { "LAVA", "LOADING", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	loading_wigfrid =
	{
		type = "loading",
		skin_tags = { "LAVA", "LOADING", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	loading_willowfire =
	{
		type = "loading",
		skin_tags = { "LAVA", "LOADING", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	loading_wolfgang =
	{
		type = "loading",
		skin_tags = { "LAVA", "LOADING", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	mysterybox_classic_4 =
	{
		type = "mysterybox",
		skin_tags = { "MYSTERYBOX", },
		box_build = "box_mystery_classic",
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 38,
	},
	mysterybox_ice_4 =
	{
		type = "mysterybox",
		skin_tags = { "MYSTERYBOX", },
		box_build = "box_mystery_ice",
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 38,
	},
	mysterybox_lava_4 =
	{
		type = "mysterybox",
		skin_tags = { "MYSTERYBOX", },
		box_build = "box_shared",
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 33,
	},
	mysterybox_nature_4 =
	{
		type = "mysterybox",
		skin_tags = { "MYSTERYBOX", },
		box_build = "box_mystery_nature",
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 41,
	},
	pack_gladiator_all =
	{
		type = "purchase",
		skin_tags = { },
		featured_pack = true,
		display_order = 1,
		display_atlas = "images/iap_images_gladiator.xml",
		display_tex = "gladiator.tex",
		box_build = "box_shop_forge_all",
		release_group = 34,
	},
	pack_gladiator_wathgrithr =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 11,
		display_atlas = "bigportraits/wathgrithr_gladiator.xml",
		display_tex = "wathgrithr_gladiator_oval.tex",
		box_build = "box_shop_forge",
		release_group = 34,
	},
	pack_gladiator_waxwell =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 10,
		display_atlas = "bigportraits/waxwell_gladiator.xml",
		display_tex = "waxwell_gladiator_oval.tex",
		box_build = "box_shop_forge",
		release_group = 34,
	},
	pack_gladiator_webber =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 12,
		display_atlas = "bigportraits/webber_gladiator.xml",
		display_tex = "webber_gladiator_oval.tex",
		box_build = "box_shop_forge",
		release_group = 34,
	},
	pack_gladiator_wendy =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 5,
		display_atlas = "bigportraits/wendy_gladiator.xml",
		display_tex = "wendy_gladiator_oval.tex",
		box_build = "box_shop_forge",
		release_group = 34,
	},
	pack_gladiator_wes =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 9,
		display_atlas = "bigportraits/wes_gladiator.xml",
		display_tex = "wes_gladiator_oval.tex",
		box_build = "box_shop_forge",
		release_group = 34,
	},
	pack_gladiator_wickerbottom =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 7,
		display_atlas = "bigportraits/wickerbottom_gladiator.xml",
		display_tex = "wickerbottom_gladiator_oval.tex",
		box_build = "box_shop_forge",
		release_group = 34,
	},
	pack_gladiator_willow =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 3,
		display_atlas = "bigportraits/willow_gladiator.xml",
		display_tex = "willow_gladiator_oval.tex",
		box_build = "box_shop_forge",
		release_group = 34,
	},
	pack_gladiator_wilson =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 2,
		display_atlas = "bigportraits/wilson_gladiator.xml",
		display_tex = "wilson_gladiator_oval.tex",
		box_build = "box_shop_forge",
		release_group = 34,
	},
	pack_gladiator_winona =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 13,
		display_atlas = "bigportraits/winona_gladiator.xml",
		display_tex = "winona_gladiator_oval.tex",
		box_build = "box_shop_forge",
		release_group = 34,
	},
	pack_gladiator_wolfgang =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 4,
		display_atlas = "bigportraits/wolfgang_gladiator.xml",
		display_tex = "wolfgang_gladiator_oval.tex",
		box_build = "box_shop_forge",
		release_group = 34,
	},
	pack_gladiator_woodie =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 8,
		display_atlas = "bigportraits/woodie_gladiator.xml",
		display_tex = "woodie_gladiator_oval.tex",
		box_build = "box_shop_forge",
		release_group = 34,
	},
	pack_gladiator_wx78 =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 6,
		display_atlas = "bigportraits/wx78_gladiator.xml",
		display_tex = "wx78_gladiator_oval.tex",
		box_build = "box_shop_forge",
		release_group = 34,
	},
	pack_heart_you =
	{
		type = "purchase",
		skin_tags = { },
		featured_pack = true,
		steam_dlc_id = 798740,
		display_order = 1,
		display_atlas = "images/iap_images_heart.xml",
		display_tex = "heart.tex",
		box_build = "box_shop_heart",
		release_group = 41,
	},
	pack_ice_all =
	{
		type = "purchase",
		skin_tags = { },
		featured_pack = true,
		display_order = 1,
		display_atlas = "images/iap_images_ice.xml",
		display_tex = "ice.tex",
		box_build = "box_shop_ice",
		release_group = 37,
	},
	pack_ice_webber =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 6,
		display_atlas = "bigportraits/webber_ice.xml",
		display_tex = "webber_ice_oval.tex",
		box_build = "box_shop_ice",
		release_group = 37,
	},
	pack_ice_wendy =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 5,
		display_atlas = "bigportraits/wendy_ice.xml",
		display_tex = "wendy_ice_oval.tex",
		box_build = "box_shop_ice",
		release_group = 37,
	},
	pack_ice_wickerbottom =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 6,
		display_atlas = "bigportraits/wickerbottom_ice.xml",
		display_tex = "wickerbottom_ice_oval.tex",
		box_build = "box_shop_ice",
		release_group = 37,
	},
	pack_ice_willow =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 3,
		display_atlas = "bigportraits/willow_ice.xml",
		display_tex = "willow_ice_oval.tex",
		box_build = "box_shop_ice",
		release_group = 37,
	},
	pack_ice_wilson =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 2,
		display_atlas = "bigportraits/wilson_ice.xml",
		display_tex = "wilson_ice_oval.tex",
		box_build = "box_shop_ice",
		release_group = 37,
	},
	pack_ice_wolfgang =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 4,
		display_atlas = "bigportraits/wolfgang_ice.xml",
		display_tex = "wolfgang_ice_oval.tex",
		box_build = "box_shop_ice",
		release_group = 37,
	},
	pack_nature_all =
	{
		type = "purchase",
		skin_tags = { },
		featured_pack = true,
		steam_dlc_id = 798750,
		display_order = 2,
		display_atlas = "images/iap_images_nature.xml",
		display_tex = "nature.tex",
		box_build = "box_shop_nature",
		release_group = 41,
	},
	pack_nature_wathgrithr =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 7,
		display_atlas = "bigportraits/wathgrithr_nature.xml",
		display_tex = "wathgrithr_nature_oval.tex",
		box_build = "box_shop_nature",
		release_group = 41,
	},
	pack_nature_waxwell =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 6,
		display_atlas = "bigportraits/waxwell_nature.xml",
		display_tex = "waxwell_nature_oval.tex",
		box_build = "box_shop_nature",
		release_group = 41,
	},
	pack_nature_wes =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 5,
		display_atlas = "bigportraits/wes_nature.xml",
		display_tex = "wes_nature_oval.tex",
		box_build = "box_shop_nature",
		release_group = 41,
	},
	pack_nature_winona =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 8,
		display_atlas = "bigportraits/winona_nature.xml",
		display_tex = "winona_nature_oval.tex",
		box_build = "box_shop_nature",
		release_group = 41,
	},
	pack_nature_woodie =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 4,
		display_atlas = "bigportraits/woodie_nature.xml",
		display_tex = "woodie_nature_oval.tex",
		box_build = "box_shop_nature",
		release_group = 41,
	},
	pack_nature_wx78 =
	{
		type = "purchase",
		skin_tags = { },
		display_order = 3,
		display_atlas = "bigportraits/wx78_nature.xml",
		display_tex = "wx78_nature_oval.tex",
		box_build = "box_shop_nature",
		release_group = 41,
	},
	playerportrait_bg_beefalo =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_birchnut =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_camp =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_cardinals =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_deciduousforest =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_flames =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Loyal",
		release_group = 32,
	},
	playerportrait_bg_forestfire =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_garden =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_grasslands =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_heart1 =
	{
		type = "playerportrait",
		skin_tags = { "HEART", "PLAYERPORTRAIT", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 39,
	},
	playerportrait_bg_heart2 =
	{
		type = "playerportrait",
		skin_tags = { "HEART", "PLAYERPORTRAIT", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 39,
	},
	playerportrait_bg_lava =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_lavaarena =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_lonecarrot =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_lumpyevergreen =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_marshhouse =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_penguins =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_pighouse =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_rocks =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_roseportal =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_shoreline =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_spidermarsh =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_spikymarsh =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_suspisciousdirtpile =
	{
		type = "playerportrait",
		skin_tags = { "VARG", "PLAYERPORTRAIT", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	playerportrait_bg_thickforest =
	{
		type = "playerportrait",
		skin_tags = { "LAVA", "PLAYERPORTRAIT", },
		rarity = "Classy",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	playerportrait_bg_toothtraps =
	{
		type = "playerportrait",
		skin_tags = { "VARG", "PLAYERPORTRAIT", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	playerportrait_bg_winter =
	{
		type = "playerportrait",
		skin_tags = { "ICE", "PLAYERPORTRAIT", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	playerportrait_bg_winterfire =
	{
		type = "playerportrait",
		skin_tags = { "ICE", "PLAYERPORTRAIT", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	playerportrait_bg_wintertrees =
	{
		type = "playerportrait",
		skin_tags = { "ICE", "PLAYERPORTRAIT", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	playerportrait_bg_yule1 =
	{
		type = "playerportrait",
		skin_tags = { "ICE", "PLAYERPORTRAIT", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	playerportrait_bg_yule2 =
	{
		type = "playerportrait",
		skin_tags = { "ICE", "PLAYERPORTRAIT", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	playerportrait_bg_yule3 =
	{
		type = "playerportrait",
		skin_tags = { "ICE", "PLAYERPORTRAIT", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_abigail_flower =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_babybeefalo =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_bat_furled =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_bearger_roar =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_beefalo =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_bernie =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_bishop =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_catcoon =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_chester =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_clayhound =
	{
		type = "profileflair",
		skin_tags = { "VARG", "PROFILEFLAIR", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	profileflair_claywarg =
	{
		type = "profileflair",
		skin_tags = { "VARG", "PROFILEFLAIR", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	profileflair_crow =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_cupcake =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_deerclops =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_dragonfly_sleeping =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_dragonfruit =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_frog =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_goosemoose =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_hound =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_icehound =
	{
		type = "profileflair",
		skin_tags = { "VARG", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	profileflair_knight =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_koalefant =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_krampus =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_mactusk =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_mandrake =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_merm =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_mole =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_nightlight =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_ornaments_1 =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_ornaments_10 =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_ornaments_11 =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_ornaments_12 =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_ornaments_13 =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_ornaments_2 =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_ornaments_3 =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_ornaments_4 =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_ornaments_5 =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_ornaments_6 =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_ornaments_7 =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_ornaments_8 =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_ornaments_9 =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Classy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_pengull =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_phonograph =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_pig_happy =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_pigking =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_pumpkinlantern =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_puppington =
	{
		type = "profileflair",
		skin_tags = { "VARG", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	profileflair_rabbit =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_redhound =
	{
		type = "profileflair",
		skin_tags = { "VARG", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	profileflair_rook =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_rose =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_shadowhand =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_shadowmanipulator =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_smallbird =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_spider =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_tallbird_eye =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_treeguard =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_trinket_faketeeth =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_trinket_gnome =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_trinket_gnomette =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_varg =
	{
		type = "profileflair",
		skin_tags = { "VARG", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "Seasonal",
		release_group = 40,
	},
	profileflair_waffle =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_werepig_howl =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_wererabbit =
	{
		type = "profileflair",
		skin_tags = { "LAVA", "PROFILEFLAIR", },
		rarity = "Common",
		rarity_modifier = "EventModifier",
		release_group = 32,
	},
	profileflair_yule_bearger =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_yule_claus =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_yule_deer =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Spiffy",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_yule_deerclops =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_yule_dragonfly =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_yule_dragonflyfire =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
	profileflair_yule_goosemoose =
	{
		type = "profileflair",
		skin_tags = { "ICE", "PROFILEFLAIR", },
		rarity = "Distinguished",
		rarity_modifier = "Seasonal",
		release_group = 36,
	},
}

