-- AUTOGENERATED CODE BY export_accountitems.lua

PREFAB_SKINS = {
	abigail =
	{
		"abigail_formal",
		"abigail_handmedown",
		"abigail_nature",
		"abigail_rose",
		"abigail_shadow",
		"abigail_survivor",
	},
	abigail_flower =
	{
		"abigail_flower_formal",
		"abigail_flower_handmedown",
		"abigail_flower_nature",
		"abigail_flower_rose",
		"abigail_flower_shadow",
		"abigail_flower_survivor",
	},
	alterguardianhat =
	{
		"alterguardianhat_lastprism",
	},
	amulet =
	{
		"amulet_red_heart",
		"amulet_red_occulteye",
	},
	armor_sanity =
	{
		"armor_sanity_curve",
		"armor_sanity_sharp",
	},
	armordragonfly =
	{
		"armor_dragonfly_fangedcollar",
		"armor_dragonfly_haramaki",
		"armor_dragonfly_lamellar",
		"armor_dragonfly_roman",
	},
	armorgrass =
	{
		"armor_grass_cloak",
		"armor_grass_woven",
	},
	armormarble =
	{
		"armor_marble_chainmail",
		"armor_marble_rockabs",
		"armor_marble_valkyrie",
	},
	armorruins =
	{
		"armor_ruins_arcane",
		"armor_ruins_bulky",
		"armor_ruins_leaf",
		"armor_ruins_tusk",
	},
	armorskeleton =
	{
		"armor_skeleton_shadowscalemail",
	},
	armorwood =
	{
		"armor_wood_fangedcollar",
		"armor_wood_haramaki",
		"armor_wood_lamellar",
		"armor_wood_roman",
	},
	arrowsign_post =
	{
		"arrowsign_post_circus",
		"arrowsign_post_factory",
		"arrowsign_post_fantasy",
	},
	axe =
	{
		"axe_feathered",
		"axe_invisible",
		"axe_northern",
		"axe_victorian",
	},
	backpack =
	{
		"backpack_babybeef",
		"backpack_basic_blue_catcoon",
		"backpack_basic_green_olive",
		"backpack_bat",
		"backpack_beefalo",
		"backpack_buckle_grey_pewter",
		"backpack_buckle_navy_phthalo",
		"backpack_buckle_red_rook",
		"backpack_camping_green_viridian",
		"backpack_camping_orange_carrot",
		"backpack_camping_red_koalefant",
		"backpack_carrat",
		"backpack_catcoon",
		"backpack_chester",
		"backpack_crab",
		"backpack_deerclops",
		"backpack_dragonfly_fire",
		"backpack_glommer",
		"backpack_hound",
		"backpack_koalefant",
		"backpack_mandrake",
		"backpack_mushy",
		"backpack_poop",
		"backpack_rabbit",
		"backpack_smallbird",
		"backpack_spider",
		"backpack_splumonkey",
	},
	batbat =
	{
		"batbat_fantasy",
		"batbat_scythe",
	},
	bedroll_furry =
	{
		"bedroll_furry_potato",
		"bedroll_furry_quilt_blue_frost",
		"bedroll_furry_quilt_green_hunters",
		"bedroll_furry_quilt_orange_honey",
		"bedroll_furry_quilt_red_redbird",
		"bedroll_furry_quilt_white_ivory",
	},
	beebox =
	{
		"beebox_crystal",
		"beebox_house",
		"beebox_victorian",
	},
	beefalohat =
	{
		"beefalohat_fantasy",
		"beefalohat_klaus",
		"beefalohat_pigking",
		"beefalohat_pigking_alt",
	},
	beehat =
	{
		"beehat_mourning",
		"beehat_sunhat",
	},
	beemine =
	{
		"beemine_heart",
		"beemine_jamjar",
	},
	bernie_active =
	{
		"bernie_cat_active",
	},
	bernie_big =
	{
		"bernie_cat_big",
	},
	bernie_inactive =
	{
		"bernie_cat",
	},
	birdcage =
	{
		"birdcage_circus",
		"birdcage_curly",
		"birdcage_gothic",
		"birdcage_gothicp",
		"birdcage_ornamental",
		"birdcage_pirate",
		"birdcage_romantic",
	},
	book_brimstone =
	{
		"book_brimstone_gilded",
	},
	boomerang =
	{
		"boomerang_bananarang",
		"boomerang_tiger",
	},
	bugnet =
	{
		"bugnet_frog",
		"bugnet_lavaproof",
		"bugnet_spider",
		"bugnet_spider_white",
	},
	bundle =
	{
		"bundle_gothic",
		"bundle_vintage",
	},
	bundlewrap =
	{
		"bundlewrap_gothic",
		"bundlewrap_vintage",
	},
	campfire =
	{
		"campfire_cabin",
	},
	cane =
	{
		"cane_ancient",
		"cane_candycane",
		"cane_harlequin",
		"cane_sharp",
		"cane_victorian",
	},
	catcoonhat =
	{
		"catcoonhat_trapper_rooster",
		"catcoonhat_trapperup_rooster",
		"hat_puppy_cap",
	},
	cavein_boulder =
	{
		"cavein_boulder_kettlebell",
	},
	chester =
	{
		"chester_lamb",
		"chester_walrus",
	},
	chester_eyebone =
	{
		"chester_eyebone_lamb",
		"chester_eyebone_walrus",
	},
	coldfirepit =
	{
		"coldfirepit_flower",
		"coldfirepit_gothic",
		"coldfirepit_teeth",
	},
	cookpot =
	{
		"cookpot_cauldron",
		"cookpot_cauldronp",
		"cookpot_clay",
		"cookpot_survival",
		"cookpot_tureen",
	},
	critter_dragonling =
	{
		"dragonling_bat",
		"dragonling_batp",
		"dragonling_winter",
		"dragonling_wyvern",
	},
	critter_dragonling_builder =
	{
		"dragonling_bat_builder",
		"dragonling_batp_builder",
		"dragonling_winter_builder",
		"dragonling_wyvern_builder",
	},
	critter_glomling =
	{
		"glomling_beardeddragon",
		"glomling_puft",
		"glomling_winter",
	},
	critter_glomling_builder =
	{
		"glomling_beardeddragon_builder",
		"glomling_puft_builder",
		"glomling_winter_builder",
	},
	critter_kitten =
	{
		"kitten_black",
		"kitten_winter",
	},
	critter_kitten_builder =
	{
		"kitten_black_builder",
		"kitten_winter_builder",
	},
	critter_lamb =
	{
		"lamb_winter",
	},
	critter_lamb_builder =
	{
		"lamb_winter_builder",
	},
	critter_perdling =
	{
		"perdling_pelican",
		"perdling_puffin",
		"perdling_rooster",
		"perdling_winter",
	},
	critter_perdling_builder =
	{
		"perdling_pelican_builder",
		"perdling_puffin_builder",
		"perdling_rooster_builder",
		"perdling_winter_builder",
	},
	critter_puppy =
	{
		"puppy_chow",
		"puppy_tzu",
		"puppy_winter",
	},
	critter_puppy_builder =
	{
		"puppy_chow_builder",
		"puppy_tzu_builder",
		"puppy_winter_builder",
	},
	dragonflychest =
	{
		"dragonflychest_fantasy",
		"dragonflychest_kraken",
	},
	dragonflyfurnace =
	{
		"dragonflyfurnace_antique",
		"dragonflyfurnace_crystal",
	},
	earmuffshat =
	{
		"earmuffshat_beeguard",
		"earmuffshat_deerclops",
	},
	endtable =
	{
		"endtable_carpet",
		"endtable_cawnival",
		"endtable_cawnival_alt",
		"endtable_dragonfly",
		"endtable_vintage",
	},
	eyebrellahat =
	{
		"eyebrellahat_crystal",
		"eyebrellahat_fantasy",
		"eyebrellahat_victorian",
	},
	farm_hoe =
	{
		"farm_hoe_invisible",
		"farm_hoe_rustic",
	},
	featherfan =
	{
		"featherfan_exotic",
	},
	featherhat =
	{
		"featherhat_circus",
		"featherhat_exotic",
		"featherhat_victorian",
	},
	fence =
	{
		"fence_factory",
		"fence_fantasy",
		"fence_gingerbread",
		"fence_gothic",
		"fence_picketbrown",
		"fence_pickettan",
		"fence_picketwhite",
		"fence_victorianblack",
		"fence_victorianbrass",
		"fence_victorianbronze",
	},
	fence_gate =
	{
		"fence_gate_gingerbread",
		"fence_gate_gothic",
		"fence_gate_picketbrown",
		"fence_gate_pickettan",
		"fence_gate_picketwhite",
		"fence_gate_victorianblack",
		"fence_gate_victorianbrass",
		"fence_gate_victorianbronze",
	},
	fence_gate_item =
	{
		"fencegate_gingerbread_item",
		"fencegate_gothic_item",
		"fencegate_picketbrown_item",
		"fencegate_pickettan_item",
		"fencegate_picketwhite_item",
		"fencegate_victorianblack_item",
		"fencegate_victorianbrass_item",
		"fencegate_victorianbronze_item",
	},
	fence_item =
	{
		"fence_factory_item",
		"fence_fantasy_item",
		"fence_gingerbread_item",
		"fence_gothic_item",
		"fence_picketbrown_item",
		"fence_pickettan_item",
		"fence_picketwhite_item",
		"fence_victorianblack_item",
		"fence_victorianbrass_item",
		"fence_victorianbronze_item",
	},
	firepit =
	{
		"firepit_fanged",
		"firepit_firebird",
		"firepit_hole",
		"firepit_hole_alt",
		"firepit_kiln",
		"firepit_kiln_alt",
		"firepit_lava",
		"firepit_stonehenge",
		"firepit_victorian",
	},
	firestaff =
	{
		"firestaff_bee",
		"firestaff_flamelash",
		"firestaff_gungnir",
		"firestaff_hockey",
		"firestaff_lance",
		"firestaff_meteor",
		"firestaff_northern",
		"firestaff_rose",
	},
	firesuppressor =
	{
		"firesuppressor_circus",
		"firesuppressor_robot",
	},
	fish_box =
	{
		"fishbox_nautical",
	},
	flowerhat =
	{
		"flowerhat_crown",
		"flowerhat_healing",
		"flowerhat_holly_wreath",
		"flowerhat_ribbon_wreath",
		"flowerhat_wreath",
	},
	footballhat =
	{
		"footballhat_combathelm",
		"footballhat_combathelm2",
		"footballhat_hockey",
		"hat_dog_helm",
	},
	gemsocket =
	{
		"gemsocket_crystal",
		"gemsocket_hallowpylon",
	},
	glasscutter =
	{
		"glasscutter_terraprisma",
	},
	glommer =
	{
		"glommer_fantasy",
	},
	glommerflower =
	{
		"glommerflower_fantasy",
	},
	golden_farm_hoe =
	{
		"golden_farmhoe_invisible",
	},
	goldenaxe =
	{
		"goldenaxe_invisible",
		"goldenaxe_northern",
	},
	goldenpickaxe =
	{
		"goldenpickaxe_invisible",
		"goldenpickaxe_northern",
	},
	goldenshovel =
	{
		"goldenshovel_invisible",
		"goldenshovel_northern",
	},
	grass_umbrella =
	{
		"parasol_spring",
	},
	greenstaff =
	{
		"greenstaff_clockwork",
	},
	hambat =
	{
		"hambat_nautical",
		"hambat_potroast",
		"hambat_spiralcut",
	},
	hammer =
	{
		"hammer_crowbar",
		"hammer_forge",
		"hammer_hammush",
		"hammer_invisible",
	},
	heatrock =
	{
		"heatrock_fantasy",
		"heatrock_fire",
	},
	hutch =
	{
		"hutch_fantasy",
	},
	hutch_fishbowl =
	{
		"hutch_fishbowl_fantasy",
	},
	icebox =
	{
		"icebox_coffin",
		"icebox_crystal",
		"icebox_porcelain",
		"icebox_victorian",
	},
	icestaff =
	{
		"icestaff_bee",
		"icestaff_gungnir",
		"icestaff_hockey",
		"icestaff_icerod",
		"icestaff_lance",
		"icestaff_northern",
		"icestaff_rose",
	},
	krampus_sack =
	{
		"krampus_sack_basket",
		"krampus_sack_voidbag",
	},
	lantern =
	{
		"lantern_crystal",
		"lantern_flower",
		"lantern_flower_alt",
		"lantern_gothic",
		"lantern_mummy",
		"lantern_mummy_alt",
		"lantern_retro",
		"lantern_tesla",
		"lantern_winter",
		"lantern_winter_alt",
	},
	lighter =
	{
		"lighter_haunteddoll",
	},
	lightning_rod =
	{
		"lightning_rod_gothic",
		"lightning_rod_nautical",
		"lightning_rod_retro",
		"lightning_rod_robot",
	},
	lureplant =
	{
		"eyeplant_trap_plantera",
	},
	lureplantbulb =
	{
		"eyeplant_bulb_trap_plantera",
	},
	mast =
	{
		"mast_crabking",
		"mast_crabking_alt",
		"mast_nautical",
		"mast_rose",
		"mast_rose_alt",
	},
	mast_item =
	{
		"mast_crabking_alt_item",
		"mast_crabking_item",
		"mast_nautical_item",
		"mast_rose_alt_item",
		"mast_rose_item",
	},
	mastupgrade_lamp =
	{
		"mastupgradelamp_nautical",
	},
	mastupgrade_lamp_item =
	{
		"mastupgradelamp_item_nautical",
	},
	mastupgrade_lightningrod =
	{
		"mastupgrade_lightningrod_nautical",
	},
	mastupgrade_lightningrod_item =
	{
		"mastupgrade_lightningrod_item_nautical",
	},
	mastupgrade_lightningrod_top =
	{
		"mastupgrade_lightningrod_nautical_top",
	},
	meatrack =
	{
		"meatrack_butcher",
		"meatrack_circus",
		"meatrack_victorian",
	},
	mermhouse_crafted =
	{
		"mermhouse_crafted_fantasy",
	},
	minerhat =
	{
		"minerhat_bonnet",
		"minerhat_cowboy",
		"minerhat_floppy",
	},
	minisign =
	{
		"minisign_fantasy",
		"minisign_picketbrown",
		"minisign_pickettan",
		"minisign_picketwhite",
	},
	minisign_drawn =
	{
		"minisign_fantasy_drawn",
		"minisign_picketbrown_drawn",
		"minisign_pickettan_drawn",
		"minisign_picketwhite_drawn",
	},
	minisign_item =
	{
		"minisign_fantasy_item",
		"minisign_picketbrown_item",
		"minisign_pickettan_item",
		"minisign_picketwhite_item",
	},
	multitool_axe_pickaxe =
	{
		"multitool_axe_pickaxe_pickaxeaxe",
	},
	mushroom_light =
	{
		"mushroom_light_festive",
		"mushroom_light_tiffany",
	},
	mushroom_light2 =
	{
		"mushroom_light2_lily",
		"mushroom_light2_victorian",
	},
	nightsword =
	{
		"nightsword_curve",
		"nightsword_lightsbane",
		"nightsword_sharp",
	},
	oar =
	{
		"oar_invisible",
	},
	oar_driftwood =
	{
		"oar_driftwood_invisible",
	},
	oceanfishingrod =
	{
		"oceanfishingrod_hotline",
		"oceanfishingrod_ice",
		"oceanfishingrod_ice_alt",
	},
	opalstaff =
	{
		"moonstaff_crystal",
		"moonstaff_portal",
	},
	orangestaff =
	{
		"orangestaff_ancient",
		"orangestaff_candycane",
		"orangestaff_harlequin",
		"orangestaff_rodofdiscord",
		"orangestaff_sharp",
		"orangestaff_victorian",
	},
	panflute =
	{
		"panflute_harlequin",
	},
	pickaxe =
	{
		"pickaxe_feathered",
		"pickaxe_invisible",
		"pickaxe_northern",
		"pickaxe_reavershark",
		"pickaxe_scythe",
		"pickaxe_scythe_alt",
		"pickaxe_victorian",
	},
	piggyback =
	{
		"piggyback_elephant",
		"piggyback_nose",
	},
	pighouse =
	{
		"pighouse_cabin",
		"pighouse_gothic",
		"pighouse_logcabin",
	},
	pitchfork =
	{
		"pitchfork_invisible",
	},
	rabbithouse =
	{
		"rabbithouse_carrat",
		"rabbithouse_yule",
	},
	rainhat =
	{
		"rainhat_bonnet",
		"rainhat_cowboy",
		"rainhat_floppy",
	},
	rainometer =
	{
		"rainometer_circus",
	},
	razor =
	{
		"razor_scissors",
		"razor_straight",
	},
	researchlab =
	{
		"researchlab_gothic",
		"researchlab_green",
		"researchlab_retro",
	},
	researchlab2 =
	{
		"researchlab2_alchemytable",
		"researchlab2_crystal",
		"researchlab2_gothic",
		"researchlab2_pod",
	},
	researchlab3 =
	{
		"researchlab3_ancient",
		"researchlab3_crystal",
		"researchlab3_monster",
		"researchlab3_nature",
	},
	researchlab4 =
	{
		"researchlab4_catcoon_costume",
		"researchlab4_catcoon_costumep",
		"researchlab4_chef",
		"researchlab4_chester_costume",
		"researchlab4_chester_costumep",
		"researchlab4_derby",
		"researchlab4_festive_bell_red_firehound",
		"researchlab4_glommer_costume",
		"researchlab4_glommer_costumep",
		"researchlab4_hutch_costume",
		"researchlab4_hutch_costumep",
		"researchlab4_merchant",
		"researchlab4_tophat_circus",
		"researchlab4_tophat_harlequin",
		"researchlab4_witch_pyre",
	},
	reskin_tool =
	{
		"reskin_tool_brush",
	},
	reviver =
	{
		"reviver_cupid",
		"reviver_cupid_2",
		"reviver_cupid_2alt",
		"reviver_cupid_3",
		"reviver_cupid_3alt",
		"reviver_cupid_4",
		"reviver_cupid_4alt",
		"reviver_cupid_alt",
		"reviver_lifecrystal",
	},
	ruins_bat =
	{
		"ruins_bat_heavy",
	},
	ruinshat =
	{
		"ruinshat_arcane",
	},
	saddle_basic =
	{
		"saddle_basic_yotb",
		"saddle_basic_yotbalt",
	},
	saltbox =
	{
		"saltbox_nautical",
		"saltbox_shaker",
		"saltbox_victorian",
	},
	sculptingtable =
	{
		"sculptingtable_gothic",
	},
	seafaring_prototyper =
	{
		"seafaring_prototyper_lighthouse",
	},
	seedpouch =
	{
		"seedpouch_rustic",
	},
	shovel =
	{
		"shovel_feathered",
		"shovel_invisible",
		"shovel_northern",
		"shovel_victorian",
	},
	skeletonhat =
	{
		"skeletonhat_shadowhelmet",
	},
	spear =
	{
		"spear_bee",
		"spear_forge_gungnir",
		"spear_forge_lance",
		"spear_hockey",
		"spear_northern",
		"spear_ragged",
		"spear_rose",
		"spear_simple",
	},
	spear_wathgrithr =
	{
		"spear_wathgrithr_northern",
		"spear_wathgrithr_valkyrie",
		"spear_wathgrithr_wrestle",
	},
	stagehand =
	{
		"stagehand_carpet",
		"stagehand_cawnival",
		"stagehand_cawnival_alt",
		"stagehand_dragonfly",
		"stagehand_vintage",
	},
	steeringwheel =
	{
		"steeringwheel_nautical",
	},
	steeringwheel_item =
	{
		"steeringwheel_item_nautical",
	},
	strawhat =
	{
		"strawhat_bonnet",
		"strawhat_cowboy",
		"strawhat_floppy",
	},
	supertacklecontainer =
	{
		"supertacklecontainer_shell",
	},
	tacklecontainer =
	{
		"tacklecontainer_shell",
	},
	telebase =
	{
		"telebase_crystal",
		"telebase_hallowpylon",
	},
	telestaff =
	{
		"telestaff_crystal",
		"telestaff_shadowbeam",
	},
	tent =
	{
		"tent_beach",
		"tent_circus",
		"tent_leaf",
	},
	tophat =
	{
		"hat_catcoon_costume",
		"hat_catcoon_costumep",
		"hat_chester_costume",
		"hat_chester_costumep",
		"hat_glommer_costume",
		"hat_glommer_costumep",
		"hat_hutch_costume",
		"hat_hutch_costumep",
		"tophat_chef",
		"tophat_circus",
		"tophat_derby",
		"tophat_festive_bell_red_firehound",
		"tophat_harlequin",
		"tophat_merchant",
		"tophat_witch_pyre",
	},
	torch =
	{
		"torch_carrat",
		"torch_carrat_alt",
		"torch_nautical",
		"torch_pillar",
		"torch_pillar_alt",
		"torch_pronged",
		"torch_rag",
		"torch_shadow",
		"torch_shadow_alt",
		"torch_spooky",
		"torch_spookyp",
	},
	trap =
	{
		"trap_basket",
		"trap_metal",
	},
	trap_teeth =
	{
		"trap_teeth_tiger",
	},
	treasurechest =
	{
		"treasurechest_carpetbag",
		"treasurechest_corruption",
		"treasurechest_crimson",
		"treasurechest_cupid",
		"treasurechest_cupidalt",
		"treasurechest_gingerbread",
		"treasurechest_monster",
		"treasurechest_posh",
		"treasurechest_poshprint",
		"treasurechest_sacred",
		"treasurechest_steamertrunk",
		"treasurechest_traincase",
		"treasurechest_traveltrunk",
		"treasurechest_vintage",
	},
	umbrella =
	{
		"umbrella_circus",
		"umbrella_heart",
		"umbrella_parasol",
		"umbrella_spider",
	},
	wall_moonrock =
	{
		"wall_moonrock_victorian",
	},
	wall_moonrock_item =
	{
		"wall_moonrock_victorianitem",
	},
	wall_ruins =
	{
		"wall_ruins_thulecite",
		"wall_ruins_thulecite_alt",
		"wall_ruins_victorian",
	},
	wall_ruins_item =
	{
		"wall_ruins_thulecite_alt_item",
		"wall_ruins_thuleciteitem",
		"wall_ruins_victorianitem",
	},
	wall_stone =
	{
		"wall_stone_ancient",
		"wall_stone_ancient_alt",
		"wall_stone_gothic",
		"wall_stone_victorian",
	},
	wall_stone_item =
	{
		"wall_stone_ancient_alt_item",
		"wall_stone_ancientitem",
		"wall_stone_gothicitem",
		"wall_stone_victorianitem",
	},
	walrushat =
	{
		"walrushat_blue",
	},
	walter =
	{
		"walter_bee",
		"walter_bee_d",
		"walter_bee_p",
		"walter_detective",
		"walter_formal",
		"walter_ice",
		"walter_nature",
		"walter_none",
		"walter_survivor",
		"walter_ventriloquist",
		"walter_victorian",
	},
	walterhat =
	{
		"walterhat_bee",
		"walterhat_beep",
		"walterhat_detective",
		"walterhat_formal",
		"walterhat_ice",
		"walterhat_nature",
		"walterhat_survivor",
		"walterhat_ventriloquist",
		"walterhat_victorian",
	},
	wanda =
	{
		"wanda_bishop",
		"wanda_bishop_d",
		"wanda_bishop_p",
		"wanda_formal",
		"wanda_none",
		"wanda_shadow",
		"wanda_steampunk",
		"wanda_yule",
	},
	wardrobe =
	{
		"wardrobe_armoire",
		"wardrobe_crystal",
		"wardrobe_gothic",
		"wardrobe_heart",
		"wardrobe_vine",
		"wardrobe_yule",
	},
	warly =
	{
		"warly_candyman",
		"warly_carrat",
		"warly_carrat_d",
		"warly_carrat_p",
		"warly_chef",
		"warly_fisherman",
		"warly_ice",
		"warly_nature",
		"warly_none",
		"warly_rose",
		"warly_victorian",
	},
	wateringcan =
	{
		"wateringcan_rustic",
	},
	watermelonhat =
	{
		"watermelonhat_pumpkin",
	},
	wathgrithr =
	{
		"wathgrithr_combatant",
		"wathgrithr_cook",
		"wathgrithr_deerclops",
		"wathgrithr_deerclops_d",
		"wathgrithr_deerclops_p",
		"wathgrithr_formal",
		"wathgrithr_formalp",
		"wathgrithr_gladiator",
		"wathgrithr_magma",
		"wathgrithr_nature",
		"wathgrithr_none",
		"wathgrithr_rose",
		"wathgrithr_rosep",
		"wathgrithr_scarecrow",
		"wathgrithr_shadow",
		"wathgrithr_shadowp",
		"wathgrithr_survivor",
		"wathgrithr_survivorp",
		"wathgrithr_valkyrie",
		"wathgrithr_victorian",
		"wathgrithr_wrestler",
		"wathgrithr_yule",
	},
	wathgrithrhat =
	{
		"wathgrithrhat_valkyrie",
		"wathgrithrhat_wrestle",
	},
	waxwell =
	{
		"waxwell_combatant",
		"waxwell_cook",
		"waxwell_formal",
		"waxwell_gladiator",
		"waxwell_krampus",
		"waxwell_krampus_d",
		"waxwell_krampus_p",
		"waxwell_magma",
		"waxwell_nature",
		"waxwell_none",
		"waxwell_rose",
		"waxwell_survivor",
		"waxwell_unshadow",
		"waxwell_vampire",
		"waxwell_victorian",
		"waxwell_yule",
	},
	webber =
	{
		"webber_bat",
		"webber_bat_d",
		"webber_bat_p",
		"webber_boy",
		"webber_combatant",
		"webber_cook",
		"webber_formal",
		"webber_formalp",
		"webber_gladiator",
		"webber_ice",
		"webber_magma",
		"webber_nature",
		"webber_none",
		"webber_punk",
		"webber_rose",
		"webber_rosep",
		"webber_shadow",
		"webber_shadowp",
		"webber_survivor",
		"webber_survivorp",
		"webber_victorian",
		"webber_wrestler",
	},
	webber_beard =
	{
		"webber_beard_bat",
		"webber_beard_boy",
		"webber_beard_formal",
		"webber_beard_gladiator",
		"webber_beard_ice",
		"webber_beard_magma",
		"webber_beard_nature",
		"webber_beard_punk",
		"webber_beard_rose",
		"webber_beard_shadow",
		"webber_beard_survivor",
		"webber_beard_victorian",
		"webber_beard_wrestler",
	},
	wendy =
	{
		"wendy_combatant",
		"wendy_cook",
		"wendy_creepy",
		"wendy_formal",
		"wendy_formalp",
		"wendy_gladiator",
		"wendy_handmedown",
		"wendy_ice",
		"wendy_lureplant",
		"wendy_lureplant_d",
		"wendy_lureplant_p",
		"wendy_magma",
		"wendy_nature",
		"wendy_none",
		"wendy_rose",
		"wendy_rosep",
		"wendy_shadow",
		"wendy_shadowp",
		"wendy_survivor",
		"wendy_survivorp",
		"wendy_victorian",
	},
	wes =
	{
		"wes_clown",
		"wes_combatant",
		"wes_cook",
		"wes_formal",
		"wes_formalp",
		"wes_gladiator",
		"wes_harlequin",
		"wes_magma",
		"wes_mandrake",
		"wes_mandrake_d",
		"wes_mandrake_p",
		"wes_nature",
		"wes_none",
		"wes_rose",
		"wes_rosep",
		"wes_shadow",
		"wes_shadowp",
		"wes_survivor",
		"wes_survivorp",
		"wes_victorian",
		"wes_wrestler",
		"wes_yule",
	},
	whip =
	{
		"whip_snapthorn",
	},
	wickerbottom =
	{
		"wickerbottom_combatant",
		"wickerbottom_cook",
		"wickerbottom_formal",
		"wickerbottom_gladiator",
		"wickerbottom_ice",
		"wickerbottom_lightninggoat",
		"wickerbottom_lightninggoat_d",
		"wickerbottom_lightninggoat_p",
		"wickerbottom_magma",
		"wickerbottom_none",
		"wickerbottom_rose",
		"wickerbottom_shadow",
		"wickerbottom_spiderwitch",
		"wickerbottom_survivor",
		"wickerbottom_victorian",
		"wickerbottom_yule",
	},
	willow =
	{
		"willow_combatant",
		"willow_cook",
		"willow_dowdy",
		"willow_dragonfly",
		"willow_dragonfly_d",
		"willow_dragonfly_p",
		"willow_formal",
		"willow_formalp",
		"willow_gladiator",
		"willow_haunteddoll",
		"willow_ice",
		"willow_magma",
		"willow_none",
		"willow_rose",
		"willow_rosep",
		"willow_shadow",
		"willow_shadowp",
		"willow_survivor",
		"willow_survivorp",
		"willow_victorian",
		"willow_yule",
	},
	wilson =
	{
		"wilson_combatant",
		"wilson_cook",
		"wilson_formal",
		"wilson_gladiator",
		"wilson_ice",
		"wilson_madscience",
		"wilson_magma",
		"wilson_nature",
		"wilson_none",
		"wilson_pigguard",
		"wilson_pigguard_d",
		"wilson_pigguard_p",
		"wilson_rose",
		"wilson_shadow",
		"wilson_survivor",
		"wilson_victorian",
		"wilson_yule",
	},
	wilson_beard =
	{
		"wilson_beard_formal",
		"wilson_beard_gladiator",
		"wilson_beard_ice",
		"wilson_beard_madscience",
		"wilson_beard_magma",
		"wilson_beard_nature",
		"wilson_beard_pigguard",
		"wilson_beard_rose",
		"wilson_beard_shadow",
		"wilson_beard_survivor",
		"wilson_beard_victorian",
		"wilson_beard_yule",
	},
	winona =
	{
		"winona_combatant",
		"winona_cook",
		"winona_factory",
		"winona_formal",
		"winona_formalp",
		"winona_frankenstein",
		"winona_gladiator",
		"winona_grassgecko",
		"winona_grassgecko_d",
		"winona_grassgecko_p",
		"winona_ice",
		"winona_magma",
		"winona_nature",
		"winona_none",
		"winona_rose",
		"winona_rosep",
		"winona_shadow",
		"winona_shadowp",
		"winona_survivor",
		"winona_survivorp",
		"winona_victorian",
		"winona_wrestler",
		"winona_yule",
	},
	winterhat =
	{
		"winterhat_black_davys",
		"winterhat_fancy_puppy",
		"winterhat_fancy_puppyalt",
		"winterhat_pink_hibiscus",
		"winterhat_plum_pudding",
		"winterhat_rooster",
		"winterhat_rooster_alt",
		"winterhat_stocking_cap_green_forest",
	},
	winterometer =
	{
		"winterometer_circus",
	},
	wolfgang =
	{
		"wolfgang_combatant",
		"wolfgang_cook",
		"wolfgang_formal",
		"wolfgang_formalp",
		"wolfgang_gladiator",
		"wolfgang_ice",
		"wolfgang_magma",
		"wolfgang_nature",
		"wolfgang_none",
		"wolfgang_rose",
		"wolfgang_rosep",
		"wolfgang_shadow",
		"wolfgang_shadowp",
		"wolfgang_strongman",
		"wolfgang_survivor",
		"wolfgang_survivorp",
		"wolfgang_victorian",
		"wolfgang_walrus",
		"wolfgang_walrus_d",
		"wolfgang_walrus_p",
		"wolfgang_wolfman",
		"wolfgang_wrestler",
	},
	woodie =
	{
		"woodie_combatant",
		"woodie_cook",
		"woodie_formal",
		"woodie_formalp",
		"woodie_gladiator",
		"woodie_hippie",
		"woodie_hockey",
		"woodie_magma",
		"woodie_nature",
		"woodie_none",
		"woodie_rose",
		"woodie_rosep",
		"woodie_shadow",
		"woodie_shadowp",
		"woodie_survivor",
		"woodie_survivorp",
		"woodie_treeguard",
		"woodie_treeguard_d",
		"woodie_treeguard_p",
		"woodie_victorian",
		"woodie_yule",
	},
	wormhole =
	{
		"wormhole_claw",
		"wormhole_lureplant",
		"wormhole_spider",
		"wormhole_worm",
	},
	wormwood =
	{
		"wormwood_cactus",
		"wormwood_mushroom",
		"wormwood_none",
		"wormwood_pumpkin",
		"wormwood_rose",
		"wormwood_saladmander",
		"wormwood_saladmander_d",
		"wormwood_saladmander_p",
		"wormwood_shadow",
		"wormwood_victorian",
		"wormwood_yule",
	},
	wortox =
	{
		"wortox_dragon",
		"wortox_ice",
		"wortox_minotaur",
		"wortox_nature",
		"wortox_noeyeddeer",
		"wortox_noeyeddeer_d",
		"wortox_noeyeddeer_p",
		"wortox_none",
		"wortox_original",
		"wortox_survivor",
		"wortox_victorian",
	},
	wurt =
	{
		"wurt_cave",
		"wurt_formal",
		"wurt_none",
		"wurt_rose",
		"wurt_shadow",
		"wurt_squid",
		"wurt_toadstool",
		"wurt_toadstool_d",
		"wurt_toadstool_p",
		"wurt_victorian",
		"wurt_yule",
	},
	wx78 =
	{
		"wx78_combatant",
		"wx78_cook",
		"wx78_formal",
		"wx78_formalp",
		"wx78_gladiator",
		"wx78_ice",
		"wx78_magma",
		"wx78_nature",
		"wx78_none",
		"wx78_retro",
		"wx78_rhinorook",
		"wx78_rhinorook_d",
		"wx78_rhinorook_p",
		"wx78_rose",
		"wx78_rosep",
		"wx78_shadow",
		"wx78_shadowp",
		"wx78_survivor",
		"wx78_survivorp",
		"wx78_victorian",
		"wx78_wip",
		"wx78_wrestler",
		"wx78_yule",
	},
	yellowstaff =
	{
		"starstaff_crystal",
		"starstaff_portal",
	},

}

PREFAB_SKINS_IDS = {}
for prefab,skins in pairs(PREFAB_SKINS) do
	PREFAB_SKINS_IDS[prefab] = {}
	for k,v in pairs(skins) do
		PREFAB_SKINS_IDS[prefab][v] = k
	end
end
