-- AUTOGENERATED CODE BY export_accountitems.lua

PREFAB_SKINS = {
	amulet = 
	{
		"amulet_red_occulteye",
	},
	armordragonfly = 
	{
		"armor_dragonfly_fangedcollar",
		"armor_dragonfly_haramaki",
		"armor_dragonfly_lamellar",
	},
	armorgrass = 
	{
		"armor_grass_cloak",
		"armor_grass_woven",
	},
	armormarble = 
	{
		"armor_marble_chainmail",
		"armor_marble_rockabs",
	},
	armorwood = 
	{
		"armor_wood_fangedcollar",
		"armor_wood_haramaki",
		"armor_wood_lamellar",
	},
	backpack = 
	{
		"backpack_basic_blue_catcoon",
		"backpack_basic_green_olive",
		"backpack_bat",
		"backpack_beefalo",
		"backpack_buckle_grey_pewter",
		"backpack_buckle_navy_phthalo",
		"backpack_buckle_red_rook",
		"backpack_camping_green_viridian",
		"backpack_camping_orange_carrot",
		"backpack_camping_red_koalefant",
		"backpack_catcoon",
		"backpack_crab",
		"backpack_deerclops",
		"backpack_dragonfly_fire",
		"backpack_glommer",
		"backpack_mandrake",
		"backpack_mushy",
		"backpack_poop",
		"backpack_rabbit",
		"backpack_smallbird",
		"backpack_spider",
	},
	bedroll_furry = 
	{
		"bedroll_furry_quilt_blue_frost",
		"bedroll_furry_quilt_white_ivory",
	},
	birdcage = 
	{
		"birdcage_gothic",
		"birdcage_ornamental",
		"birdcage_pirate",
	},
	book_brimstone = 
	{
		"book_brimstone_gilded",
	},
	cane = 
	{
		"cane_ancient",
	},
	catcoonhat = 
	{
		"catcoonhat_trapper_rooster",
		"catcoonhat_trapperup_rooster",
	},
	cookpot = 
	{
		"cookpot_cauldron",
		"cookpot_survival",
	},
	critter_dragonling = 
	{
		"dragonling_bat",
		"dragonling_winter",
		"dragonling_wyvern",
	},
	critter_dragonling_builder = 
	{
		"dragonling_bat_builder",
		"dragonling_winter_builder",
		"dragonling_wyvern_builder",
	},
	critter_glomling = 
	{
		"glomling_beardeddragon",
		"glomling_winter",
	},
	critter_glomling_builder = 
	{
		"glomling_beardeddragon_builder",
		"glomling_winter_builder",
	},
	critter_kitten = 
	{
		"kitten_winter",
	},
	critter_kitten_builder = 
	{
		"kitten_winter_builder",
	},
	critter_lamb = 
	{
		"lamb_winter",
	},
	critter_lamb_builder = 
	{
		"lamb_winter_builder",
	},
	critter_perdling = 
	{
		"perdling_rooster",
		"perdling_winter",
	},
	critter_perdling_builder = 
	{
		"perdling_rooster_builder",
		"perdling_winter_builder",
	},
	critter_puppy = 
	{
		"puppy_winter",
	},
	critter_puppy_builder = 
	{
		"puppy_winter_builder",
	},
	endtable = 
	{
		"endtable_carpet",
		"endtable_dragonfly",
		"endtable_vintage",
	},
	firepit = 
	{
		"firepit_fanged",
		"firepit_hole",
		"firepit_stonehenge",
	},
	firestaff = 
	{
		"firestaff_bee",
		"firestaff_meteor",
		"firestaff_rose",
	},
	flowerhat = 
	{
		"flowerhat_crown",
		"flowerhat_healing",
		"flowerhat_holly_wreath",
		"flowerhat_ribbon_wreath",
		"flowerhat_wreath",
	},
	footballhat = 
	{
		"footballhat_combathelm",
	},
	hambat = 
	{
		"hambat_spiralcut",
	},
	icestaff = 
	{
		"icestaff_bee",
		"icestaff_rose",
	},
	minerhat = 
	{
		"minerhat_floppy",
	},
	orangestaff = 
	{
		"orangestaff_ancient",
	},
	rainhat = 
	{
		"rainhat_floppy",
	},
	researchlab2 = 
	{
		"researchlab2_pod",
		"researchlab2_pod_alt",
	},
	researchlab4 = 
	{
		"researchlab4_catcoon_costume",
		"researchlab4_chester_costume",
		"researchlab4_derby",
		"researchlab4_festive_bell_red_firehound",
		"researchlab4_glommer_costume",
		"researchlab4_hutch_costume",
	},
	reviver = 
	{
		"reviver_cupid",
	},
	spear = 
	{
		"spear_bee",
		"spear_rose",
	},
	strawhat = 
	{
		"strawhat_floppy",
	},
	tophat = 
	{
		"hat_catcoon_costume",
		"hat_chester_costume",
		"hat_glommer_costume",
		"hat_hutch_costume",
		"tophat_derby",
		"tophat_festive_bell_red_firehound",
	},
	torch = 
	{
		"torch_rag",
		"torch_shadow",
		"torch_shadow_alt",
		"torch_spooky",
	},
	treasurechest = 
	{
		"treasurechest_carpetbag",
		"treasurechest_gingerbread",
		"treasurechest_posh",
		"treasurechest_poshprint",
		"treasurechest_sacred",
		"treasurechest_steamertrunk",
		"treasurechest_traincase",
		"treasurechest_traveltrunk",
	},
	wathgrithr = 
	{
		"wathgrithr_none",
		"wathgrithr_combatant",
		"wathgrithr_deerclops",
		"wathgrithr_deerclops_d",
		"wathgrithr_formal",
		"wathgrithr_gladiator",
		"wathgrithr_rose",
		"wathgrithr_shadow",
		"wathgrithr_survivor",
	},
	waxwell = 
	{
		"waxwell_none",
		"waxwell_combatant",
		"waxwell_formal",
		"waxwell_gladiator",
		"waxwell_krampus",
		"waxwell_krampus_d",
		"waxwell_rose",
		"waxwell_survivor",
		"waxwell_unshadow",
	},
	webber = 
	{
		"webber_none",
		"webber_bat",
		"webber_bat_d",
		"webber_combatant",
		"webber_formal",
		"webber_gladiator",
		"webber_ice",
		"webber_rose",
		"webber_shadow",
		"webber_survivor",
	},
	wendy = 
	{
		"wendy_none",
		"wendy_combatant",
		"wendy_formal",
		"wendy_gladiator",
		"wendy_ice",
		"wendy_lureplant",
		"wendy_lureplant_d",
		"wendy_rose",
		"wendy_shadow",
		"wendy_survivor",
	},
	wes = 
	{
		"wes_none",
		"wes_combatant",
		"wes_formal",
		"wes_gladiator",
		"wes_mandrake",
		"wes_mandrake_d",
		"wes_rose",
		"wes_shadow",
		"wes_survivor",
	},
	wickerbottom = 
	{
		"wickerbottom_none",
		"wickerbottom_combatant",
		"wickerbottom_formal",
		"wickerbottom_gladiator",
		"wickerbottom_ice",
		"wickerbottom_lightninggoat",
		"wickerbottom_lightninggoat_d",
		"wickerbottom_rose",
		"wickerbottom_shadow",
		"wickerbottom_survivor",
	},
	willow = 
	{
		"willow_none",
		"willow_combatant",
		"willow_dragonfly",
		"willow_dragonfly_d",
		"willow_formal",
		"willow_gladiator",
		"willow_ice",
		"willow_rose",
		"willow_shadow",
		"willow_survivor",
	},
	wilson = 
	{
		"wilson_none",
		"wilson_combatant",
		"wilson_formal",
		"wilson_gladiator",
		"wilson_ice",
		"wilson_pigguard",
		"wilson_pigguard_d",
		"wilson_rose",
		"wilson_shadow",
		"wilson_survivor",
	},
	winona = 
	{
		"winona_none",
		"winona_combatant",
		"winona_formal",
		"winona_gladiator",
		"winona_grassgecko",
		"winona_grassgecko_d",
		"winona_rose",
		"winona_shadow",
		"winona_survivor",
	},
	winterhat = 
	{
		"winterhat_black_davys",
		"winterhat_pink_hibiscus",
		"winterhat_plum_pudding",
		"winterhat_rooster",
		"winterhat_stocking_cap_green_forest",
	},
	wolfgang = 
	{
		"wolfgang_none",
		"wolfgang_combatant",
		"wolfgang_formal",
		"wolfgang_gladiator",
		"wolfgang_ice",
		"wolfgang_rose",
		"wolfgang_shadow",
		"wolfgang_survivor",
		"wolfgang_walrus",
		"wolfgang_walrus_d",
	},
	woodie = 
	{
		"woodie_none",
		"woodie_combatant",
		"woodie_formal",
		"woodie_gladiator",
		"woodie_rose",
		"woodie_shadow",
		"woodie_survivor",
		"woodie_treeguard",
		"woodie_treeguard_d",
	},
	wx78 = 
	{
		"wx78_none",
		"wx78_combatant",
		"wx78_formal",
		"wx78_gladiator",
		"wx78_rhinorook",
		"wx78_rhinorook_d",
		"wx78_rose",
		"wx78_shadow",
		"wx78_survivor",
	},

}

PREFAB_SKINS_IDS = {}
for prefab,skins in pairs(PREFAB_SKINS) do
	PREFAB_SKINS_IDS[prefab] = {}
	for k,v in pairs(skins) do
		PREFAB_SKINS_IDS[prefab][v] = k
	end
end
