-- AUTOGENERATED CODE BY export_accountitems.lua

PREFAB_SKINS = {
	amulet = 
	{
		"amulet_red_heart",
		"amulet_red_occulteye",
	},
	armordragonfly = 
	{
		"armor_dragonfly_fangedcollar",
		"armor_dragonfly_haramaki",
		"armor_dragonfly_lamellar",
	},
	armorgrass = 
	{
		"armor_grass_cloak",
		"armor_grass_woven",
	},
	armormarble = 
	{
		"armor_marble_chainmail",
		"armor_marble_rockabs",
	},
	armorruins = 
	{
		"armor_ruins_arcane",
		"armor_ruins_bulky",
		"armor_ruins_leaf",
		"armor_ruins_tusk",
	},
	armorwood = 
	{
		"armor_wood_fangedcollar",
		"armor_wood_haramaki",
		"armor_wood_lamellar",
	},
	arrowsign_post = 
	{
		"arrowsign_post_circus",
		"arrowsign_post_factory",
	},
	axe = 
	{
		"axe_victorian",
	},
	backpack = 
	{
		"backpack_basic_blue_catcoon",
		"backpack_basic_green_olive",
		"backpack_bat",
		"backpack_beefalo",
		"backpack_buckle_grey_pewter",
		"backpack_buckle_navy_phthalo",
		"backpack_buckle_red_rook",
		"backpack_camping_green_viridian",
		"backpack_camping_orange_carrot",
		"backpack_camping_red_koalefant",
		"backpack_catcoon",
		"backpack_crab",
		"backpack_deerclops",
		"backpack_dragonfly_fire",
		"backpack_glommer",
		"backpack_mandrake",
		"backpack_mushy",
		"backpack_poop",
		"backpack_rabbit",
		"backpack_smallbird",
		"backpack_spider",
	},
	batbat = 
	{
		"batbat_scythe",
	},
	bedroll_furry = 
	{
		"bedroll_furry_quilt_blue_frost",
		"bedroll_furry_quilt_white_ivory",
	},
	beefalohat = 
	{
		"beefalohat_pigking",
	},
	beehat = 
	{
		"beehat_mourning",
	},
	birdcage = 
	{
		"birdcage_circus",
		"birdcage_gothic",
		"birdcage_ornamental",
		"birdcage_pirate",
		"birdcage_romantic",
	},
	book_brimstone = 
	{
		"book_brimstone_gilded",
	},
	bugnet = 
	{
		"bugnet_spider",
	},
	cane = 
	{
		"cane_ancient",
		"cane_victorian",
	},
	catcoonhat = 
	{
		"catcoonhat_trapper_rooster",
		"catcoonhat_trapperup_rooster",
		"hat_puppy_cap",
	},
	cookpot = 
	{
		"cookpot_cauldron",
		"cookpot_survival",
		"cookpot_tureen",
	},
	critter_dragonling = 
	{
		"dragonling_bat",
		"dragonling_winter",
		"dragonling_wyvern",
	},
	critter_dragonling_builder = 
	{
		"dragonling_bat_builder",
		"dragonling_winter_builder",
		"dragonling_wyvern_builder",
	},
	critter_glomling = 
	{
		"glomling_beardeddragon",
		"glomling_winter",
	},
	critter_glomling_builder = 
	{
		"glomling_beardeddragon_builder",
		"glomling_winter_builder",
	},
	critter_kitten = 
	{
		"kitten_black",
		"kitten_winter",
	},
	critter_kitten_builder = 
	{
		"kitten_black_builder",
		"kitten_winter_builder",
	},
	critter_lamb = 
	{
		"lamb_winter",
	},
	critter_lamb_builder = 
	{
		"lamb_winter_builder",
	},
	critter_perdling = 
	{
		"perdling_rooster",
		"perdling_winter",
	},
	critter_perdling_builder = 
	{
		"perdling_rooster_builder",
		"perdling_winter_builder",
	},
	critter_puppy = 
	{
		"puppy_chow",
		"puppy_tzu",
		"puppy_winter",
	},
	critter_puppy_builder = 
	{
		"puppy_chow_builder",
		"puppy_tzu_builder",
		"puppy_winter_builder",
	},
	endtable = 
	{
		"endtable_carpet",
		"endtable_dragonfly",
		"endtable_vintage",
	},
	featherhat = 
	{
		"featherhat_circus",
	},
	fence = 
	{
		"fence_factory",
	},
	fence_item = 
	{
		"fence_factory_item",
	},
	firepit = 
	{
		"firepit_fanged",
		"firepit_firebird",
		"firepit_hole",
		"firepit_stonehenge",
		"firepit_victorian",
	},
	firestaff = 
	{
		"firestaff_bee",
		"firestaff_gungnir",
		"firestaff_lance",
		"firestaff_meteor",
		"firestaff_rose",
	},
	firesuppressor = 
	{
		"firesuppressor_circus",
	},
	flowerhat = 
	{
		"flowerhat_crown",
		"flowerhat_healing",
		"flowerhat_holly_wreath",
		"flowerhat_ribbon_wreath",
		"flowerhat_wreath",
	},
	footballhat = 
	{
		"footballhat_combathelm",
		"footballhat_combathelm2",
		"hat_dog_helm",
	},
	hambat = 
	{
		"hambat_potroast",
		"hambat_spiralcut",
	},
	hammer = 
	{
		"hammer_crowbar",
		"hammer_forge",
	},
	icebox = 
	{
		"icebox_coffin",
		"icebox_victorian",
	},
	icestaff = 
	{
		"icestaff_bee",
		"icestaff_gungnir",
		"icestaff_lance",
		"icestaff_rose",
	},
	lantern = 
	{
		"lantern_tesla",
		"lantern_winter",
	},
	minerhat = 
	{
		"minerhat_cowboy",
		"minerhat_floppy",
	},
	orangestaff = 
	{
		"orangestaff_ancient",
		"orangestaff_victorian",
	},
	rainhat = 
	{
		"rainhat_cowboy",
		"rainhat_floppy",
	},
	rainometer = 
	{
		"rainometer_circus",
	},
	researchlab2 = 
	{
		"researchlab2_pod",
		"researchlab2_pod_alt",
	},
	researchlab4 = 
	{
		"researchlab4_catcoon_costume",
		"researchlab4_chester_costume",
		"researchlab4_derby",
		"researchlab4_festive_bell_red_firehound",
		"researchlab4_glommer_costume",
		"researchlab4_hutch_costume",
		"researchlab4_tophat_circus",
		"researchlab4_witch_pyre",
	},
	reviver = 
	{
		"reviver_cupid",
		"reviver_cupid_2",
		"reviver_cupid_3",
	},
	ruins_bat = 
	{
		"ruins_bat_heavy",
	},
	shovel = 
	{
		"shovel_victorian",
	},
	spear = 
	{
		"spear_bee",
		"spear_forge_gungnir",
		"spear_forge_lance",
		"spear_rose",
	},
	spear_wathgrithr = 
	{
		"spear_wathgrithr_wrestle",
	},
	strawhat = 
	{
		"strawhat_cowboy",
		"strawhat_floppy",
	},
	tent = 
	{
		"tent_circus",
	},
	tophat = 
	{
		"hat_catcoon_costume",
		"hat_chester_costume",
		"hat_glommer_costume",
		"hat_hutch_costume",
		"tophat_circus",
		"tophat_derby",
		"tophat_festive_bell_red_firehound",
		"tophat_witch_pyre",
	},
	torch = 
	{
		"torch_rag",
		"torch_shadow",
		"torch_shadow_alt",
		"torch_spooky",
	},
	treasurechest = 
	{
		"treasurechest_carpetbag",
		"treasurechest_gingerbread",
		"treasurechest_monster",
		"treasurechest_posh",
		"treasurechest_poshprint",
		"treasurechest_sacred",
		"treasurechest_steamertrunk",
		"treasurechest_traincase",
		"treasurechest_traveltrunk",
	},
	umbrella = 
	{
		"umbrella_circus",
		"umbrella_heart",
		"umbrella_spider",
	},
	wardrobe = 
	{
		"wardrobe_heart",
	},
	watermelonhat = 
	{
		"watermelonhat_pumpkin",
	},
	wathgrithr = 
	{
		"wathgrithr_combatant",
		"wathgrithr_cook",
		"wathgrithr_deerclops",
		"wathgrithr_deerclops_d",
		"wathgrithr_formal",
		"wathgrithr_gladiator",
		"wathgrithr_magma",
		"wathgrithr_nature",
		"wathgrithr_none",
		"wathgrithr_rose",
		"wathgrithr_shadow",
		"wathgrithr_survivor",
		"wathgrithr_victorian",
		"wathgrithr_wrestler",
	},
	wathgrithrhat = 
	{
		"wathgrithrhat_wrestle",
	},
	waxwell = 
	{
		"waxwell_combatant",
		"waxwell_cook",
		"waxwell_formal",
		"waxwell_gladiator",
		"waxwell_krampus",
		"waxwell_krampus_d",
		"waxwell_magma",
		"waxwell_nature",
		"waxwell_none",
		"waxwell_rose",
		"waxwell_survivor",
		"waxwell_unshadow",
		"waxwell_victorian",
	},
	webber = 
	{
		"webber_bat",
		"webber_bat_d",
		"webber_combatant",
		"webber_cook",
		"webber_formal",
		"webber_gladiator",
		"webber_ice",
		"webber_magma",
		"webber_none",
		"webber_punk",
		"webber_rose",
		"webber_shadow",
		"webber_survivor",
		"webber_victorian",
	},
	wendy = 
	{
		"wendy_combatant",
		"wendy_cook",
		"wendy_creepy",
		"wendy_formal",
		"wendy_gladiator",
		"wendy_ice",
		"wendy_lureplant",
		"wendy_lureplant_d",
		"wendy_magma",
		"wendy_none",
		"wendy_rose",
		"wendy_shadow",
		"wendy_survivor",
		"wendy_victorian",
	},
	wes = 
	{
		"wes_clown",
		"wes_combatant",
		"wes_cook",
		"wes_formal",
		"wes_gladiator",
		"wes_magma",
		"wes_mandrake",
		"wes_mandrake_d",
		"wes_nature",
		"wes_none",
		"wes_rose",
		"wes_shadow",
		"wes_survivor",
		"wes_victorian",
		"wes_wrestler",
	},
	wickerbottom = 
	{
		"wickerbottom_combatant",
		"wickerbottom_cook",
		"wickerbottom_formal",
		"wickerbottom_gladiator",
		"wickerbottom_ice",
		"wickerbottom_lightninggoat",
		"wickerbottom_lightninggoat_d",
		"wickerbottom_magma",
		"wickerbottom_none",
		"wickerbottom_rose",
		"wickerbottom_shadow",
		"wickerbottom_survivor",
		"wickerbottom_victorian",
	},
	willow = 
	{
		"willow_combatant",
		"willow_cook",
		"willow_dowdy",
		"willow_dragonfly",
		"willow_dragonfly_d",
		"willow_formal",
		"willow_gladiator",
		"willow_ice",
		"willow_magma",
		"willow_none",
		"willow_rose",
		"willow_shadow",
		"willow_survivor",
		"willow_victorian",
	},
	wilson = 
	{
		"wilson_combatant",
		"wilson_cook",
		"wilson_formal",
		"wilson_gladiator",
		"wilson_ice",
		"wilson_madscience",
		"wilson_magma",
		"wilson_none",
		"wilson_pigguard",
		"wilson_pigguard_d",
		"wilson_rose",
		"wilson_shadow",
		"wilson_survivor",
		"wilson_victorian",
	},
	winona = 
	{
		"winona_combatant",
		"winona_cook",
		"winona_factory",
		"winona_formal",
		"winona_formalp",
		"winona_gladiator",
		"winona_grassgecko",
		"winona_grassgecko_d",
		"winona_magma",
		"winona_nature",
		"winona_none",
		"winona_rose",
		"winona_rosep",
		"winona_shadow",
		"winona_shadowp",
		"winona_survivor",
		"winona_survivorp",
		"winona_victorian",
	},
	winterhat = 
	{
		"winterhat_black_davys",
		"winterhat_fancy_puppy",
		"winterhat_pink_hibiscus",
		"winterhat_plum_pudding",
		"winterhat_rooster",
		"winterhat_stocking_cap_green_forest",
	},
	winterometer = 
	{
		"winterometer_circus",
	},
	wolfgang = 
	{
		"wolfgang_combatant",
		"wolfgang_cook",
		"wolfgang_formal",
		"wolfgang_gladiator",
		"wolfgang_ice",
		"wolfgang_magma",
		"wolfgang_none",
		"wolfgang_rose",
		"wolfgang_shadow",
		"wolfgang_survivor",
		"wolfgang_victorian",
		"wolfgang_walrus",
		"wolfgang_walrus_d",
		"wolfgang_wrestler",
	},
	woodie = 
	{
		"woodie_combatant",
		"woodie_cook",
		"woodie_formal",
		"woodie_gladiator",
		"woodie_magma",
		"woodie_nature",
		"woodie_none",
		"woodie_rose",
		"woodie_shadow",
		"woodie_survivor",
		"woodie_treeguard",
		"woodie_treeguard_d",
		"woodie_victorian",
	},
	wx78 = 
	{
		"wx78_combatant",
		"wx78_cook",
		"wx78_formal",
		"wx78_gladiator",
		"wx78_magma",
		"wx78_nature",
		"wx78_none",
		"wx78_rhinorook",
		"wx78_rhinorook_d",
		"wx78_rose",
		"wx78_shadow",
		"wx78_survivor",
		"wx78_victorian",
		"wx78_wip",
	},

}

PREFAB_SKINS_IDS = {}
for prefab,skins in pairs(PREFAB_SKINS) do
	PREFAB_SKINS_IDS[prefab] = {}
	for k,v in pairs(skins) do
		PREFAB_SKINS_IDS[prefab][v] = k
	end
end
