-- AUTOGENERATED CODE BY export_accountitems.lua

local SKIN_GIFT_TYPES =
{
	cane_ancient = "ANRARG",
	emote_swoon = "CUPID",
	firepit_hole = "EARLY_ACCESS",
	reviver_cupid = "CUPID",
	torch_shadow = "ARG",
	torch_shadow_alt = "ARG",
	treasurechest_sacred = "ANRARG",
	winterhat_rooster = "LUNAR",
}

local SKIN_GIFT_POPUPDATA =
{
	ANRARG =
	{
		atlas = "images/thankyou_item_event.xml",
		image = {"thankyou_anrarg.tex"},
		title = STRINGS.THANKS_POPUP.ANRARG,
		titleoffset = {0, -20, 0},
	},
	ARG =
	{
		atlas = "images/thankyou_item_popup.xml",
		image = {"thankyou_gift.tex"},
		title = STRINGS.THANKS_POPUP.ARG,
		titleoffset = {0, -20, 0},
	},
	CUPID =
	{
		atlas = "images/thankyou_item_popup.xml",
		image = {"thankyou_gift.tex"},
		title = STRINGS.THANKS_POPUP.CUPID,
		titleoffset = {0, -30, 0},
	},
	LUNAR =
	{
		atlas = "images/thankyou_item_event.xml",
		image = {"thankyou_lunar.tex"},
		title = STRINGS.THANKS_POPUP.LUNAR,
		titleoffset = {0, -30, 0},
	},
}

return { types = SKIN_GIFT_TYPES, popupdata = SKIN_GIFT_POPUPDATA }
