-- AUTOGENERATED CODE BY export_accountitems.lua

return 
{
	PACKS =
	{
		pack_gladiator_all =
		{
			"wilson_gladiator",
			"willow_gladiator",
			"wolfgang_gladiator",
			"wendy_gladiator",
			"wx78_gladiator",
			"wickerbottom_gladiator",
			"woodie_gladiator",
			"wes_gladiator",
			"waxwell_gladiator",
			"wathgrithr_gladiator",
			"webber_gladiator",
			"winona_gladiator",
		},
		pack_gladiator_wathgrithr =
		{
			"wathgrithr_gladiator",
			"body_wathgrithr_gladiator",
			"feet_wathgrithr_gladiator",
			"hand_wathgrithr_gladiator",
			"legs_wathgrithr_gladiator",
		},
		pack_gladiator_waxwell =
		{
			"waxwell_gladiator",
			"body_waxwell_gladiator",
			"feet_waxwell_gladiator",
			"hand_waxwell_gladiator",
			"legs_waxwell_gladiator",
		},
		pack_gladiator_webber =
		{
			"webber_gladiator",
			"body_webber_gladiator",
			"feet_webber_gladiator",
			"hand_webber_gladiator",
		},
		pack_gladiator_wendy =
		{
			"wendy_gladiator",
			"body_wendy_gladiator",
			"feet_wendy_gladiator",
			"hand_wendy_gladiator",
		},
		pack_gladiator_wes =
		{
			"wes_gladiator",
			"body_wes_gladiator",
			"feet_wes_gladiator",
			"hand_wes_gladiator",
		},
		pack_gladiator_wickerbottom =
		{
			"wickerbottom_gladiator",
			"body_wickerbottom_gladiator",
			"feet_wickerbottom_gladiator",
			"hand_wickerbottom_gladiator",
		},
		pack_gladiator_willow =
		{
			"willow_gladiator",
			"body_willow_gladiator",
			"feet_willow_gladiator",
			"hand_willow_gladiator",
			"legs_willow_gladiator",
		},
		pack_gladiator_wilson =
		{
			"wilson_gladiator",
			"body_wilson_gladiator",
			"feet_wilson_gladiator",
			"hand_wilson_gladiator",
			"legs_wilson_gladiator",
		},
		pack_gladiator_winona =
		{
			"winona_gladiator",
			"body_winona_gladiator",
			"feet_winona_gladiator",
			"hand_winona_gladiator",
			"legs_winona_gladiator",
		},
		pack_gladiator_wolfgang =
		{
			"wolfgang_gladiator",
			"body_wolfgang_gladiator",
			"feet_wolfgang_gladiator",
			"hand_wolfgang_gladiator",
			"legs_wolfgang_gladiator",
		},
		pack_gladiator_woodie =
		{
			"woodie_gladiator",
			"body_woodie_gladiator",
			"feet_woodie_gladiator",
			"hand_woodie_gladiator",
			"legs_woodie_gladiator",
		},
		pack_gladiator_wx78 =
		{
			"wx78_gladiator",
			"body_wx78_gladiator",
			"feet_wx78_gladiator",
			"hand_wx78_gladiator",
			"legs_wx78_gladiator",
		},
		pack_ice_all =
		{
			"wilson_ice",
			"willow_ice",
			"wickerbottom_ice",
			"wendy_ice",
			"webber_ice",
			"wolfgang_ice",
		},
		pack_ice_webber =
		{
			"webber_ice",
			"body_webber_ice",
			"feet_webber_ice",
			"legs_webber_ice",
		},
		pack_ice_wendy =
		{
			"wendy_ice",
			"body_wendy_ice",
			"feet_wendy_ice",
			"hand_wendy_ice",
		},
		pack_ice_wickerbottom =
		{
			"wickerbottom_ice",
			"body_wickerbottom_ice",
			"feet_wickerbottom_ice1",
			"hand_wickerbottom_ice",
		},
		pack_ice_willow =
		{
			"willow_ice",
			"body_willow_ice",
			"feet_willow_ice",
			"hand_willow_ice",
		},
		pack_ice_wilson =
		{
			"wilson_ice",
			"body_wilson_ice",
			"feet_wilson_ice",
			"hand_wilson_ice",
			"legs_wilson_ice",
		},
		pack_ice_wolfgang =
		{
			"wolfgang_ice",
			"body_wolfgang_ice",
			"feet_wolfgang_ice",
			"hand_wolfgang_ice",
			"legs_wolfgang_ice",
		},
	},

	CONTENTS =
	{
		wathgrithr_gladiator = "pack_gladiator_wathgrithr",
		body_wathgrithr_gladiator = "pack_gladiator_wathgrithr",
		feet_wathgrithr_gladiator = "pack_gladiator_wathgrithr",
		hand_wathgrithr_gladiator = "pack_gladiator_wathgrithr",
		legs_wathgrithr_gladiator = "pack_gladiator_wathgrithr",
		waxwell_gladiator = "pack_gladiator_waxwell",
		body_waxwell_gladiator = "pack_gladiator_waxwell",
		feet_waxwell_gladiator = "pack_gladiator_waxwell",
		hand_waxwell_gladiator = "pack_gladiator_waxwell",
		legs_waxwell_gladiator = "pack_gladiator_waxwell",
		webber_gladiator = "pack_gladiator_webber",
		body_webber_gladiator = "pack_gladiator_webber",
		feet_webber_gladiator = "pack_gladiator_webber",
		hand_webber_gladiator = "pack_gladiator_webber",
		wendy_gladiator = "pack_gladiator_wendy",
		body_wendy_gladiator = "pack_gladiator_wendy",
		feet_wendy_gladiator = "pack_gladiator_wendy",
		hand_wendy_gladiator = "pack_gladiator_wendy",
		wes_gladiator = "pack_gladiator_wes",
		body_wes_gladiator = "pack_gladiator_wes",
		feet_wes_gladiator = "pack_gladiator_wes",
		hand_wes_gladiator = "pack_gladiator_wes",
		wickerbottom_gladiator = "pack_gladiator_wickerbottom",
		body_wickerbottom_gladiator = "pack_gladiator_wickerbottom",
		feet_wickerbottom_gladiator = "pack_gladiator_wickerbottom",
		hand_wickerbottom_gladiator = "pack_gladiator_wickerbottom",
		willow_gladiator = "pack_gladiator_willow",
		body_willow_gladiator = "pack_gladiator_willow",
		feet_willow_gladiator = "pack_gladiator_willow",
		hand_willow_gladiator = "pack_gladiator_willow",
		legs_willow_gladiator = "pack_gladiator_willow",
		wilson_gladiator = "pack_gladiator_wilson",
		body_wilson_gladiator = "pack_gladiator_wilson",
		feet_wilson_gladiator = "pack_gladiator_wilson",
		hand_wilson_gladiator = "pack_gladiator_wilson",
		legs_wilson_gladiator = "pack_gladiator_wilson",
		winona_gladiator = "pack_gladiator_winona",
		body_winona_gladiator = "pack_gladiator_winona",
		feet_winona_gladiator = "pack_gladiator_winona",
		hand_winona_gladiator = "pack_gladiator_winona",
		legs_winona_gladiator = "pack_gladiator_winona",
		wolfgang_gladiator = "pack_gladiator_wolfgang",
		body_wolfgang_gladiator = "pack_gladiator_wolfgang",
		feet_wolfgang_gladiator = "pack_gladiator_wolfgang",
		hand_wolfgang_gladiator = "pack_gladiator_wolfgang",
		legs_wolfgang_gladiator = "pack_gladiator_wolfgang",
		woodie_gladiator = "pack_gladiator_woodie",
		body_woodie_gladiator = "pack_gladiator_woodie",
		feet_woodie_gladiator = "pack_gladiator_woodie",
		hand_woodie_gladiator = "pack_gladiator_woodie",
		legs_woodie_gladiator = "pack_gladiator_woodie",
		wx78_gladiator = "pack_gladiator_wx78",
		body_wx78_gladiator = "pack_gladiator_wx78",
		feet_wx78_gladiator = "pack_gladiator_wx78",
		hand_wx78_gladiator = "pack_gladiator_wx78",
		legs_wx78_gladiator = "pack_gladiator_wx78",
		webber_ice = "pack_ice_webber",
		body_webber_ice = "pack_ice_webber",
		feet_webber_ice = "pack_ice_webber",
		legs_webber_ice = "pack_ice_webber",
		wendy_ice = "pack_ice_wendy",
		body_wendy_ice = "pack_ice_wendy",
		feet_wendy_ice = "pack_ice_wendy",
		hand_wendy_ice = "pack_ice_wendy",
		wickerbottom_ice = "pack_ice_wickerbottom",
		body_wickerbottom_ice = "pack_ice_wickerbottom",
		feet_wickerbottom_ice1 = "pack_ice_wickerbottom",
		hand_wickerbottom_ice = "pack_ice_wickerbottom",
		willow_ice = "pack_ice_willow",
		body_willow_ice = "pack_ice_willow",
		feet_willow_ice = "pack_ice_willow",
		hand_willow_ice = "pack_ice_willow",
		wilson_ice = "pack_ice_wilson",
		body_wilson_ice = "pack_ice_wilson",
		feet_wilson_ice = "pack_ice_wilson",
		hand_wilson_ice = "pack_ice_wilson",
		legs_wilson_ice = "pack_ice_wilson",
		wolfgang_ice = "pack_ice_wolfgang",
		body_wolfgang_ice = "pack_ice_wolfgang",
		feet_wolfgang_ice = "pack_ice_wolfgang",
		hand_wolfgang_ice = "pack_ice_wolfgang",
		legs_wolfgang_ice = "pack_ice_wolfgang",
	}

}

