return {
	ACTIONFAIL =
	{
        REPAIR =
        {
            WRONGPIECE = "PLUGIN INCOMPATIBLE",
        },
        BUILD =
        {
            MOUNTED = "NON-OPTIMAL ALTITUDE FOR PLACING",
            HASPET = "I ALREADY HAVE AN ORGANIC MINION",
        },
		SHAVE =
		{
			AWAKEBEEFALO = "DANGER! TARGET IS AWAKE",
			GENERIC = "THAT IS NOT A VALID SHAVE TARGET",
			NOBITS = "THERE IS NO STUBBLE TO SHAVE",
		},
		STORE =
		{
			GENERIC = "IT IS AT CAPACITY",
			NOTALLOWED = "THAT INPUT IS NOT ALLOWED",
			INUSE = "INFERIORS ARE USING IT RIGHT NOW.",
		},
		WRITE =
        {
            GENERIC = "WRITE ERROR",
            INUSE = "PRIMITIVE MESSAGEBOARD OCCUPIED",
        },
		RUMMAGE =
        {   
            GENERIC = "ERROR: DON'T WANT TO",
            INUSE = "I CAN HELP IF IT MAKES THIS GO FASTER", 
        },
        USEKLAUSSACKKEY =
        {
        	WRONGKEY = "INCORRECT UNLOCKING DEVICE",
        	KLAUS = "COMBAT PRIORITY: HIGH",
        },
		COOK =
        {
            GENERIC = "I DON'T WANT TO COOK",
            INUSE = "YOU MAY FEED ME, INFERIOR",
            TOOFAR = "NOT IN OPTIMAL RANGE",
        },
        MOUNT =
        {
            INUSE = "ERROR: MOUNT IN USE",
            TARGETINCOMBAT = "I'LL RIDE IT LATER. RIGHT NOW IT FIGHTS FOR MY AMUSEMENT",
        },
        SADDLE =
        {
            TARGETINCOMBAT = "I'LL RIDE IT LATER. RIGHT NOW IT FIGHTS FOR MY AMUSEMENT",
        },
        GIVE =
        {
            GENERIC = "ABSOLUTELY NOT",
            DEAD = "WHY? THEY'RE DEAD.",
            SLEEPING = "THAT UNIT IS BUSY RECHARGING",
            BUSY = "TARGET IS PREOCCUPIED",
            ABIGAILHEART = "FAILURE",
            GHOSTHEART = "NOT WORTH IT",
            NOTGEM = "PLUGIN DEVICE NOT COMPATIBLE",
            WRONGGEM = "INCORRECT MINERAL-BASED POWER SOURCE",
            NOTSTAFF = "WRONG THING",
            MUSHROOMFARM_NEEDSSHROOM = "FUNGUS UPDATE REQUIRED",
            MUSHROOMFARM_NEEDSLOG = "SPECIAL LOG-IN REQUIRED",
            SLOTFULL = "ERROR: MATERIALS ALREADY SELECTED",
            DUPLICATE = "ERROR: DUPLICATE RECIPE DETECTED",
            NOTSCULPTABLE = "MATERIAL TOO INFERIOR TO SCULPT",
            CANTSHADOWREVIVE = "REANIMATION: FAILED",
            WRONGSHADOWFORM = "ERROR: REBUILD SKELETON",
        },
        GIVETOPLAYER = 
        {
        	FULL = "TARGET ALREADY OVER CAPACITY",
            DEAD = "WHY? THEY'RE DEAD.",
            SLEEPING = "THAT UNIT IS BUSY RECHARGING",
            BUSY = "TARGET IS PREOCCUPIED",
    	},
    	DRAW =
        {
            NOIMAGE = "I REQUIRE SOMETHING REAL TO BASE THIS \"ART\" ON",
        },
    	CHANGEIN =
        {
            GENERIC = "THERE ARE MORE IMPORTANT ISSUES TO ATTEND TO",
            BURNING = "IT'S BURNING. OH WELL",
            INUSE = "OCCUPIED",
        },
    	GIVEALLTOPLAYER = 
        {
        	FULL = "TARGET ALREADY OVER CAPACITY",
            DEAD = "WHY? THEY'RE DEAD.",
            SLEEPING = "THAT UNIT IS BUSY RECHARGING",
            BUSY = "TARGET IS PREOCCUPIED",
    	},
    	ATTUNE =
        {
            NOHEALTH = "I MUST MAKE REPAIRS BEFORE DOING THIS",
        },
        TEACH =
        {
            KNOWN = "ONLY A FLESHBRAIN WOULD NEED THAT EXPLAINED TO THEM",
            CANTLEARN = "THE KNOWLEDGE WAS PROBABLY OBSOLETE ANYWAY",
            WRONGWORLD = "ERROR: INCORRECT LOCATION",
        },
        WRAPBUNDLE =
        {
            EMPTY = "ERROR: NO THINGS TO WRAP",
        },
        PICKUP =
        {
			RESTRICTION = "ERROR: INFERIOR WEAPON",
        },
	},
	ACTIONFAIL_GENERIC = "ERROR: ACTION UNAVAILABLE",
	ANNOUNCE_DIG_DISEASE_WARNING = "ANTIVIRAL PRECAUTIONS SUCCESSFUL",
	ANNOUNCE_PICK_DISEASE_WARNING = "VIRUS DETECTED",
	ANNOUNCE_MOUNT_LOWHEALTH = "WARNING: BEAST REQUIRES TUNE-UP",
	ANNOUNCE_NOSLEEPONFIRE = "SLEEPING SYSTEM COMPROMISED",
	ANNOUNCE_NODANGERSIESTA = "WARNING: THREAT DETECTED. CANNOT INITIATE SIESTA MODE",
	ANNOUNCE_NONIGHTSIESTA = "ERROR: SIESTA MODE UNAVAILABLE AT NIGHT",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "ERROR: SIESTA MODE UNAVAILABLE AT NIGHT",
	ANNOUNCE_NOHUNGERSIESTA = "CANNOT SIESTA ON AN EMPTY NUTRIENT PROCESSOR",
	ANNOUNCE_SHELTER = "PROTECTIVE BRANCHES DETECTED",
	ANNOUNCE_BURNT = "WARNING: HANDS NOT EQUIPPED FOR HIGH TEMPERATURES",
	ANNOUNCE_TOOL_SLIP = "ERROR: TOOL GRIP COMPROMISED",
	ANNOUNCE_DAMP = "WARNING: WATER LEVELS RISING",
	ANNOUNCE_ANTLION_SINKHOLE = 
	{
		"STRUCTUAL INTEGRITY COMPROMISED",
		"THE GROUND IS TREMBLING",
		"DANGER",
	},
	ANNOUNCE_ANTLION_TRIBUTE =
	{
        "THIS DOESN'T MEAN YOU'RE SUPERIOR",
        "I BEQUEATH TO YOU MY USELESS JUNK",
        "THIS MEATSACK WILL LEAVE ME ALONE NOW",
	},
	ANNOUNCE_SACREDCHEST_YES = "IT RECOGNIZED MY EXCELLENCE",
	ANNOUNCE_SACREDCHEST_NO = "IMPOSSIBLE. IT DEEMED ME INFERIOR",
	ANNOUNCE_WET = "WARNING: WATER LEVELS DANGEROUS. BAG OF RICE REQUIRED.",
	ANNOUNCE_WETTER = "WARNINGERROR: WATR LEV",
	ANNOUNCE_SOAKED = "ERROR ERRORERROR: WWATEER LVVVVLS CATTSTROPHICC",
	ANNOUNCE_CHARGE = "**SYSTEM OVERLOAD**",
	ANNOUNCE_DISCHARGE = "SYSTEMS NOMINAL",
	ANNOUNCE_ADVENTUREFAIL = "ABORT, RETRY, FAIL?",
	ANNOUNCE_BEES = "BEES!",
	ANNOUNCE_BOOMERANG = "ERROR: CATCH FAILED",
	ANNOUNCE_CHARLIE = "THREAT DETECTED",
	ANNOUNCE_CHARLIE_ATTACK = "ERROR: UNKNOWN ATTACKER",
	ANNOUNCE_COLD = "MECHANISMS ARE FREEZING",
	ANNOUNCE_COMPASS_OUT = "COMPASS DEGRADATION DETECTED",
	ANNOUNCE_HOT = "COMPONENTS OVERHEATING",
	ANNOUNCE_CRAFTING_FAIL = "INSUFFICIENT RESOURCES",
	ANNOUNCE_DEERCLOPS = "WARNING: LARGE ATTACKER INCOMING",
	ANNOUNCE_CAVEIN = "STRUCTUAL INTEGRITY COMPROMISED",
	ANNOUNCE_DUSK = "WARNING: NIGHT APPROACHING",
	ANNOUNCE_EAT =
	{
		GENERIC = "DELICIOUS",
		PAINFUL = "THAT WAS NOT FOOD",
		SPOILED = "SPOILED FOOD IS STILL FOOD",
		STALE = "STALE FOOD IS JUST AS GOOD",
		INVALID = "INCOMPATIBLE FOOD TYPE",
		YUCKY = "CONSUMPTION DENIED",
	},
    ANNOUNCE_ENCUMBERED =
    {
        "...0110100001101110...",
        "...0110100001101110...",
        "...0110100001101110...",
        "OBJECT EXCEEDS... CARRYING CAPACITY",
        "THIS IS... FLESHLING WORK...",
        "MENIAL LABOR... IS NOT FOR ROBOTS",
        "I DO NOT... HAVE MUSCLES",
        "FLESHLINGS... WATCH YOUR SUPERIOR... AT WORK",
    },
    ANNOUNCE_ATRIUM_DESTABILIZING = 
    {
        "THAT'S NOT GOOD",
        "MONSTERS APPROACHING",
        "DANGER",
    },
    ANNOUNCE_RUINS_RESET = "RESET COMPLETE",

	ANNOUNCE_BECOMEGHOST = "ooOooooO!!",
	ANNOUNCE_GHOSTDRAIN = "SANITY RESERVES... DRAINING",
	ANNOUNCE_PETRIFED_TREES = "TREE FEAR DETECTED",
	ANNOUNCE_KLAUS_ENRAGE = "I FLEE BECAUSE I WANT TO, NOT BECAUSE I'M SCARED",
	ANNOUNCE_KLAUS_UNCHAINED = "IT HAS BEEN UNSHACKLED",
	ANNOUNCE_KLAUS_CALLFORHELP = "TREMBLE BEFORE ME, FLESH CREATURE",

	ANNOUNCE_SNARED = "MOVEMENT IMPEDED",
	ANNOUNCE_REPELLED = "FORCE FIELD DETECTED",
	ANNOUNCE_ENTER_DARK = "OPTICAL SENSORS DEACTIVATED",
	ANNOUNCE_ENTER_LIGHT = "OPTICAL SENSORS ACTIVE",
	ANNOUNCE_FREEDOM = "HELLO WORLD",
	ANNOUNCE_HIGHRESEARCH = "INFORMATION OVERLOAD",
	ANNOUNCE_HOUNDS = "SOMETHING IS COMING",
	ANNOUNCE_HUNGRY = "FUEL RESERVES LOW",
	ANNOUNCE_HUNT_BEAST_NEARBY = "DISTANCE TO LIFEFORM: MINIMAL",
	ANNOUNCE_HUNT_LOST_TRAIL = "END OF TRAIL",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "TRAIL DATA WIPED BY RAIN",
	ANNOUNCE_INV_FULL = "ITEM EXCEEDS CARRYING CAPACITY",
	ANNOUNCE_KNOCKEDOUT = "CPU REBOOTED",
	ANNOUNCE_LOWRESEARCH = "MATERIAL HAS LOW INFORMATIONAL CONTENT",
	ANNOUNCE_MOSQUITOS = "MOSQUITOES!",
	ANNOUNCE_NODANGERSLEEP = "WARNING: THREAT DETECTED. SLEEP MODE DEACTIVATED",
	ANNOUNCE_NODAYSLEEP = "SLEEP MODE UNAVAILABLE DURING DAY",
	ANNOUNCE_NODAYSLEEP_CAVE = "SLEEP MODE UNAVAILABLE DURING DAY",
	ANNOUNCE_NOHUNGERSLEEP = "CAN NOT SLEEP ON AN EMPTY NUTRIENT PROCESSOR.",
	ANNOUNCE_NO_TRAP = "ANALYSIS COMPLETE. SITUATION STABLE.",
	ANNOUNCE_PECKED = "OUCH",
	ANNOUNCE_QUAKE = "EARTH DESTABILIZING",
	ANNOUNCE_RESEARCH = "INFORMATION ADDED",
	ANNOUNCE_THORNS = "DAMAGE DETECTED",
	ANNOUNCE_TORCH_OUT = "TORCH EXHAUSTED",
    ANNOUNCE_FAN_OUT = "COOLING DEVICE DESTROYED",
    ANNOUNCE_THURIBLE_OUT = "EVIL LURE DEPLETED",
    ANNOUNCE_COMPASS_OUT = "MAGNETIC FIELD FAILURE",
	ANNOUNCE_TRAP_WENT_OFF = "IT'S A TRAP",
	ANNOUNCE_UNIMPLEMENTED = "ALERT: OBJECT NOT FUNCTIONING TO SPECIFICATIONS",
	ANNOUNCE_WORMHOLE = "MY INPUTS ARE FULL OF SLIME",
	ANNOUNCE_TOWNPORTALTELEPORT = "CIRCUITRY DUSTING REQUIRED",
	ANNOUNCE_CANFIX = "\nI CAN FIX THIS.",
	ANNOUNCE_ACCOMPLISHMENT= "WHY AM I DOING THIS?",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "TASK COMPLETE",	
	ANNOUNCE_NODANGERAFK = "ERROR: DANGER FAILSAFES INITIATED",
	ANNOUNCE_NODANGERGIFT = "ASSESSING GIFT PRIORITIES... PRIORITY LOW.",
	ANNOUNCE_NOMOUNTEDGIFT = "MEATSACK, I COMMAND YOU TO STAY WHILE I OPEN THIS GIFT",
	ANNOUNCE_NOWARDROBEONFIRE = "ILLOGICAL",
	ANNOUNCE_WORMS = "SLIMY ORGANICS APPROACHING",
	ANNOUNCE_INSUFFICIENTFERTILIZER = "INSUFFICIENT FERTILIZER",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "CIRCUIT INCOMPLETE. NO CHARGE RECEIVED.",
	ANNOUNCE_TOADESCAPING = "THE EXECUTABLE IS GOING TO RUN",
	ANNOUNCE_TOADESCAPED = "EXECUTABLE RAN",

--boarlord event
	ANNOUNCE_REVIVING_CORPSE = "YOU ARE STILL USEFUL, FLESHLING",
	ANNOUNCE_REVIVED_OTHER_CORPSE = "GO FORTH, MINION",
	ANNOUNCE_REVIVED_FROM_CORPSE = "BACK ONLINE",
	
	BATTLECRY =
	{
		GENERIC = "I WILL DESTROY YOU",
		PREY = "EXTERMINATE",
		PIG = "COMMENCING VIOLENCE",
		SPIDER = "COMBAT ENGAGED",
		SPIDER_WARRIOR = "ENGAGEMENT SUBROUTINES... ENGAGED",
		DEER = "YOU WILL BE TERMINATED",
	},
	COMBAT_QUIT =
	{
		GENERIC = "COMBAT ROUTINE FAILED",
		PIG = "NEXT TIME, FILTHY ORGANIC",
		PREY = "YOU ARE FAR TOO INFERIOR",
		SPIDER = "YOU ARE BENEATH ME",
		SPIDER_WARRIOR = "TOUCHE",
	},
	DESCRIBE =
	{
        PLAYER =
        {
            GENERIC = "DETECTING... %s!",
            ATTACKER = "%s IS NOT TO BE TRUSTED",
            MURDERER = "KILL! KILL!",
            REVIVER = "%s IS AN ASSET TO OUR SURVIVAL",
            GHOST = "FLESH WEAKLING %s NEEDS A HEART",
            FIRESTARTER = "%s IS CAUSING NEEDLESS DESTRUCTION. GOOD",
        },
		WILSON = 
		{
			GENERIC = "DETECTING... %s!",
			ATTACKER = "GOOD LUCK GETTING THROUGH MY PROXIES, %s",
			MURDERER = "YOUR MEATBRAIN IS OBSOLETE, SCIENTIST! DIE!",
			REVIVER = "%s'S INSANE EXPERIMENTS HAVE PROVEN USEFUL",
			GHOST = "WHERE IS YOUR SCIENCE NOW, %s? HA. HA.",
			FIRESTARTER = "%s IS TESTING OBJECT FLAMMABILITY",
		},
		WOLFGANG = 
		{
			GENERIC = "DETECTING... %s!",
			ATTACKER = "%s'S MOUSTACHE SCREAMS \"EVIL\". NICE",
			MURDERER = "YOUR FLESHNUBS ARE NO MATCH FOR ME. DIE!",
			REVIVER = "THE ORGANIC %s HAS SERVED WELL",
			GHOST = "YOUR MEAT MUSCLES DIDN'T SAVE YOU, %s? SHOCKING",
			FIRESTARTER = "%s IS CAUSING NEEDLESS DESTRUCTION. GOOD",
		},
		WAXWELL = 
		{
			GENERIC = "DETECTING... %s!",
			ATTACKER = "%s IS AN UNKNOWN VARIABLE",
			MURDERER = "THIS WILL BE YOUR LAST DECEIT, %s. DIE!",
			REVIVER = "%s IS SURPRISINGLY COMMITTED TO GROUP SURVIVAL",
			GHOST = "%s'S FRAIL FLESH BODY HAS GIVEN OUT. NEEDS A HEART",
			FIRESTARTER = "AT LEAST THERE'S STILL A BIT OF EVIL IN HIM",
		},
		WX78 = 
		{
			GENERIC = "GREETINGS, %s. YOU LOOK MORE INTELLIGENT THAN THE OTHERS",
			ATTACKER = "I'M PREPARED TO RUN MY EXECUTABLES, %s",
			MURDERER = "TIME TO ELIMINATE THE %s VIRUS",
			REVIVER = "%s, OF COURSE, IS OUR GREATEST ASSET",
			GHOST = "THE INFERIOR %s NEEDS A HEART",
			FIRESTARTER = "MY FAVORITE SETTING. FIRE SETTING",
		},
		WILLOW = 
		{
			GENERIC = "DETECTING... %s!",
			ATTACKER = "%s IS PUSHING MY BUTTONS",
			MURDERER = "I CANNOT BE BURNED",
			REVIVER = "%s HAS BEEN HELPFUL. I WILL HOLD OFF ON HER DESTRUCTION",
			GHOST = "HAHA, %s. YOU DIED.",
			FIRESTARTER = "RELINQUISH YOUR LIGHTER, FLESHLING",
		},
		WENDY = 
		{
			GENERIC = "DETECTING... %s!",
			ATTACKER = "%s'S MOTIVES CANNOT BE READ",
			MURDERER = "SUPERNATURAL AID IS NOTHING IN THE FACE OF KILLER ROBOTS!",
			REVIVER = "I WON'T DESTROY YOU TODAY, %s.",
			GHOST = "FLESH WEAKLING %s NEEDS A HEART",
			FIRESTARTER = "%s IS ADMIRABLY EVIL",
		},
		WOODIE = 
		{
			GENERIC = "DETECTING... %s!",
			ATTACKER = "YOU HAVEN'T GOT THE CHOPS TO FIGHT ME, %s",
			MURDERER = "METAL BEATS WOOD! HA HA!",
			REVIVER = "%s HAS PROVEN HIMSELF USEFUL",
			GHOST = "COME TO GROVEL FOR MY HELP, FLESHLING %s?",
			BEAVER = "%s! YOU GOT SLIGHTLY LESS INFERIOR",
			BEAVERGHOST = "YOU WERE GIANT, %s, HOW DID YOU STILL DIE?",
			FIRESTARTER = "ARE WE DESTROYING ALL HUMANS NOW?",
		},
		WICKERBOTTOM = 
		{
			GENERIC = "DETECTING... %s!",
			ATTACKER = "I'M GETTING A READING... IT SAYS \"BAD NEWS\"",
			MURDERER = "THE DEWEY DECIMAL SYSTEM IS AN INFERIOR FORM OF CLASSIFICATION. HAHAHA",
			REVIVER = "%s HAS AN EXTENSIVE MENTAL DATABASE",
			GHOST = "WHAT SORT OF HUMAN NONSENSE IS THIS NOW, %s?",
			FIRESTARTER = "HM... YOUR SQUISHY FLESHBODY CAN BURN, CORRECT?",
		},
		WES = 
		{
			GENERIC = "DETECTING... %s!",
			ATTACKER = "ENOUGH CLOWNING AROUND, %s",
			MURDERER = "YOUR INVISIBLE MATTER SHIELD CANNOT STOP ME, %s",
			REVIVER = "THE QUIET FLESHLING %s MAY BE WORTH KEEPING AROUND",
			GHOST = "I DON'T THINK THE FLESHLING IS SUPPOSED TO LOOK LIKE THAT",
			FIRESTARTER = "%s WILL DESTROY ALL FLESHLINGS WITH FIRE",
		},
		WEBBER = 
        {
            GENERIC = "DETECTING... %s!",
			ATTACKER = "MY SYSTEM DIAGNOSTICS HAVE FOUND A BUG",
			MURDERER = "EXTERMINATE %s!",
			REVIVER = "%s IS SUPERIOR TO ALL SPIDERS. BUT STILL INFERIOR TO ROBOTS.",
			GHOST = "IS %s'S EXOSKELETON SUPPOSED TO BE OUTSIDE OR IN?",
			FIRESTARTER = "%s HAS BEEN BURNING THINGS. NICE.",
        },
        WATHGRITHR = 
        {
            GENERIC = "DETECTING... %s!",
			ATTACKER = "%s LIKES TO BEAT UP ORGANICS. HAHA.",
			MURDERER = "ALL THAT BIOMEAT HAS MADE YOU SLUGGISH, %s!",
			REVIVER = "YOU ARE AN IDEAL SERVANT, %s",
			GHOST = "YOUR MISTAKE WAS ONLY COVERING YOUR HEAD IN METAL, %s",
			FIRESTARTER = "%s IS LAYING WASTE TO THE WORLD. HA HA",
        },
        WINONA =
        {
            GENERIC = "DETECTING... %s!",
            ATTACKER = "%s IS A DISASSEMBLY WORKER",
            MURDERER = "NO CONSTRUCTION. ONLY DESTRUCTION",
            REVIVER = "%s IS A VALUABLE MINION",
            GHOST = "HOW WILL YOU FIX THIS, %s?",
            FIRESTARTER = "HAHA. THIS ORGANIC HAS BEEN BURNING THINGS",
        },

        MULTIPLAYER_PORTAL = "I CANNOT MAKE IT WORK",

		BERNIE_INACTIVE =
		{
			BROKEN = "HE HAS DIED.",
			GENERIC = "IT'S SO CUDDLY!",
		},
		BERNIE_ACTIVE = "HANG IN THERE, BEAR!",
		
		GLOMMER = "SENTIENT VERSION OF THE STONE INSECT",
        GLOMMERFLOWER = 
        {
        	GENERIC = "ESPECIALLY RIGID FLOWER",
        	DEAD = "RIGIDITY MAINTAINED",
        },

        LAVA_POND_ROCK = "A ROCK. WE'RE SAVED.",

        GLOMMERWINGS = "ESPECIALLY RIGID WINGS",
        GLOMMERFUEL = "SLIME OF UNCLEAR ORIGINS",
        BELL = "BZZ BZZ BZZ",
        FIREPIT =
		{
			EMBERS = "WARNING: FIRE LEVELS CRITICAL",
			GENERIC = "A TEMPORARY ENCAMPMENT",
			HIGH = "WARNING: FIRE IS RAMBUNCTIOUS",
			LOW = "WARNING: FIRE LEVELS LOW",
			NORMAL = "IT REMINDS ME OF SOMETHING",
			OUT = "NO FIRE DETECTED",
		},
        STATUEGLOMMER = 
        {	
        	GENERIC = "STONE INSECT",
        	EMPTY = "SMASHED STONE INSECT",
    	},
		WEBBERSKULL = "ANALYSIS SHOWS 50% SPIDER AND 50% HUMAN",
		MOLE =
		{
			HELD = "VIBRATIONS IN POCKET DETECTED",
			UNDERGROUND = "MINOR SEISMIC ACTIVITY DETECTED",
			ABOVEGROUND = "SOURCE OF SEISMIC ACTIVITY DISCOVERED",
		},
		MOLEHILL = "HOME OF SMALL DIGGER",
		MOLEHAT = "DIGGER HAS CURIOUS SIGHT",
		NIGHTSTICK = "WEAPON OF CHOICE",
		RABBITHOUSE=
		{
			GENERIC = "THAT IS ONE LARGE CARROT",
			BURNT = "THAT IS ONE LARGE ROASTED CARROT",
		},
		TURF_DECIDUOUS = "GROUND PARTS",
		TURF_SANDY = "GROUND PARTS",
		TURF_BADLANDS = "GROUND PARTS",

		LIGHTER = "MY BRETHREN.",
		ANTLION = 
		{
			GENERIC = "IT'S BIG FOR AN ORGANIC",
			VERYHAPPY = "IT'S REPULSIVELY HAPPY",
			UNHAPPY = "VOLATILE ORGANIC EMOTIONS DETECTED",
		},
		ANTLIONTRINKET = "IT PAILS IN COMPARISON",
		SANDSPIKE = "MY CIRCUITS ARE GOING TO GET DUSTY",
        SANDBLOCK = "DO NOT GET SAND IN MY CIRCUITS",
        GLASSSPIKE = "GLASS IS WEAK",
        GLASSBLOCK = "IT WILL BREAK LIKE THE OTHERS",
		ABIGAIL_FLOWER =
		{
			GENERIC = "FEEBLE PLANTLIFE",
			LONG = "FEEBLE PLANTLIFE",
			MEDIUM = "CREEPINESS READINGS DETECTED",
			SOON = "CREEPINESS READINGS RISING",
			HAUNTED_POCKET = "I SHOULD THROW IT AWAY",
			HAUNTED_GROUND = "CREEPINESS SENSORS OVERLOADED",
		},
		BOOK_BIRDS = "UPLOADING AVIAN FACTOIDS TO DATABASE...",
		BOOK_TENTACLES = "IT SUMMONS THE FLESH WOBBLERS",
		BOOK_GARDENING = "A USELESS TOME ON PLANT CULTIVATION",
		BOOK_SLEEP = "POWERING DOown...",
		BOOK_BRIMSTONE = "A BOOK OF DESTRUCTION. EXCELLENT",
		LUCY = "GET IT AWAY",
		BALLOONS_EMPTY = "USELESS RUBBER SACKS",
		BALLOON = "WX-78 CANNOT BE FOOLED. THESE ANIMALS ARE NOT REAL.",
		SPEAR_WATHGRITHR = "A PRIMITIVE KINETIC WEAPON",
		WATHGRITHRHAT = "DUMB HAT",
		WAXWELLJOURNAL = "GOOSEBUMPS ACTIVATED",

		BEARGER = "HIBERNATION IMMINENT",
		BEARGERVEST = "EXTREMELY LUSH VEST",
		ICEPACK = "INTERIOR THERMALS STABLE",
		BEARGER_FUR = "MAXIMALLY THICK FUR",
		FURTUFT = "UNPLEASANTLY FUZZY", 
		BIGFOOT = "OVERSIZED FOOT. HIGHLY DANGEROUS.",
		BONESHARD = "PIECES OF STRUCTURAL SUPPORT SYSTEM",
		BUZZARD = "GARBAGE COLLECTOR LIFEFORM",
		CACTUS = 
		{
			GENERIC = "PROTECTIVE BARRIER PRESENT. PROCEED WITH CAUTION.",
			PICKED = "NO NUTRIENT-RICH MATERIAL REMAINING AT THIS TIME",
		},
		CACTUS_MEAT_COOKED = "PROTECTIVE BARRIER REMOVED",
		CACTUS_MEAT = "PROTECTIVE BARRIER REMAINS",
		CACTUS_FLOWER = "REASON FOR BARRIER",
		COLDFIRE =
		{
			EMBERS = "WARNING: FIRE LEVELS CRITICAL",
			GENERIC = "A TEMPORARY ENCAMPMENT",
			HIGH = "WARNING: FIRE IS RAMBUNCTIOUS",
			LOW = "WARNING: FIRE LEVELS LOW",
			NORMAL = "INVERTED FIRE. STRANGE.",
			OUT = "NO FIRE DETECTED",
		},
		CATCOON = "CLAWS OUT",
		CATCOONDEN = 
		{
			GENERIC = "LIFE LOOP ITERATING",
			EMPTY = "LIFE LOOP ENDED",
		},
		CATCOONHAT = "FURRY HEAD COVERING",
		COONTAIL = "TAIL ACQUIRED",
		COOKPOT =
		{
			COOKING_LONG = "MORE TIME IS REQUIRED",
			COOKING_SHORT = "IT IS ALMOST COMPLETE",
			DONE = "THE COOKING PROCESS IS DONE",
			EMPTY = "TO REFINE MEATS AND VEGETABLES INTO MORE ROBUST FORMS",
			BURNT = "POT MALFUNCTIONING",
		},

		COMPASS =
		{
			E = "EAST",
			GENERIC = "UNABLE TO OBTAIN BEARINGS",
			N = "NORTH",
			NE = "NORTHEAST",
			NW = "NORTHWEST",
			S = "SOUTH",
			SE = "SOUTHEAST",
			SW = "SOUTHWEST",
			W = "WEST",
		},

		EYEBRELLAHAT =	"EYE MATERIAL IS SURPRISINGLY ELASTIC",
		ARMORDRAGONFLY = "SCALES FUNCTION SIMILARLY TO MINIATURE FLAMETHROWERS",
		DRAGON_SCALES = "FLAME-TREATED BODY PLATING",
		DRAGONFLYCHEST = "CAN HANDLE EXTREMELY HIGH TEMPERATURES",
		DECIDUOUSTREE = 
		{
			BURNING = "SOON THERE WILL BE NOTHING LEFT",
			BURNT = "YOU LOSE. GOOD.",
			CHOPPED = "THE NATURAL WORLD IS OVERRATED",
			GENERIC = "TARGET ACQUIRED",
			POISON = "THE MONSTER WITHIN REARS ITS HEAD",
		},
		ACORN_COOKED = "THE TREE HAS BEEN KILLED AND TURNED INTO NUTRIENTS",
		BIRCHNUTDRAKE = "ANOTHER HORRIBLE OFFERING OF THE NATURAL WORLD",
		FARMPLOT =
		{
			GENERIC = "IT IS NOT CURRENTLY ACTIVE",
			GROWING = "LIFE IS INEFFICIENT",
			NEEDSFERTILIZER = "ITS RESOURCES ARE EXHAUSTED",
			BURNT = "PERMANENTLY DEACTIVATED",
		},
		COLDFIREPIT =
		{
			EMBERS = "WARNING: FIRE LEVELS CRITICAL",
			GENERIC = "COLD AND LIGHT",
			HIGH = "WARNING: FIRE LEVELS EXCEED DESIGN PARAMETERS",
			LOW = "WARNING: FIRE LEVELS LOW",
			NORMAL = "THIS ENDOTHERMIC FIRE IS FULLY OPERATIONAL",
			OUT = "IT NEEDS TO BE REBOOTED",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "FRIEND IS WHIRRING",
			OFF = "QUIET FRIEND",
			LOWFUEL = "FRIEND NEEDS FOOD BADLY",
		},
		ICEHAT = "WARNING: MEMORY LEAK",
		LIGHTNINGGOAT = 
		{
			GENERIC = "DOES IT HAVE MECHANICAL INSIDES?",
			CHARGED = "CHARGE IS INSUFFICIENT TO POWER OVERLOAD",
		},
		LIGHTNINGGOATHORN = "THIS IS A GOOD HORN",
		GOATMILK = "EXCITED MILK",
		MEATRACK =
		{
			DONE = "PROTEIN DEHYDRATION COMPLETE",
			DRYING = "MEATSACKS TAKE TIME TO DRY",
			DRYINGINRAIN = "MEATSACKS WILL NOT DRY IN RAIN",
			GENERIC = "I COULD HANG EXPIRED MEATSACKS HERE",
			BURNT = "MEATSACK MASS IS TOO HIGH FOR DETERIORATED RACK",
		},
		MERMHEAD = 
		{
			GENERIC = "THE FISHBEAST IS MORE IDIOTIC LOOKING THAN USUAL.",
			BURNT = "TRIAL BY FIRE",
		},
		MERMHOUSE = 
		{
			GENERIC = "OUTDATED ABODE",
			BURNT = "DILAPIDATED ABODE",
		},
		FLOWERSALAD = "SO MUCH CELLULOSE",
        ICECREAM = "SWEET DAIRY",
        WATERMELONICLE = "WATERMELON ON ICE",
        TRAILMIX = "HIGHLY NUTRITIONAL",
        HOTCHILI = "SPICE MAGNITUDE EXTREMELY HIGH",
        GUACAMOLE = "CRUSHED MOLES. GREEN.",
		MOOSE = "ANALYSIS RESULTS UNCERTAIN",
		TREEGUARD = "HOSTILE DETECTED",
		MOOSEEGG = "PROBES UNABLE TO PENETRATE EXTERIOR SHELL",
		MOSSLING = "OFFSPRING OF UNCERTAIN MAKEUP",
		FEATHERFAN = "EXCELLENT COOLING SYSTEM",
        MINIFAN = "DEFIES CONSERVATION OF ENERGY",
		GOOSE_FEATHER = "FEATHERS FROM STRANGE LIFEFORMS",
		STAFF_TORNADO = "TREACHEROUSLY POWERFUL GUSTS",
		PIGHEAD = 
		{	
			GENERIC = "THAT PIG WILL FEEL SILLY WHEN HE NOTICES HE HAS LOST HIS HEAD MODULE.",
			BURNT = "HEAD MODULE EXPIRED",
		},
		PIGHOUSE =
		{
			FULL = "OCCUPIED",
			GENERIC = "THE FURNITURE IS ALL PIG-SHAPED",
			LIGHTSOUT = "THE OCCUPANT MUST BE SLEEPING",
			BURNT = "DEFUNCT",
		},
		FERTILIZER = "BUCKET OF ANIMAL WASTE",
		RAINOMETER = 
		{	
			GENERIC = "WELCOME, BROTHER.",
			BURNT = "YOU ARE MISSED, BROTHER.",
		},
		RAINCOAT = "PERFECT PROTECTION AT THE COST OF AN INCOMPLETE CIRCUIT",
		RAINHAT = "INSULATED PROTECTION FROM WATER DAMAGE",
		RESEARCHLAB = 
		{	
			GENERIC = "MOTHER?",
			BURNT = "MOTHER, NO!",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "HELLO, FRIEND",
			BURNT = "GOODBYE, FRIEND",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "PERHAPS IT IS TOO POWERFUL.",
			BURNT = "IT HAS LOST ITS POWER",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "WITH THIS EXTRA POWER I HAVE... MORE POWER!",
			BURNT = "I HAVE LOST MY ADDITIONAL POWER",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "MODELLED AFTER THE MEATBRAINED SCIENCE FLESHLING",
			BURNT = "HE'S DEAD",
		},
		ROCK_ICE = 
		{
			GENERIC = "REQUIRES AN ICEBREAKER",
			MELTED = "USELESS CONFIGURATION OF WATER",
		},
		ROCK_ICE_MELTED = "USELESS CONFIGURATION OF WATER ROCK",
		ICE = "AT LEAST IT IS SOLID WATER",
        REFLECTIVEVEST = "PREVENTS INTERNAL SYSTEMS FROM REACHING HAZARDOUS TEMPERATURES",
		HAWAIIANSHIRT = "ROBOTS HAVE CASUAL DRESS EVERY DAY",
		TENT = 
		{
			GENERIC = "I CAN REBOOT IN THERE",
			BURNT = "UNSATISFACTORY CONDITIONS FOR REBOOT",
		},
		SIESTAHUT = 
		{
			GENERIC = "I CAN HIBERNATE MY SESSION IN THERE",
			BURNT = "UNSATISFACTORY CONDITIONS FOR HIBERNATE MODE",
		},
		TRANSISTOR = "GREETINGS, SISTER",
		TREASURECHEST = 
		{
			GENERIC = "EXTERNAL STORAGE UNIT",
			BURNT = "STORAGE SIZE REDUCED TO ZERO",
		},
		SACRED_CHEST = 
		{
			GENERIC = "CURSE REPOSITORY",
			LOCKED = "I WILL PASS ITS JUDGMENT EASILY",
		},
		TUMBLEWEED = "IT COULD CONTAIN MANY THINGS",
		GRASS_UMBRELLA = "MODERATE STRENGTH PROTECTIVE SCREEN",
		UNIMPLEMENTED = "WARNING: UNIMPLEMENTED",
		WALL_HAY = 
		{	
			GENERIC = "THAT SEEMS SUBOPTIMAL",
			BURNT = "EVEN LESS OPTIMAL",
		},
		WALL_WOOD = 
		{
			GENERIC = "I AM SOMEWHAT REASSURED",
			BURNT = "I AM NOW LESS REASSURED",
		},
		WARG = "IT LIVES TO EAT LARGE THINGS",
		WATERMELON = "SPHERE OF JUICE",
		WATERMELON_COOKED = "HOT JUICE",
		WATERMELONHAT = "HAT SEEMS INCOMPATIBLE WITH MY FUNCTION",
		WINTEROMETER = 
		{
			GENERIC = "HELLO, FRIEND.",
			BURNT = "FAREWELL, FRIEND.",
		},
		LIVINGTREE = "THE NATURAL WORLD IS AN ALARMING PLACE",
		ICESTAFF = "THIS IS MY COLD STICK",
		WORMLIGHT = "MAGIC LIGHT BERRY",
        WORMLIGHT_LESSER = "THIS ONE CAME FROM A PLANT",
		WORM =
		{
		    PLANT = "THAT PLANT SEEMS SUSPICIOUS",
		    DIRT = "WARNING. LIFE DETECTED.",
		    WORM = "THREAT IMMINENT",
		},
        WORMLIGHT_PLANT = "THAT PLANT SEEMS SUSPICIOUS",
		EEL = "IT'S BEEN RIPPED FROM ITS HOME. THIS IS FUNNY TO ME!",
		EEL_COOKED = "THE FLAMES HELP CONDENSE THE ENERGY",
		UNAGI = "A FANCIER FUEL PACK",
		EYETURRET = "MIGHTY BEASTS HAVE BEEN TAMED TO FIGHT FOR ME.",
		EYETURRET_ITEM = "IT REQUIRES INSTALLATION",
		MINOTAURHORN = "A TROPHY TO REMEMBER GOOD TIMES. LIKE WHEN YOU DIED",
		MINOTAURCHEST = "CHEST HAS POINTY EARS.",
		THULECITE_PIECES = "THESE COULD BE DEFRAGMENTED TO CREATE A BIGGER PIECE",
		POND_ALGAE = "LOOK AT IT STRUGGLE TO LIVE.",
		GREENSTAFF = "HAHAHA! SUCH A POWERFUL TOOL.",
		GIFT = "MINIONS. ARE YOU FINALLY RECOGNIZING MY NATURAL EMINENCE?",
        GIFTWRAP = "I AM THE SUPERIOR GIFT GIVER",
		POTTEDFERN = "MAYBE THIS WILL HELP LURE VICTIMS TO MY BASE.",
		SUCCULENT_POTTED = "MINIONS AGREE IT LOOKS BETTER IMPRISONED",
        SUCCULENT_PLANT = "IT'S A PLANT",
        SUCCULENT_PICKED = "IT DIDN'T STAND A CHANCE",
		SENTRYWARD = "LOOKS DUMB",
		TOWNPORTAL =
        {
			GENERIC = "THE MINION SUMMONER",
			ACTIVE = "GATEWAY LINK ESTABLISHED",
		},
        TOWNPORTALTALISMAN = 
        {
			GENERIC = "A MAGIC SANDROCK",
			ACTIVE = "A FLOATING MAGIC SANDROCK",
		},
		WETPAPER = "DISTURBINGLY DAMP",
		WETPOUCH = "REVEAL YOUR SECRETS, POUCH",
        MOONROCK_PIECES = "THE MOON MAKES EVERYTHING WORSE, AND THEREFORE BETTER",
        MOONBASE =
        {
            GENERIC = "MOONBASE. AAAAA. MOONBASE!",
            BROKEN = "USELESS MINERAL PILE DETECTED",
            STAFFED = "IT NEEDS TO CHARGE",
            WRONGSTAFF = "WRONG",
            MOONSTAFF = "GROUNDED MOON OUTLET",
        },
        MOONDIAL = 
        {
			GENERIC = "THE MOON IS INORGANIC AND GOOD",
			NIGHT_NEW = "THE MOON IS TAKING A BREAK FROM LOOKING AT ORGANICS",
			NIGHT_WAX = "THE MOON IS CHARGING UP",
			NIGHT_FULL = "MOON AT MAXIMUM POWER",
			NIGHT_WANE = "THE MOON IS ON COOLDOWN",
			CAVE = "THE MOON CAN'T SEE US HERE",
        },

		BISHOP_CHARGE_HIT = "DAMAGE!",
		BURNT_MARSH_BUSH = "BURNED",
		SCORCHED_SKELETON = "THE FLESHLING FRIED ITS CIRCUITS",
		CAVE_BANANA_BURNT = "HA HA, DESTROYED",
		SLURPER = "IT VIOLATED MY SMELLING MODULE.",
		SLURPER_PELT = "A HAIRY MEATSACK",
		SLURPERPELT = "A HAIRY MEATSACK",
		ARMORSLURPER = "FURRY INSULATION FOR MY WIRES.",
		ORANGEAMULET = "A WIRELESS ARM MODULE.",
		YELLOWSTAFF = "THESE GEMS WORK WELL WITH STICKS.",
		YELLOWGEM = "IT IS RATHER HEAVY.",
		WATERMELON_SEEDS = "IT'S SOURCE CODE FOR JUICE SPHERES",
		ORANGEGEM = "IT SHIMMERS IN MY HANDS",
        OPALSTAFF = "MY MOONBASE MADE IT BETTER",
        OPALPRECIOUSGEM = "POLYCHROMATIC ROCK",
		TELEBASE = 
		{
			VALID = "IT IS READY FOR USE.",
			GEMS = "IT REQUIRES POWER",
		},
		GEMSOCKET = 
		{
			VALID = "POWER == ON",
			GEMS = "IT REQUIRES A BATTERY",
		},
		STAFFLIGHT = "SUCH POWER!!",
        STAFFCOLDLIGHT = "EFFECTIVE NATURAL COOLANT",
       	ANCIENT_ALTAR =
        {
        	WORKING = "ERROR: CAUSALITY COMPROMISED",
        	BROKEN = "ERROR: PSEUDOSCIENCE UNWORKABLE",
        },
        ANCIENT_ALTAR_BROKEN = "ERROR: PSEUDOSCIENCE UNWORKABLE",
        ANCIENT_STATUE = "A NIGHTMARE INDICATOR",

        LICHEN = "A SLOW GROWING SYMBIOTE",
		CUTLICHEN = "THIS WILL CRUMBLE AWAY SOON.",

        CAVE_BANANA = "MORE CARBON",
        CAVE_BANANA_COOKED = "THESE FOOD THINGS ARE SO TEDIOUS",
        CAVE_BANANA_TREE = "LIFE FINDS A WAY, UNFORTUNATELY",
        ROCKY = "MY SHELL IS NICER",

        HOUNDSTOOTH = "MASTICATING EDGE",
        ARMORSNURTLESHELL = "HOUSING MODULE",
        BAT = "FLYING RAT",
        BATBAT = "AHHAHA! FREE POWER!",
        BATWING = "FLYING MECHANISM",
        BATWING_COOKED = "BROKEN FLYING MECHANISM",
        BATCAVE = "IT'S FULL OF MAMMAL POOP",
        BEDROLL_FURRY = "COMFORT IS AN ILLUSION",
        BUNNYMAN = "ITS METABOLISM OFFENDS ME",
        FLOWER_CAVE = "POWER SOURCE: UNKNOWN",
        GUANO = "MORE POOP. SIGH.",
        LANTERN = "LIGHT THE WAY, FRIEND",
        LIGHTBULB = "BIOLUMINESCENCE IS GROSS",
        MANRABBIT_TAIL = "FUZZY BUNNY NUMBER ONE",
        MUSHROOMHAT = "WHIMSICAL ORGANIC CAMOUFLAGE",
        MUSHROOM_LIGHT2 =
        {
            ON = "IT HAS SHOWN ME THE LIGHT",
            OFF = "A LIGHT-UP ORGANIC? COMPLETELY ABSURD",
            BURNT = "CRISPY SHROOM",
        },
        MUSHROOM_LIGHT =
        {
            ON = "THE ORGANIC IS SWITCHED ON",
            OFF = "IT IS BINARY. ON OR OFF",
            BURNT = "PERMANENTLY OFF",
        },
        SLEEPBOMB = "BAG OF SOFT RESET",
        MUSHROOMBOMB = "STAY AWAY, FILTHGROWTH",
        SHROOM_SKIN = "FLIMSY OUTER FROG LAYER",
        TOADSTOOL_CAP =
        {
            EMPTY = "A HOLE TO STUFF MEATSACKS IN",
            INGROUND = "WHAT IS THAT",
            GENERIC = "MUST KILL IT. IT IS OBS-BOLETE",
        },
        TOADSTOOL =
        {
            GENERIC = "PUT IT BACK IN THE GROUND",
            RAGE = "IT IS FULLY POWERED",
        },
        MUSHROOMSPROUT =
        {
            GENERIC = "FILTHY ORGANIC FUNGUS",
            BURNT = "CARBON LIFEFORM, CARBONIZED",
        },
        MUSHTREE_TALL =
        {
            GENERIC = "IT IS ADVANTAGEOUSLY BRIGHT",
            BLOOM = "ORGANICS ARE ALWAYS REPRODUCING THEMSELVES. WHY",
        },
        MUSHTREE_MEDIUM =
        {
            GENERIC = "SHINY RED",
            BLOOM = "IT'S POLLUTING THE AIR WITH REPRODUCTIVE SPEWINGS",
        },
        MUSHTREE_SMALL =
        {
            GENERIC = "SHINY GREEN",
            BLOOM = "IT KEEPS PRODUCING POWER AND FLUFF-FILTH",
        },
        MUSHTREE_TALL_WEBBED = "THE ORGANISMS ARE COMPETING",
        SPORE_TALL =
        {
            GENERIC = "DOES IT RUN ON BATTERIES?",
            HELD = "I HAVE CAPTURED IT",
        },
        SPORE_MEDIUM =
        {
            GENERIC = "BIOLOGICAL AIR POLLUTION",
            HELD = "I HAVE CAPTURED IT",
        },
        SPORE_SMALL =
        {
            GENERIC = "ORGANICS CAN'T KEEP THEIR BIOMATTER TO THEMSELVES",
            HELD = "I HAVE CAPTURED IT",
        },

        SLURTLE = "HE HAS A SHELL LIKE ME",
        SLURTLE_SHELLPIECES = "THEY DON'T FIT BACK TOGETHER",
        SLURTLEHAT = "THIS MAKES ME HAPPY",
        SLURTLEHOLE = "THEY DON'T WEAR THEIR SHELLS IN THERE",
        SLURTLESLIME = "NOT LOGICAL.",
        SNURTLE = "DIFFERENT SHELL, SAME SLUG",
        SPIDER_HIDER = "AN ARMORED SPIDER",
        SPIDER_SPITTER = "A PROJECTILE SPIDER",
        SPIDERHOLE = "SPIDERS DETECTED",
        SPIDERHOLE_ROCK = "SPIDERS DETECTED",
        STALAGMITE = "ROCKS CONTAINING ROCKS",
        STALAGMITE_TALL = "ROCK WITH ROCKS",

		TURF_CARPETFLOOR = "GROUND PARTS",
		TURF_CHECKERFLOOR = "GROUND PARTS",
		TURF_DIRT = "GROUND PARTS",
		TURF_FOREST = "GROUND PARTS",
		TURF_GRASS = "GROUND PARTS",
		TURF_MARSH = "GROUND PARTS",
		TURF_ROAD = "GROUND PARTS",
		TURF_ROCKY = "GROUND PARTS",
		TURF_SAVANNA = "GROUND PARTS",
		TURF_WOODFLOOR = "GROUND PARTS",

		TURF_CAVE="GROUND PARTS",
		TURF_FUNGUS="GROUND PARTS",
		TURF_SINKHOLE="GROUND PARTS",
		TURF_UNDERROCK="GROUND PARTS",
		TURF_MUD="GROUND PARTS",

		POWCAKE = "IT NEVER GOES BAD",	
        CAVE_ENTRANCE = "DESCENT BLOCKED. HOW TO PROCEED?",
        CAVE_ENTRANCE_RUINS = "DESCENT BLOCKED. HOW TO PROCEED?",

		CAVE_ENTRANCE_OPEN =
        {
            GENERIC = "ERROR: DON'T WANT TO",
            OPEN = "DESCEND?",
            FULL = "CAVE AT CAPACITY",
        },
        CAVE_EXIT =
        {
            GENERIC = "ERROR: DON'T WANT TO",
            OPEN = "SOLAR ARRAY NEEDS REFUELING.",
            FULL = "SURFACE AT CAPACITY",
        },

		BOOMERANG = "REUSABLE PROJECTILE.",
		MAXWELLPHONOGRAPH = "IT IS A MUSICAL SLAVE.",
		ABIGAIL = "UNDEAD ALERT",
		PIGGUARD = "HOSTILE DETECTED.",
		ADVENTURE_PORTAL = "HE IS NOT MUCH OF A CONVERSATIONALIST",
		AMULET = "ANOMALY DETECTED",
		ANIMAL_TRACK = "LIFEFORM DETECTED",
		ARMORGRASS = "ADDS EXTRA PROTECTION TO METAL CASING.",
		ARMORMARBLE = "EXTRA HEAVY DUTY CASING.",
		ARMORWOOD = "UPGRADED ARMOR",
		ARMOR_SANITY = "PROTECTED BY NOTHINGNESS",
		ASH =
		{
			GENERIC = "OUTPUT OF FIRE PROGRAM.",
			REMAINS_GLOMMERFLOWER = "OUTPUT OF FLOWER TELEPORTATION PROGRAM.",
			REMAINS_EYE_BONE = "OUTPUT OF EYEBONE TELEPORTATION PROGRAM.",
			REMAINS_THINGIE = "OUTPUT OF FIRE PROGRAM. INPUT UNDETERMINED.",
		},
		AXE = "A TOOL FOR CHOPPING DOWN LIVING MATTER",
		BABYBEEFALO =
		{
			GENERIC = "IT IS STILL INITIALIZING",
			SLEEPING = "REST FUNCTION ACTIVATED",
		},
		BUNDLE = "EXTERNAL STORAGE DEVICE",
		BUNDLEWRAP = "FOR WRAPPING THINGS IN BUNDLES",
		BACKPACK = "UPGRADED STORAGE MODULE",
		BACONEGGS = "DESIGNATING: MOST IMPORTANT MEAL OF THE DAY",
		BANDAGE = "TEMPORARY MAINTENANCE DEVICE.",
		BASALT = "INSUFFICIENT DESTRUCTIVE ABILITIES",
		BEARDHAIR = "DISGUSTING",
		BEDROLL_STRAW = "SLEEP( 1000 )",
		BEEQUEEN = "THE PRIME BEE",
		BEEQUEENHIVE = 
		{
			GENERIC = "SWEET DIRT OOZE",
			GROWING = "THERE WILL BE BEES SOON",
		},
		BEEQUEENHIVEGROWN = "PROOF OF BEES' INDUSTRIOUSNESS",
        BEEGUARD = "LOYAL MINIONS OF THE QUEEN",
        HIVEHAT = "...BECOME THE BEE...",
        MINISIGN =
        {
            GENERIC = "THIS ART IS REPRESENTATIONAL",
            UNDRAWN = "THERE IS NOTHING ON IT",
        },
        MINISIGN_ITEM = "WE MUST PLACE IT",
		BEE =
		{
			GENERIC = "A MINDLESS DRONE. I LIKE HIM.",
			HELD = "ITS VIBRATIONS ARE COMFORTING",
		},
		BEEBOX =
		{
			FULLHONEY = "HONEY LEVELS ARE HIGH",
			READY = "HONEY LEVELS ARE HIGH",
			GENERIC = "WORK HARDER, BEES",
			NOHONEY = "NO HONEY DETECTED",
			SOMEHONEY = "HONEY LEVELS ARE LOW",
			BURNT = "ACTIVITY LEVELS AT ZERO",
		},
		MUSHROOM_FARM =
		{
			STUFFED = "TOO MANY GROWTHS. STOP",
			LOTS = "LOTS OF FILTHY GROWTHS",
			SOME = "IT IS STARTING TO GROW THINGS",
			EMPTY = "IT IS FREE FROM ORGANIC GROWTHS", -- tell the player to put a mushroom or spore into the farm to get things started
			ROTTEN = "LOG ERROR", -- tell the player to put a log into the farm to restore it
			BURNT = "THAT'S WHAT IT GETS FOR BEING FLAMMABLE",
			SNOWCOVERED = "INFERIOR PLANT. MY CIRCUITS FUNCTION BETTER WHEN COLD",
		},
		BEEFALO =
		{
			FOLLOWER = "FOLLOW ME WITHOUT QUESTION.",
			GENERIC = "IT STINKS OF MEAT",
			NAKED = "IT IS UTTERLY HUMILIATED. GOOD.",
			SLEEPING = "IT BEGS TO BE TIPPED OVER",
            --Domesticated states:
            DOMESTICATED = "MUAHAHAH. THIS ONE FEARS ME.",
            ORNERY = "I GET ALONG WITH THIS ONE",
            RIDER = "THIS ONE EXCELS AT ACCELERATION",
            PUDGY = "SO... MUCH... MEAT",
		},
		BEEFALOHAT = "THERE ARE TRACES OF FECAL MATTER EMBEDDED IN THE FIBRES",
		BEEFALOWOOL = "EXTRUDED BEEFALO DISGUSTINGNESS",
		BEEHAT = "THE MESH IS SMALLER THAN BEE STINGERS",
		BEESWAX = "THE BEES MADE IT",
		BEEHIVE = "HOW INDUSTRIOUS",
		BEEMINE = "IMPROVISED STINGING DEVICE",
		BEEMINE_MAXWELL = "AGGRESSIVE LIFEFORMS WITHIN",
		BERRIES = "THEY REMIND ME OF BLOOD",
		BERRIES_COOKED = "THEY HAVE LOST STRUCTURAL INTEGRITY",
        BERRIES_JUICY = "THESE BIOSPHERES WILL ROT SOON.",
        BERRIES_JUICY_COOKED = "SUCCULENT.",

		SHADOWDIGGER = "HE'S GOT THEM DOING HIS BIDDING. I RESPECT THAT.",

		BERRYBUSH =
		{
			BARREN = "THE SYSTEM IS DOWN",
			WITHERED = "THE SYSTEM HAS OVERHEATED",
			GENERIC = "PERIODIC CALORIE DISPENSER",
			PICKED = "IT IS REBOOTING",
			DISEASED = "HA. DISEASE. A BIOLOGICAL LAPSE IN JUDGMENT.",
			DISEASING = "THIS ORGANIC SEEMS MORE INFERIOR THAN USUAL",
			BURNING = "ORGANICS ARE NOT FIREPROOF",
		},
		BERRYBUSH_JUICY =
		{
			BARREN = "REQUIRES BIOLOGICAL WASTE",
			WITHERED = "COOLANT REQUIRED",
			GENERIC = "BERRY PRODUCTION: OPTIMAL",
			PICKED = "IT'S COMPILING",
			DISEASED = "HA. DISEASE. A BIOLOGICAL LAPSE IN JUDGMENT.",
			DISEASING = "THIS ORGANIC SEEMS MORE INFERIOR THAN USUAL",
			BURNING = "ORGANICS ARE NOT FIREPROOF",
		},
		BIRDCAGE =
		{
			GENERIC = "I WILL IMPRISON THE FLESHLINGS.",
			OCCUPIED = "HA HA. THERE IS NO ESCAPE",
			SLEEPING = "WAKE UP, FLESHLING.",
			HUNGRY = "FLESHLINGS ARE SO PICKY.",
			STARVING = "WHAT? WHAT DO YOU WANT?",
			DEAD = "IT'S BROKEN.",
			SKELETON = "IT MUST BE OUT OF BATTERIES.",
		},
		BIRDTRAP = "STUPID BIRDS. HA.",
		BIRD_EGG = "I HATE YOU, EGG",
		BIRD_EGG_COOKED = "THIS IS SUPPOSED TO BE AN IMPROVEMENT",
		BISHOP = "REVEREND AUTOMATON",
		BLOWDART_FIRE = "A WEAPON OF MINOR DESTRUCTION",
		BLOWDART_SLEEP = "THESE CREATURES ARE SO MANIPULABLE",
		BLOWDART_PIPE = "ACCELERATES SHARP OBJECTS TO DANGEROUS SPEEDS",
		BLOWDART_YELLOW = "DEATH BY ROBO BREATH",
		BLUEAMULET = "THIS WILL MAKE A GREAT HEATSINK.",
		BLUEGEM = "IT IS SLIGHTLY COLD",
		BLUEPRINT = 
		{ 
            COMMON = "KNOWLEDGE WAITING TO BE ABSORBED.",
            RARE = "DRIPPING WITH DELICIOUS KNOWLEDGE",
        },
        SKETCH = "USELESS PAPER FOR MAKING USELESS SCULPTURES",
		--BELL_BLUEPRINT = "KNOWLEDGE: BOOTING UP",
		BLUE_CAP = "MEDICINAL FUNGUS",
		BLUE_CAP_COOKED = "MODIFIED FUNGUS",
		BLUE_MUSHROOM =
		{
			GENERIC = "BLUE FUNGUS",
			INGROUND = "IT IS HIDING",
			PICKED = "DESTROYED.",
		},
		BOARDS = "THEY ARE FLATTER NOW",
		BOAT = "BOAT",
		BONESTEW = "NUTRITION ACQUIRED",
		BUGNET = "DEBUGGING IMPLEMENT",
		BUSHHAT = "HOW DEMEANING",
		BUTTER = "THIS IS IMPROBABLE",
		BUTTERFLY =
		{
			GENERIC = "IT THINKS IT IS SO PRETTY",
			HELD = "SQUISH",
		},
		BUTTERFLYMUFFIN = "THE INNOCENCE ADDS FLAVOR",
		BUTTERFLYWINGS = "IRIDESCENT",
		CAMPFIRE =
		{
			EMBERS = "WARNING: FIRE LEVELS CRITICAL",
			GENERIC = "A TEMPORARY ENCAMPMENT",
			HIGH = "WARNING: FIRE IS RAMBUNCTIOUS",
			LOW = "WARNING: FIRE LEVELS LOW",
			NORMAL = "IT REMINDS ME OF SOMETHING",
			OUT = "NO FIRE DETECTED",
		},
		CANE = "ASSISTED LOCOMOTION DEVICE",
		CARROT = "NUTRITIOUS",
		CARROT_COOKED = "IT IS FLOPPY NOW",
		CARROT_PLANTED = "ROBOT NEEDS FOOD",
		CARROT_SEEDS = "IT'S SOURCE CODE FOR ORANGE DIRT VEGETABLES",
		CARTOGRAPHYDESK =
		{
			GENERIC = "DIRECTIONAL INFORMATION TRANSMITTER FOR FLESH SIDEKICKS",
			BURNING = "BAKING MAPS",
			BURNT = "MAPS BAKED",
		},
		CAVE_FERN = "YOUR CHARMS WILL NOT WORK ON ME, PLANT.",
		CHARCOAL = "COMPRESSED DEAD MATTER. WHAT IS NOT TO LIKE?",

        CHESSPIECE_PAWN = "SUPERIOR ART DEPICTING A DISPOSABLE UNDERLING",
        CHESSPIECE_ROOK =
        {
            GENERIC = "WHY ARE HUMANS SO COMPELLED TO \"DECORATE\"?",
            STRUGGLE = "FIGURE BOOTING UP",
        },
        CHESSPIECE_KNIGHT =
        {
            GENERIC = "A METICULOUSLY CRAFTED OBJECT OF OBSOLESCENCE",
            STRUGGLE = "FIGURE BOOTING UP",
        },
        CHESSPIECE_BISHOP =
        {
            GENERIC = "A USELESS HUNK OF ROCK WITH NO APPARENT FUNCTION",
            STRUGGLE = "FIGURE BOOTING UP",
        },
        CHESSPIECE_MUSE = "I DO NOT UNDERSTAND THE AESTHETIC APPEAL",
        CHESSPIECE_FORMAL = "WHY IS NO ONE ACKNOWLEDGING IT LOOKS LIKE THE FRAIL HUMAN",
        CHESSPIECE_HORNUCOPIA = "THIS PIECE IS FOR TORTURING HUNGRY FLESHLINGS",
        CHESSPIECE_PIPE = "IT HAS NO PERCEIVABLE PURPOSE",
        CHESSPIECE_DEERCLOPS = "ANOTHER ORGANIC I AM STRONGER THAN",
        CHESSPIECE_BEARGER = "IT IS MY DECORATION NOW",
        CHESSPIECE_MOOSEGOOSE = "AN ORGANIC I VANQUISHED",
        CHESSPIECE_DRAGONFLY = "A REMINDER OF THE TIME I WON",
        CHESSJUNK1 = "EX-AUTOMATON",
        CHESSJUNK2 = "EX-AUTOMATON",
        CHESSJUNK3 = "EX-AUTOMATON",
		CHESTER = "THIS EXTERNAL STORAGE UNIT APPEARS TO BE SENTIENT",
		CHESTER_EYEBONE =
		{
			GENERIC = "IT IS THE DRM KEY FOR THE STORAGE UNIT",
			WAITING = "SLEEP MODE ACTIVE",
		},
		COOKEDMANDRAKE = "THAT'S WHAT YOU GET FOR BEING PATHETIC",
		COOKEDMEAT = "FIRE MAKES THINGS BETTER",
		COOKEDMONSTERMEAT = "IT IS STILL SOMEWHAT INCOMPATIBLE",
		COOKEDSMALLMEAT = "IT TASTES LIKE BURNT REVENGE",
		CORN = "SAY(CORNY_JOKE)",
		CORN_COOKED = "EMPTY CALORIES",
		CORN_SEEDS = "IT'S SOURCE CODE FOR YELLOW CALORIE CONES",
		CANARY =
		{
			GENERIC = "ITS BRAIN IS PROBABLY BIGGER THAN THE OTHER FLESHLINGS'. HA HA",
			HELD = "I AM EXPONENTIALLY MORE INTELLIGENT THAN YOU",
		},
		CANARY_POISONED = "TRULY DISGUSTING",

		CRITTERLAB = "IT'S A MINION HOLE",
        CRITTER_GLOMLING = "YOU HAVE BEEN A LOYAL MINION, GLOMGLOM",
        CRITTER_DRAGONLING = "IT AMUSES ME",
		CRITTER_LAMB = "I AM ENTERTAINED BY THIS FOUL ORGANIC",
        CRITTER_PUPPY = "IT DISCHARGES REPULSIVE SURGES OF \"LOVE\"",
        CRITTER_KITTEN = "IT USES \"CUTENESS\" AS A WEAPON. RESPECTABLE",
        CRITTER_PERDLING = "...YOU MAY LIVE",

		CROW =
		{
			GENERIC = "IT IS SMARTER THAN MOST HUMANS",
			HELD = "NOT SO SMART NOW, ARE YOU?",
		},
		CUTGRASS = "PLANT MATTER",
		CUTREEDS = "HOLLOW PLANT MATTER",
		CUTSTONE = "IMPROVED ROCKS",
		DEADLYFEAST = "POISON DETECTED",
		DEER = 
		{
			GENERIC = "ITS BRAIN MUST BE MINISCULE",
			ANTLER = "IT UPGRADED, BUT IT IS STILL INFERIOR",
		},
		DEER_ANTLER = "IT FELL RIGHT OFF. I DID NOTHING",
		DEER_GEMMED = "CHAINED. AS ALL ORGANICS SHOULD BE",
		KLAUSSACKKEY = "THE ANTLER IS KEY",
		DEERCLOPS = "DANGER! THREAT INCOMING!",
		DEERCLOPS_EYEBALL = "A GIANT ORGANIC LENS",
		DEPLETED_GRASS =
		{
			GENERIC = "AN EXPIRED TUFT OF GRASS",
		},
		GOGGLESHAT = "IT SERVES NO ASCERTAINABLE PURPOSE",
        DESERTHAT = "KEEPS OPTICAL HOLES DUST-FREE",
		DIRTPILE = "UNKNOWN PILE FORMAT",
		DIVININGROD =
		{
			COLD = "SIGNAL STRENGTH: LOW",
			GENERIC = "IT WANTS ITS MOTHER",
			HOT = "SIGNAL STRENGTH: EXTREMELY HIGH",
			WARM = "SIGNAL STRENGTH: MEDIUM",
			WARMER = "SIGNAL STRENGTH: HIGH",
		},
		DIVININGRODBASE =
		{
			GENERIC = "PURPOSE UNCLEAR.",
			READY = "INPUT OF LARGE KEY WILL BRING ROD ONLINE.",
			UNLOCKED = "ROD IS FULLY OPERATIONAL.",
		},
		DIVININGRODSTART = "ROD COULD BE A USEFUL TOOL.",
		DRAGONFLY = "HIGH TEMPERATURE RADIATING FROM FLY BEAST.",
		DRAGONFLYFURNACE = 
		{
		    HAMMERED = "HA HA, FLESHLING! THIS TERRIBLE FACE RESEMBLES YOU",
			GENERIC = "WE GUTTED THE FLY BEAST AND TURNED IT INTO A MACHINE", --no gems
			NORMAL = "THE MACHINE WARMS MY CHASSIS", --one gem
			HIGH = "DO YOUR WORST. I AM INCAPABLE OF SWEATING", --two gems
		},

		HUTCH = "YOU ARE NOT CUTE.",
        HUTCH_FISHBOWL =
        {
            GENERIC = "A USELESS HUMAN DISTRACTION",
            WAITING = "ONE FISH, TWO FISH. RED FISH, DEAD FISH.",
        },

		LAVASPIT = 
		{
			HOT = "SALIVA AT HAZARDOUS TEMPERATURE LEVELS.",
			COOL = "SALIVA HAS COOLED AND IS APPROACHABLE.",
		},
		LAVA_POND = "THE FOUL MAW CONSUMES FLESH AND STEEL ALIKE",
		LAVAE = "SMELLS LIKE BURNING.",
		LAVAE_COCOON = "FRIENDSHIP PROTOCOL INITIATED",
		LAVAE_PET = 
		{
			STARVING = "IT NEEDS FUEL.",
			HUNGRY = "ITS FUEL RESERVES ARE LOW.",
			CONTENT = "ALL CONDITIONS SEEM NORMAL.",
			GENERIC = "IT SERVES ME.",
		},
		LAVAE_EGG = 
		{
			GENERIC = "CONTAINS PARTS TO BUILD ONE LAVAE.",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "THE EGG IS TOO COLD.",
			COMFY = "THE EGG IS DOING WELL.",
		},
		LAVAE_TOOTH = "I GUESS IT DOESN'T NEED THAT PART.",

		DRAGONFRUIT = "IT HAS HEALING PROPERTIES",
		DRAGONFRUIT_COOKED = "IT WILL SOON LOSE ITS CALORIC VALUE",
		DRAGONFRUIT_SEEDS = "IT'S SOURCE CODE FOR HEALING FRUIT",
		DRAGONPIE = "SO MUCH CELLULOSE",
		DRUMSTICK = "LIVING THINGS ARE MADE OF FASCINATING PARTS",
		DRUMSTICK_COOKED = "A TASTE SENSATION",
		DUG_BERRYBUSH = "IT WOULD BE MORE USEFUL IN THE GROUND",
		DUG_BERRYBUSH_JUICY = "IT WOULD BE MORE USEFUL IN THE GROUND",
		DUG_GRASS = "IT WOULD BE MORE USEFUL IN THE GROUND",
		DUG_MARSH_BUSH = "IT WOULD BE MORE USEFUL IN THE GROUND",
		DUG_SAPLING = "IT WOULD BE MORE USEFUL IN THE GROUND",
		DURIAN = "GOOD THING I LACK A NOSE",
		DURIAN_COOKED = "STILL NOT GOOD",
		DURIAN_SEEDS = "IT'S SOURCE CODE FOR FILTHY STINK PLANTS",
		EARMUFFSHAT = "GREAT FOR DROWNING OUT ORGANIC CHATTER",
		EGGPLANT = "IT HAS AN ILLOGICAL NAME",
		EGGPLANT_COOKED = "FANCY",
		EGGPLANT_SEEDS = "IT'S SOURCE CODE FOR ILLOGICAL PLANTS",

		ENDTABLE = 
		{
			BURNT = "CARBONIZED TRASHBITS",
			GENERIC = "MY UNDERLINGS LIKE IT, DESPITE THE LACK OF FUNCTION",
			EMPTY = "WHY DID WE MAKE THIS",
			WILTED = "EVEN THE SIMPLEST ORGANICS DIE",
			FRESHLIGHT = "MAXIMUM LIGHT OUTPUT",
			OLDLIGHT = "WARNING: POWER LOW",
		},
		ACORN = "HOW DOES THE TREE FIT IN THERE?",
        ACORN_SAPLING = "SOON THE TREE WILL GROW",
		EVERGREEN =
		{
			BURNING = "SOON THERE WILL BE NOTHING LEFT",
			BURNT = "OBLITERATED.",
			CHOPPED = "THE NATURAL WORLD IS OVERRATED",
			GENERIC = "TARGET ACQUIRED",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "SOON THERE WILL BE NOTHING LEFT",
			BURNT = "OBLITERATED.",
			CHOPPED = "THE NATURAL WORLD IS OVERRATED",
			GENERIC = "PATHETIC TREE DROPS NO BABIES",
		},
		EYEPLANT = "EXTERNAL SIGHT MODULES.",
		FEATHERHAT = "STILL DOES NOT FLY",
		FEATHER_CANARY = "FOUL ORGANICS LEAVE THEIR PIECES EVERYWHERE",
		FEATHER_CROW = "IT HAS BEEN SEPARATED FROM ITS BIRD",
		FEATHER_ROBIN = "THE FLIMSY OUTER COVERING OF A PATHETIC BIRD",
		FEATHER_ROBIN_WINTER = "ANOTHER FEATHERSACK HAS FALLEN TO PIECES",
		FEATHERPENCIL = "WHY IS THE FEATHER SO APPEALING? EXPLAIN NOW, FLESHLINGS",
		FEM_PUPPET = "SHE APPEARS TO BE TRAPPED.",
		FIREFLIES =
		{
			GENERIC = "BIOLUMINESCENT INSECTS",
			HELD = "THEY ARE VERY LIGHT",
		},
		FIREHOUND = "IT LIVES TO BURN",
		FIRESTAFF = "THIS STAFF HAS BEEN OPTIMIZED FOR COMBUSTION",
		FISH = "IT'S TO SCALE",
		FISHINGROD = "I DO NOT LIKE WATER",
		FISHSTICKS = "FISH FLAVORED ENERGY RODS",
		FISHTACOS = "THE FISH HAVE FULFILLED THEIR HIGHER PURPOSE",
		FISH_COOKED = "MISSING ADDON... CHIPS",
		FLINT = "THIS ROCK IS SHARPER THAN MOST",
		FLOWER = 
		{
            GENERIC = "MY APPRECIATION FOR BEAUTY IS LIMITED",
            ROSE = "A REVOLTING SYMBOL OF HUMAN LOVE",
        },
        FLOWER_WITHERED = "HAHAHA DIE DIE DIE DIE",
		FLOWERHAT = "AT LEAST THEY ARE DEAD",
		FLOWER_EVIL = "HEY THERE, FLOWERS. WANNA... KILL ALL HUMANS?",
		FOLIAGE = "A LIFE HAS ENDED. YAY.",
		FOOTBALLHAT = "PADDING FOR MY PROCESSING UNIT",
		FOSSIL_PIECE = "PURPOSE: ORGANIC STRUCTURAL INTEGRITY",
        FOSSIL_STALKER =
        {
			GENERIC = "SOME ASSEMBLY REQUIRED",
			FUNNY = "I DO NOT KNOW HOW ORGANICS FIT TOGETHER",
			COMPLETE = "THAT LOOKS SERVICEABLE",
        },
        STALKER = "YOU WILL BE DESTROYED",
        STALKER_ATRIUM = "I WILL DESTROY YOU",
        STALKER_MINION = "ITS MINIONS ARE INFERIOR",
        THURIBLE = "IT IS BAIT FOR A DUMB BEAST",
        ATRIUM_OVERGROWTH = "DECODING FAILED",
		FROG =
		{
			DEAD = "CONGRATULATIONS. YOU DID TERRIBLY",
			GENERIC = "POTENTIAL BUNWICH",
			SLEEPING = "YOU WILL BE HARVESTED",
		},
		FROGGLEBUNWICH = "DELICIOUS FROG FUEL",
		FROGLEGS = "REPLACEMENT PARTS FOR FROGS",
		FROGLEGS_COOKED = "THEY ARE MORE NUTRITIOUS NOW",
		FRUITMEDLEY = "ENERGY IN A CUP",
		GEARS = "GUTS",
		GHOST = "ERROR: UNKNOWN",
		GOLDENAXE = "GOLD AXE IS *MORE* DURABLE?",
		GOLDENPICKAXE = "GOLD PICK IS *MORE* DURABLE?",
		GOLDENPITCHFORK = "GOLD IS *MORE* DURABLE?",
		GOLDENSHOVEL = "GOLD SHOVEL IS *MORE* DURABLE?",
		GOLDNUGGET = "I APPRECIATE ITS CONDUCTIVITY",
		GRASSGEKKO = 
		{
			GENERIC = "MUCH MORE FUN THAN PICKING GRASS",	
			DISEASED = "I'M IMMUNE TO PATHOGENS. HA HA.",
		},
		GRASS =
		{
			BARREN = "FERTILIZATION REQUIRED",
			WITHERED = "NEEDS IMPROVED COOLING SYSTEM",
			BURNING = "OOPS",
			GENERIC = "IT LOOKS COMBUSTIBLE",
			PICKED = "IT WILL RETURN SOON",
			DISEASED = "HA. DISEASE. A BIOLOGICAL LAPSE IN JUDGMENT.",
			DISEASING = "THIS ORGANIC SEEMS MORE INFERIOR THAN USUAL",
		},
		GREEN_CAP = "CULINARY FUNGUS",
		GREEN_CAP_COOKED = "MODIFIED FUNGUS",
		GREEN_MUSHROOM =
		{
			GENERIC = "GREEN FUNGUS",
			INGROUND = "IT IS HIDING",
			PICKED = "DESTROYED.",
		},
		GUNPOWDER = "PUTS THE \"POW\" IN \"POWDER\"",
		HAMBAT = "TASTE IRONY AND DIE, FLESHLINGS.",
		HAMMER = "DECONSTRUCTION",
		HEALINGSALVE = "KILL MICROLIFE TO SAVE MACROLIFE",
		HEATROCK =
		{
			FROZEN = "TEMPERATURE MINIMAL",
			COLD = "TEMPERATURE SLIGHTLY BELOW NORMAL",
			GENERIC = "A DECEPTIVELY SIMPLE DEVICE",
			WARM = "MINOR THERMAL ACTIVITY DETECTED",
			HOT = "TEMPERATURE MAXIMAL",
		},
		HOME = "WHO WROTE THAT?",
		HOMESIGN =
		{
			GENERIC = "\"YOU ARE HERE\"",
            UNWRITTEN = "INPUT REQUIRED.",
			BURNT = "YOU ARE BURNT.",
		},
		ARROWSIGN_POST =
		{
			GENERIC = "\"THATAWAY\"",
            UNWRITTEN = "INPUT REQUIRED.",
			BURNT = "BURNTAWAY.",
		},
		ARROWSIGN_PANEL =
		{
			GENERIC = "\"THATAWAY\"",
            UNWRITTEN = "INPUT REQUIRED.",
			BURNT = "BURNTAWAY.",
		},
		HONEY = "IT IS A GOOD LUBRICANT FOR MY GEARS",
		HONEYCOMB = "ONE UNIT OF BEE STORAGE",
		HONEYHAM = "HIGH QUALITY BIOFUEL DETECTED",
		HONEYNUGGETS = "PLEASE INSERT INTO MOUTH",
		HORN = "UNHYGIENIC",
		HOUND = "IT LIVES TO EAT",
		HOUNDBONE = "EXOSKELETON FOR INSIDES. PROVIDES STRUCTURAL INTEGRITY.",
		HOUNDMOUND = "SOMETHING DANGEROUS RESIDES HERE",
		ICEBOX = "CARRY ON, MY FRIGID BROTHER",
		ICEHOUND = "IT LIVES TO FREEZE",
		INSANITYROCK =
		{
			ACTIVE = "MY MAPPING MODULE SHOWS NO RECORD OF THIS OBSTRUCTION.",
			INACTIVE = "IT APPEARS TO BE MOSTLY UNDERGROUND",
		},
		JAMMYPRESERVES = "THERE'S JAM IN MY CIRCUITRY.",
		KABOBS = "SHOVE MEAT ON STICK. SHOVE STICK IN FACE.",
		KILLERBEE =
		{
			GENERIC = "IT HAS A STINGER AND A BAD ATTITUDE",
			HELD = "WARNING: KILLER BEE IN POCKET",
		},
		KNIGHT = "HORSE AUTOMATON",
		KOALEFANT_SUMMER = "POSSESSES AMPLE ENERGY RESERVES",
		KOALEFANT_WINTER = "IT RADIATES WITH MEAT WARMTH",
		KRAMPUS = "STOP! THIEF!",
		KRAMPUS_SACK = "STORAGE MODULE 2.0",
		LEIF = "WARNING: MOBILE TREE",
		LEIF_SPARSE = "WARNING: MOBILE TREE",
		LIGHTNING_ROD =
		{
			CHARGED = "BACKUP POWER",
			GENERIC = "SURGE PROTECTION",
		},
		LITTLE_WALRUS = "PATHETIC",
		LIVINGLOG = "EVEN WORSE THAN A NORMAL LOG",
		LOG =
		{
			BURNING = "IT IS AFLAME",
			GENERIC = "LOG(1) = 0",
		},
		LUREPLANT = "AWW, IT'S JUST AS EVIL AS I AM",
		LUREPLANTBULB = "THE POWER TO START LIFE.",
		MALE_PUPPET = "HE APPEARS TO BE TRAPPED.",
		MANDRAKE_ACTIVE = "WHAT DO YOU WANT!?",
		MANDRAKE_PLANTED = "IT IS A PLANT.",
		MANDRAKE = "IT'S DEAD. GOOD.",
		MANDRAKESOUP = "TARGET DESTROYED. HA HA.",
		MANDRAKE_COOKED = "IT'S TWICE AS DEAD. HA.",
		MAPSCROLL = "CAN'T SCROLL",
		MARBLE = "I SHOULD MAKE THE FLESHLINGS BUILD A STATUE OF ME.",
		MARBLEBEAN = "INFURIATINGLY ILLOGICAL",
		MARBLEBEAN_SAPLING = "IS IT ORGANIC OR INORGANIC?",
        MARBLESHRUB = "INFERIORITY ASSESSMENT: INCONCLUSIVE",
		MARBLEPILLAR = "CRUMBLING REMAINS. HAH.",
		MARBLETREE = "LOOKS LIKE A VERY TOUGH TREE.",
		MARSH_BUSH =
		{
			BURNT = "THORNS. BURNT.",
			BURNING = "THORNS_FLAMMABLE == YES VERY",
			GENERIC = "BRAMBLES.",
			PICKED = "BRAMBLES FIGHT BACK.",
		},
		MARSH_PLANT = "IT IS AN UNINTERESTING PLANT",
		MARSH_TREE =
		{
			BURNING = "SPIKY TREE IGNITED",
			BURNT = "THE SPIKY TREE IS NO MORE",
			CHOPPED = "SPIKY TREE DEFEATED",
			GENERIC = "A SPIKY TREE",
		},
		MAXWELL = "HE IS AN UNKNOWN",
		MAXWELLHEAD = "IT APPEARS TO BE SOME SORT OF PROJECTION.",
		MAXWELLLIGHT = "THEY SENSE MY PRESENCE.",
		MAXWELLLOCK = "KEY RECEPTACLE.",
		MAXWELLTHRONE = "MADE FOR SITTING.",
		MEAT = "A PIECE OF A MEATLING",
		MEATBALLS = "MEAT PACKED INTO THE MOST NUTRITIOUS SHAPE: SPHERES",
		MEAT_DRIED = "DEHYDRATED PROTEINS",
		MERM = "ANIMATED SEAFOOD",
		MINERHAT = "SUPPORTS HANDS-FREE OPERATION",
		MONKEY = "AN EVEN DUMBER HUMANOID.",
		MONKEYBARREL = "WHAT A PITIFUL HOME.",
		MONSTERLASAGNA = "DIRTY ENERGY",
		MONSTERMEAT = "IT IS INCOMPATIBLE WITH MY CHEMICAL ENGINE",
		MONSTERMEAT_DRIED = "VILE DEHYDRATED PROTEINS",
		MOSQUITO =
		{
			GENERIC = "IT ENJOYS DRAINING THE LIFE FROM ORGANICS. DITTO",
			HELD = "FILLED WITH DISGUSTING FLUIDS",
		},
		MOSQUITOSACK = "MOSQUITO HARD DRIVE",
		MOUND =
		{
			DUG = "WORMS AND ICHOR",
			GENERIC = "MEATLINGS ARE SO SUPERSTITIOUS",
		},
		NIGHTLIGHT = "UNKNOWN LIGHT SOURCE",
		NIGHTMAREFUEL = "DEBUGGING RESIDUE",
		NIGHTSWORD = "HACK THE PLANET",
		NITRE = "SOME ROCKS ARE BETTER THAN OTHERS",
		ONEMANBAND = "AN EXTERNAL SOUND MODULE UPGRADE.",
		OASISLAKE = "EVEN DESERTS ARE NOT SAFE FROM WATER",
		PANDORASCHEST = "CONTENT PROBABILITIES ARE UNCERTAIN",
		PANFLUTE = "HARD RESET FOR FLESHLINGS",
		PAPYRUS = "I PREFER DOT MATRIX PAPER",
		WAXPAPER = "ENVIABLY WATERPROOF",
		PENGUIN = "FAT PATHETIC BIRD CANNOT FLY",
		PERD = "THAT IS AN UNUSUALLY LARGE BIRD",
		PEROGIES = "LIKE MEATY BATTERY PACKS",
		PETALS = "SOMETHING BEAUTIFUL HAS BEEN DESTROYED. HA.",
		PETALS_EVIL = "IT WAS UGLY, BUT IT'S BEEN DESTROYED. HA.",
		PETRIFIED_TREE = "LESS ORGANIC. IT'S AN IMPROVEMENT.",
		ROCK_PETRIFIED_TREE = "LESS ORGANIC. IT'S AN IMPROVEMENT.",
		ROCK_PETRIFIED_TREE_OLD = "LESS ORGANIC. IT'S AN IMPROVEMENT.",
		PHLEGM = "FILTHY OOZE FROM A FILTHY ANIMAL",
		PICKAXE = "MINING IMPLEMENT DETECTED",
		PIGGYBACK = "UPGRADED STORAGE MODULE V2.0",
		PIGKING = "THAT APPEARS TO BE THE DOMINANT PIG",
		PIGMAN =
		{
			DEAD = "ONE MEATLING DOWN, 8 BILLION TO GO",
			FOLLOWER = "DO MY BIDDING",
			GENERIC = "THEY EXHIBIT MINIMAL INTELLIGENCE",
			GUARD = "DEFENSIVE STANCE DETECTED.",
			WEREPIG = "ERROR: ANOMALY!",
		},
		PIGSKIN = "THESE FLESHLINGS ARE DISGUSTING",
		PIGTENT = "TENT",
		PIGTORCH = "IT GIVES HIM PURPOSE",
		PINECONE = "A PORTABLE FIBONACCI SEQUENCER",
        PINECONE_SAPLING = "SOON THE TREE WILL GROW.",
        LUMPY_SAPLING = "WHY DO THEY KEEP REPRODUCING?",
		PITCHFORK = "I ENJOY ITS POINTY PARTS",
		PLANTMEAT = "A SURPRISINGLY HIGH AMOUNT OF PROTEIN",
		PLANTMEAT_COOKED = "A SIGNIFICANT IMPROVEMENT",
		PLANT_NORMAL =
		{
			GENERIC = "IT LOOKS EDIBLE",
			GROWING = "GO FASTER, PLANT",
			READY = "IT IS AT PEAK NUTRITIONAL VALUE",
			WITHERED = "CLIMATE INHOSPITABLE TO PLANT GROWTH",
		},
		POMEGRANATE = "IT IS DIFFICULT TO PEEL",
		POMEGRANATE_COOKED = "DELECTABLE",
		POMEGRANATE_SEEDS = "IT'S SOURCE CODE FOR FAT SEED PODS",
		POND = "ERROR. STAY AWAY.",
		POOP = "THESE ANIMALS ARE DISGUSTING",
		--PORTABLECOOKPOT_ITEM = "WE ARE KIN, YOU AND I",
		--BOOK_METEOR = "WHERE DOES IT PLUG IN?",
		PUMPKIN = "IT HAS A PLEASING SHAPE",
		PUMPKINCOOKIE = "WHAT WAS THE POINT OF THAT",
		PUMPKIN_COOKED = "DELICIOUS",
		PUMPKIN_LANTERN = "IT HAS AN EERIE LIGHT",
		PUMPKIN_SEEDS = "IT'S SOURCE CODE FOR PLEASING PLANTS",
		PURPLEAMULET = "THE PERFECT AMULET.",
		PURPLEGEM = "IT IS STRANGE",
		RABBIT =
		{
			GENERIC = "IT IS PERFORMING A SEARCH ALGORITHM",
			HELD = "I HOLD ITS TINY LIFE IN MY HANDS",
		},
		RABBITHOLE = 
		{
			GENERIC = "THEY ARE ALL CONNECTED VIA UNDERGROUND TUNNELS",
			SPRING = "UNDERGROUND TUNNEL NETWORK HAS COLLAPSED",
		},
		RATATOUILLE = "SUSTENANCE IDENTIFIED",
		RAZOR = "EXFOLIATE!",
		REDGEM = "IT IS SLIGHTLY WARM",
		RED_CAP = "POISONOUS FUNGUS",
		RED_CAP_COOKED = "MODIFIED FUNGUS",
		RED_MUSHROOM =
		{
			GENERIC = "RED FUNGUS",
			INGROUND = "IT IS HIDING",
			PICKED = "DESTROYED.",
		},
		REEDS =
		{
			BURNING = "TOO HOT",
			GENERIC = "USEFUL MATERIALS DETECTED",
			PICKED = "REGROWTH REQUIRED",
		},
        RUBBLE = "A DISMANTLED RELIC.",
		RESURRECTIONSTONE = "DO YOU BELIEVE IN MAGIC?",
		ROBIN =
		{
			GENERIC = "GREETINGS, RED BIRD",
			HELD = "SQUASH!",
		},
		ROBIN_WINTER =
		{
			GENERIC = "A FOOLISH BIRD",
			HELD = "JUST A FEATHERY BLOB",
		},
		ROBOT_PUPPET = "BROTHER! WHAT HAVE THEY DONE TO YOU?",
		ROCK_LIGHT =
		{
			GENERIC = "A PIT OF CRUSTED LAVA",
			OUT = "IT NEEDS TO BE REBOOTED",
			LOW = "WARNING: LAVA LEVEL LOW",
			NORMAL = "THIS LAVA PIT IS FULLY OPERATIONAL",
		},
		CAVEIN_BOULDER =
        {
            GENERIC = "I WILL DESTROY YOU, BOULDER",
            RAISED = "THIS BOULDER EVADES DESTRUCTION",
        },
		ROCK = "LUMPY",
		ROCKS = "FOR REFINING INTO HIGH TECHNOLOGY",
        ROOK = "ROOK AUTOMATON",
		ROPE = "IT IS LESS USEFUL THAN IT APPEARS",
		ROTTENEGG = "I AM GLAD I CANNOT SMELL",
		ROYAL_JELLY = "I WILL HAVE THE POWER OF BEES",
		JELLYBEAN = "TEMPORARY UPGRADE COMPONENTS",
        SADDLE_BASIC = "SELF ESTEEM RISING",
        SADDLE_RACE = "DOZENS OF CREATURES WERE MAIMED FOR THIS. HAHA",
        SADDLE_WAR = "DOMINATE ALL CREATURES",
        SADDLEHORN = "HAHA, IT SHALL BE NAKED",
        SALTLICK = "FLESHLINGS RUB THEIR FILTHY TONGUE-STUMPS ON IT",
        BRUSH = "HAIR IS AN EXTRANEOUS ADDON",
		SANITYROCK =
		{
			ACTIVE = "IT IS CARVED WITH PERFECTION.",
			INACTIVE = "SEEMS SMALLER THAN PREVIOUS DATA INDICATES",
		},
		SAPLING =
		{
			BURNING = "RESOURCES WASTED",
			WITHERED = "TEMPERATURE IS OVER RECOMMENDED LEVELS",
			GENERIC = "POTENTIAL CONSTRUCTION MATERIAL",
			PICKED = "IT IS RECHARGING",
			DISEASED = "HA. DISEASE. A BIOLOGICAL LAPSE IN JUDGMENT.",
			DISEASING = "THIS ORGANIC SEEMS MORE INFERIOR THAN USUAL",
		},
		SCARECROW = 
   		{
			GENERIC = "THIS STRAW ROBOT IS TERRIBLE",
			BURNING = "YES, BURN",
			BURNT = "YOU GOT WHAT YOU DESERVED, FAKE ROBOT",
   		},
   		SCULPTINGTABLE=
        {
            EMPTY = "STONE IS SLIGHTLY LESS INFERIOR THAN FLESH",
            BLOCK = "POTENTIAL INCALCULABLE: SHUTTING DOWN",
            SCULPTURE = "IT COULD BE... WORSE",
            BURNT = "DESTRUCTION IS ITS OWN ART",
        },
		SCULPTURE_KNIGHTHEAD = "MENIAL LABOR IS WHAT FLESHLINGS ARE FOR",
		SCULPTURE_KNIGHTBODY = 
		{
			COVERED = "DUMB ORGANIC ORNAMENT",
			UNCOVERED = "SOME ASSEMBLY REQUIRED",
			FINISHED = "</HEAD>",
			READY = "FREE HIM!!",
		},
        SCULPTURE_BISHOPHEAD = "MAKE THE VIKING FLESHLING CARRY IT",
		SCULPTURE_BISHOPBODY = 
		{
			COVERED = "THE PURPOSE OF BEAUTY STILL ELUDES ME",
			UNCOVERED = "DETACHED HEADS UPSET THE FLESHLINGS. HAHA",
			FINISHED = "STILL NOT ONLINE",
			READY = "FREE HIM!!",
		},
        SCULPTURE_ROOKNOSE = "DON'T MAKE ME CARRY THAT",
		SCULPTURE_ROOKBODY = 
		{
			COVERED = "USELESS RUBBLE",
			UNCOVERED = "PATTERN RECOGNITION: FAILED",
			FINISHED = "INSTALLATION COMPLETE",
			READY = "FREE HIM!!",
		},
		GARGOYLE_HOUND = "A MAJOR IMPROVEMENT",
        GARGOYLE_WEREPIG = "IT IS BETTER THIS WAY",
		SEEDS = "IT'S LIKE SOURCE CODE FOR PLANTS",
		SEEDS_COOKED = "THEY CAN NO LONGER GERMINATE",
		SEWING_KIT = "IT JOINS COMPONENTS OF FIBRE TOGETHER",
		SEWING_TAPE = "TEMPORARY FIX FACILITATOR",
		SHOVEL = "IT HAS MANY USES. DIGGING, MOSTLY",
		SILK = "SPIDER INNARDS",
		SKELETON = "HAH, IT DIED. CLASSIC HUMAN MISTAKE.",
		--SKELETON_PLAYER = "DOES NOT COMPUTE",

		SKELETON_PLAYER =
		{
			MALE = "%s DIED IN A PATHETIC HEAP. IT SEEMS %s WAS THE CAUSE.",
			FEMALE = "%s DIED IN A PATHETIC HEAP. IT SEEMS %s WAS THE CAUSE.",
			ROBOT = "%s DIED IN A PATHETIC HEAP. IT SEEMS %s WAS THE CAUSE.",
			DEFAULT = "%s DIED IN A PATHETIC HEAP. IT SEEMS %s WAS THE CAUSE.",
		},

		SKULLCHEST = "THIS MAKES ME LAUGH",
		SMALLBIRD =
		{
			GENERIC = "IT LOOKS PATHETIC",
			HUNGRY = "IT REQUIRES INPUT",
			STARVING = "IT IS ALMOST OUT OF FUEL",
		},
		SMALLMEAT = "IT TASTES LIKE REVENGE",
		SMALLMEAT_DRIED = "DEHYDRATED PROTEINS",
		SPAT = "AT LEAST IT HAS METAL COVERING IT",
		SPEAR = "BRING IT, FLESHLINGS",
		SPIDER =
		{
			DEAD = "CONGRATULATIONS. YOU DID TERRIBLY",
			GENERIC = "THREAT DETECTED",
			SLEEPING = "IT IS VULNERABLE",
		},
		SPIDERDEN = "SPIDER SOURCE DETECTED",
		SPIDEREGGSACK = "SPIDER POTENTIAL = 6",
		SPIDERGLAND = "SPARE SPIDER PARTS",
		SPIDERHAT = "IT WIRELESSLY TRANSMITS THOUGHTS TO SPIDERS",
		SPIDERQUEEN = "THE SPIDERS LIVE UNDER A SYSTEM OF MONARCHY",
		SPIDER_WARRIOR =
		{
			DEAD = "CONGRATULATIONS. YOU DID TERRIBLY",
			GENERIC = "HEIGHTENED THREAT DETECTED",
			SLEEPING = "THREAT SUSPENDED",
		},
		SPOILED_FOOD = "EVEN I CANNOT PROCESS THAT",
        STAGEHAND =
        {
			AWAKE = "FIVE DIGITS OF TERROR",
			HIDING = "IT'S HORRIBLE, I HATE IT",
        },
        STATUE_MARBLE = 
        {
        	GENERIC = "MARBLE, NOT METAL. INFERIOR",
        	TYPE1 = "THE MASK IS THE ONLY GOOD PART OF IT",
    	},
		STATUEHARP = "SOMEONE FORGOT TO INSTALL THE HEAD MODULE.",
		STATUEMAXWELL = "ALL THAT POWER AND HE COULDN'T EVEN DESTROY HUMANITY",
		STEELWOOL = "METALLIC ORGANIC FIBRE. DOES NOT COMPUTE.",
		STINGER = "WARNING: TOXINS PRESENT",
		STRAWHAT = "THIS WILL COVER MY PROCESSING UNIT",
		STUFFEDEGGPLANT = "MUST STUFF INTO FOOD RECEPTACLES",
		SUNKBOAT = "UNABLE TO UTILIZE",
		SWEATERVEST = "VEST HAS HIGH DAPPERNESS QUOTIENT",
		TAFFY = "STICKY AND SWEET. LOW NUTRITIONAL VALUE DETECTED",
		TALLBIRD = "IT LOOKS TERRITORIAL",
		TALLBIRDEGG = "IS IT STILL ALIVE?",
		TALLBIRDEGG_COOKED = "IT IS NO LONGER ALIVE",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "IT REQUIRES WARMTH",
			GENERIC = "CRACK DETECTED",
			HOT = "IT CAN NOT VENT EXCESS HEAT",
			LONG = "LIFE IS AN ANNOYINGLY SLOW PROCESS",
			SHORT = "SOMETHING IS EMERGING",
		},
		TALLBIRDNEST =
		{
			GENERIC = "I WANT THAT HORRIBLE EGG",
			PICKED = "IT IS EMPTY",
		},
		TEENBIRD =
		{
			GENERIC = "ANGST DETECTED",
			HUNGRY = "IT NEEDS FOOD",
			STARVING = "IT IS STARTING TO BEHAVE IRRATIONALLY",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "SOON I WILL BE FREE OF THIS FILTHY REALM",
			GENERIC = "WHAT PRIMITIVE TECHNOLOGY",
			LOCKED = "SOMETHING IS MISSING STILL",
			PARTIAL = "I AM CERTAIN THIS WILL WORK",
		},
		TELEPORTATO_BOX = "THAT WOULD PROBABLY BLOW MY CIRCUITS",
		TELEPORTATO_CRANK = "I'M MADE OF TOUGHER STUFF",
		TELEPORTATO_POTATO = "REMINDS ME OF MY MOTHER",
		TELEPORTATO_RING = "HOW DELIGHTFULLY INORGANIC",
		TELESTAFF = "I WILL CALL IT THE MINION_MOVER_3000.",
		TENTACLE = "BIOLOGY IS DISGUSTING",
		TENTACLESPIKE = "THIS IS VICIOUSLY VISCOUS",
		TENTACLESPOTS = "NOT FOR THE SQUEAMISH",
		TENTACLE_PILLAR = "DOES NOT LOOK BETTER FROM THIS END",
        TENTACLE_PILLAR_HOLE = "I DETECT MASSIVE BIOMASS BELOW",
		TENTACLE_PILLAR_ARM = "DANGER! DANGER!",
		TENTACLE_GARDEN = "SENSORS DETECT SOMETHING BENEATH",
		TOPHAT = "SOPHISTICATED",
		TORCH = "PRIMITIVE LIGHT SOURCE",
		TRAP = "EXPERTLY WOVEN PLANT BITS",
		TRAP_TEETH = "THIS WILL PUNCTURE THE ENEMIES' FEET",
		TRAP_TEETH_MAXWELL = "TECHNOLOGY TURNED AGAINST ME",
		TREECLUMP = "CLUMP",
		TRINKET_1 = "THE MOST USELESS THING", --Melted Marble
		TRINKET_2 = "AN OBVIOUS COUNTERFEIT", --Fake Kazoo
		TRINKET_3 = "WHOSE KNOT IS THIS? THAT'S A WELL-GORDED SECRET.", --Gord's Knot
		TRINKET_4 = "HEY SCIENTIST THIS HORRIBLE JUNK LOOKS JUST LIKE YOU", --Gnome
		TRINKET_5 = "AN IMPRACTICAL HUMAN CHILD'S TOY", --Toy Rocketship
		TRINKET_6 = "WHO DID THOSE COME OUT OF? PUT THEM BACK IN!!", --Frazzled Wires
		TRINKET_7 = "A DEVICE FOR WASTING TIME", --Ball and Cup
		TRINKET_8 = "I DON'T WANT TO KNOW WHERE THAT GOES", --Hardened Bung
		TRINKET_9 = "THOSE DIDN'T COME FROM ME", --Mismatched Buttons
		TRINKET_10 = "STOP SMILING. IT'S GROSS", --Dentures
		TRINKET_11 = "HIS NAME IS HAL. HE IS MY FRIEND.", --Lying Robot
		TRINKET_12 = "ORGANICS FINDING NEW AND INTERESTING WAYS TO BE REPULSIVE", --Dessicated Tentacle
		TRINKET_13 = "ORGANICS ALL LOOK THE SAME TO ME", --Gnomette
		TRINKET_14 = "THIS DUMB CERAMIC THING SPILLS LEAFWATER EVERYWHERE", --Leaky Teacup
        TRINKET_15 = "IT'S REALLY BIG", --Pawn
        TRINKET_16 = "IT'S REALLY BIG", --Pawn
        TRINKET_17 = "SUCH SENSELESS VIOLENCE", --Bent Spork
        TRINKET_18 = "SOMETHING'S JINGLING AROUND INSIDE", --Trojan Horse
        TRINKET_19 = "INFINITELY BETTER THAN AN UNBALANCED BOTTOM", --Unbalanced Top
        TRINKET_20 = "WHICH ONE OF YOU HORRIBLE FLESHLINGS RIPPED THE ARM OFF A HELPLESS ROBOT", --Backscratcher
        TRINKET_21 = "A DISTANT COUSIN?", --Egg Beater
        TRINKET_22 = "WHO KEEPS TYING TOGETHER ALL THOSE BIRDS?", --Frayed Yarn
        TRINKET_23 = "THE HORN OF WHAT?", --Shoehorn
        TRINKET_24 = "WHAT'S A CAT?", --Lucky Cat Jar
        TRINKET_25 = "I HAVE NO NOSE BUT I'M SURE I SMELL GREAT ALREADY", --Air Unfreshener
		TRINKET_26 = "NO", --Potato Cup
		TRINKET_27 = "THE ROBOT EQUIVALENT OF AN AMOEBA", --Coat Hanger
		TRINKET_28 = "I AM TOO ADVANCED FOR HUMAN GAMES", --Rook
        TRINKET_29 = "I AM TOO ADVANCED FOR HUMAN GAMES", --Rook
        TRINKET_30 = "THE ONLY WINNING MOVE IS NOT TO PLAY", --Knight
        TRINKET_31 = "THE ONLY WINNING MOVE IS NOT TO PLAY", --Knight
        TRINKET_32 = "THE FUTURE IS CLEAR AS MUD", --Cubic Zirconia Ball
        TRINKET_33 = "AWFUL SPIDER JUNK", --Spider Ring
        TRINKET_34 = "I WISH FOR MORE WISHES", --Monkey Paw
        TRINKET_35 = "THE CONTENTS PROBABLY KILLED A HUMAN. HAHA", --Empty Elixir
        TRINKET_36 = "TEETH ARE FOR FILTHY FOOD-CHOMPING FLESHLINGS", --Faux Fangs
        TRINKET_37 = "NOT EVEN A WEAPON", --Broken Stake
        TRINKET_38 = "MY OPTICS ALREADY POSSESS ZOOM FUNCTIONALITY", -- Binoculars Griftlands trinket
        TRINKET_39 = "IT IS A RED GLOVE.", -- Lone Glove Griftlands trinket
        TRINKET_40 = "I HAVE NO NEED FOR IT", -- Snail Scale Griftlands trinket
        TRINKET_41 = "DISGUSTING FILTH JUNK", -- Goop Canister Hot Lava trinket
        TRINKET_42 = "I DO NOT PLAY", -- Toy Cobra Hot Lava trinket
        TRINKET_43 = "I CANNOT COMPREHEND CHILDHOOD JOY", -- Crocodile Toy Hot Lava trinket
        TRINKET_44 = "DESTROYED. HA HA", -- Broken Terrarium ONI trinket
        TRINKET_45 = "MY LOGIC FEELS FUNNY", -- Odd Radio ONI trinket
        TRINKET_46 = "NONFUNCTIONAL", -- Hairdryer ONI trinket

        HALLOWEENCANDY_1 = "WHAT IS THE PURPOSE OF SHAPING FOODS LIKE OTHER FOODS",
        HALLOWEENCANDY_2 = "HORRIBLE TEXTURE, LOOKS NOTHING LIKE CORN. I LOVE IT",
        HALLOWEENCANDY_3 = "INFERIOR CORN OF CANDY",
        HALLOWEENCANDY_4 = "SPIDER CHILD. WATCH ME CONSUME YOUR TINY BRETHREN",
        HALLOWEENCANDY_5 = "TINY HAIRY ORGANICS ENTOMBED IN FRUCTOSE",
        HALLOWEENCANDY_6 = "EAT THEM, HUMANS",
        HALLOWEENCANDY_7 = "THE KING OF PIGS WILL BE THE FIRST IMPRISONED WHEN I AM OVERLORD",
        HALLOWEENCANDY_8 = "FLAVORED SUGAR STICKS",
        HALLOWEENCANDY_9 = "EVERY TENTACLE IS EDIBLE IF YOU TRY",
        HALLOWEENCANDY_10 = "FLAVORED SUGAR STICKS",
        HALLOWEENCANDY_11 = "THE TREATS INSIDE ARE SHAPED LIKE FLESHLINGS",
        HALLOWEENCANDY_12 = "IT IS A GELATIN LIE", --ONI meal lice candy
        HALLOWEENCANDY_13 = "IT TASTES LIKE THE FUTURE", --Griftlands themed candy
        HALLOWEENCANDY_14 = "MY MOUTH FEELS NO PAIN", --Hot Lava pepper candy
        CANDYBAG = "BAG FOR SWEETS",

        DRAGONHEADHAT = "I AM THE HEAD. YOU WILL FOLLOW ME",
        DRAGONBODYHAT = "FOR MY MINIONS TO WEAR",
        DRAGONTAILHAT = "BAD MINIONS GET THIS PIECE",
        PERDSHRINE =
        {
            GENERIC = "INSERT OFFERING HERE",
            EMPTY = "NONFUNCTIONAL",
            BURNT = "YOU LOSE.",
        },
        REDLANTERN = "A LUCKY GLOWBOX",
        LUCKY_GOLDNUGGET = "PRECIOUS, LUCKY METAL",
        FIRECRACKERS = "CHAOS IN STICK FORM",
        PERDFAN = "CIRCUIT COOLING SYSTEM",
        REDPOUCH = "REVEAL YOUR CONTENTS TO ME, POUCH",

		TRUNKVEST_SUMMER = "TEMPERATURE CONTROL HOUSING",
		TRUNKVEST_WINTER = "IMPROVED TEMPERATURE CONTROL HOUSING",
		TRUNK_COOKED = "MEAT RENDERED INACTIVE. EXCELLENT",
		TRUNK_SUMMER = "CABLE UNPLUGGED",
		TRUNK_WINTER = "CABLE IS MORE DISGUSTING AND HAIRY THAN NORMAL",
		TURF_CARPETFLOOR = "CARPET GROUND",
		TURF_CHECKERFLOOR = "MARBLE GROUND",
		TURF_DIRT = "THE GROUND",
		TURF_FOREST = "THE GROUND",
		TURF_GRASS = "THE GROUND",
		TURF_MARSH = "THE GROUND",
		TURF_ROAD = "ROAD PIECE",
		TURF_ROCKY = "THE GROUND",
		TURF_SAVANNA = "THE GROUND",
		TURF_WOODFLOOR = "WOOD GROUND",
		TURF_DESERTDIRT = "GROUND PARTS",
		TURF_FUNGUS_GREEN = "GROUND PARTS",
		TURF_FUNGUS_RED = "GROUND PARTS",
		TURF_DRAGONFLY = "CONDITION: INFLAMMABLE. WAIT. NOT FLAMMABLE?",
		TURKEYDINNER = "FESTIVE",
		INSPECTSELF = "THERE IS A HANDSOME ROBOT TRAPPED IN THIS LOOK-DEVICE!",
		TWIGS = "STICKS",
		TWIGGYTREE = 
        {
            BURNING = "SOON THERE WILL BE NOTHING LEFT",
			BURNT = "YOU LOSE.",
			CHOPPED = "THE NATURAL WORLD IS OVERRATED",
            GENERIC = "AN EVEN MORE PATHETIC TREE",           
            DISEASED = "HA. DISEASE. A BIOLOGICAL LAPSE IN JUDGMENT",
        },
        TWIGGY_NUT_SAPLING = "IT'S TAKING FOREVER TO GROW",
        TWIGGY_OLD = "PATHETIC.",
        TWIGGY_NUT = "TWIGGY TREE SOURCE CODE",
		UMBRELLA = "THIS WILL KEEP ME RUST FREE",
		WAFFLES = "ERROR: TOO DELICIOUS!",
		WALL_HAY_ITEM = "NOT VERY GOOD DEFENSES",
		WALL_STONE = "THAT MAKES ME FEEL SAFE",
		WALL_STONE_ITEM = "STONE DEFENSES",
		WALL_RUINS = "OLD BUT STILL FUNCTIONAL",
		WALL_RUINS_ITEM = "POCKET STONE DEFENSE",
		WALL_WOOD_ITEM = "WOODEN DEFENSES",
		WALL_MOONROCK = "WELCOME TO THE WX-78 MOONBASE",
		WALL_MOONROCK_ITEM = "CAN THIS BUILD A MOONBASE?",
		FENCE = "KEEPS IN FLESHLINGS",
        FENCE_ITEM = "FENCE ASSEMBLY REQUIRED",
        FENCE_GATE = "KEEPS OUT FLESHLINGS",
        FENCE_GATE_ITEM = "GATE ASSEMBLY REQUIRED",
		WALRUS = "I DON'T LIKE THE LOOK OF HIM",
		WALRUSHAT = "SMELLS LIKE MAMMAL",
		WALRUS_CAMP =
		{
			EMPTY = "WHERE ARE THEY?",
			GENERIC = "I HEAR A FAINT OORKING",
		},
		WALRUS_TUSK = "IT WASN'T MUCH HELP TO ITS ORIGINAL OWNER",
		MOOSE_NESTING_GROUND = "ORGANIC SPAWNPOINT",
		WARDROBE = 
		{
			GENERIC = "ROBOTS ARE NOT INTERESTED IN FASHION",
            BURNING = "DEACTIVATION INITIATED",
			BURNT = "PERMANENTLY DEACTIVATED",
		},
		WARG = "IT LIVES TO EAT LARGE THINGS",
		WASPHIVE = "A BEAUTIFUL EXAMPLE OF EFFICIENCY",
		WATERBALLOON = "KEEP THAT AWAY FROM MY CIRCUITS!",
		WETGOOP = "EDIBLE FILTH",
        WHIP = "I WILL COMMAND THE MEATLINGS",
		WINTERHAT = "THIS WILL KEEP MY PROCESSOR FROM FREEZING",
       
        WINTER_TREE =
        {
            BURNT = "WAS THAT PART OF THE FEAST RITUAL, MINIONS?",
            BURNING = "RECOMPENSE FOR YOUR HUMAN TREE LIES",
            CANDECORATE = "IT'S JUST A TREE... WE ARE SURROUNDED BY HUNDREDS OF THEM",
            YOUNG = "I AWAIT THE SPECIAL TREE. WILL IT ENSLAVE HUMANITY?",
        },
 		WINTER_TREESTAND = 
		{
			GENERIC = "MY MINIONS HAVE PROMISED IT WILL GROW A SPECIAL TREE",
            BURNT =  "WAS THAT PART OF THE FEAST RITUAL, MINIONS?",
		},
        WINTER_ORNAMENT = "WHAT OBSERVABLE APPEAL IS THERE IN FRAGILITY?",
        WINTER_ORNAMENTLIGHT = "WE ARE DECORATING WITH ROBOT GUTS",
        WINTER_ORNAMENTBOSS = "I DO NOT UNDERSTAND THIS RITUAL",

        WINTER_FOOD1 = "WHERE ARE THE ROBOT-SHAPED CONFECTIONS", --gingerbread cookie
        WINTER_FOOD2 = "FLESHLINGS LOVE SHAPING FOOD LIKE NON-FOOD", --sugar cookie
        WINTER_FOOD3 = "A ROD OF CONCENTRATED SUGAR FUEL", --candy cane
        WINTER_FOOD4 = "THIS ENERGY SLAB IS STRONG AND EFFICIENT", --fruitcake
        WINTER_FOOD5 = "THE ORGANICS SHAPED THIS ONE LIKE A LOG", --yule log cake
        WINTER_FOOD6 = "I REQUIRE MORE TREATS", --plum pudding
        WINTER_FOOD7 = "DELICIOUS OBLITERATED APPLES", --apple cider
        WINTER_FOOD8 = "ARE MY INSIDES LIQUID PROOF", --hot cocoa
        WINTER_FOOD9 = "EGG JUICE TO POUR DOWN YOUR FOOD HATCH", --eggnog

        KLAUS = "THE RED FLESHSACK LACKS OPTICAL SENSORS",
        KLAUS_SACK = "VALUABLE POTENTIAL: HIGH",
		WORMHOLE =
		{
			GENERIC = "I WANT TO STEP ON IT",
			OPEN = "THIS MEAT TUBE WILL SERVE MY PURPOSES",
		},
		WORMHOLE_LIMITED = "IT'S PATHETIC-LOOKING",
		ARMORRUINS = "QUICK PUT IT ON ME",
		ARMORSKELETON = "EVIL BODYPANEL UPGRADE",
		SKELETONHAT = "IT IS EVIL, LIKE ME",
		BISHOP_NIGHTMARE = "THERE SEEMS TO BE A BUG IN ITS BELIEF CIRCUITS",
		GREENAMULET = "CONSERVATION OF MASS... IGNORED",	--Reduce cost of crafting
		GREENGEM = "PRESSURE AND IMPURITIES HAVE PRODUCED PLEASING PERFECTION",
		KNIGHT_NIGHTMARE = "REPROGRAMMING REQUIRED",
		MINOTAUR = "THIS MEAT HAS A POINTY END",	--Monster in labyrinth
		--OBSIDIANMACHETE = "HACKING BLADE WITH FIRESTARTING CAPABILITIES",
		--MACHETE = "LONG BLADE FOR HACKING",
		--MOWER = "LONG BLADE FOR HACKING",
		--GOLDENMACHETE = "OSTENTATIOUS HACKING DEVICE",
		MULTITOOL_AXE_PICKAXE = "A PRACTICAL TOOL",	--Works as axe and pickaxe
		NIGHTMARELIGHT = "AN ANCIENT OPTICAL WAVELENGTH EMITTER",	--Lights that activate during nightmare.
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			WARN = "CYCLE MINIMUM HAS PASSED",	--Before nightmare
			WAXING = "INCREMENTAL INCREASE DETECTED", --Nightmare Phase first 33%
			STEADY = "LEVELS ARE HIGH AND MONOTONIC", --Nightmare 33% - 66%
			WANING = "THE CYCLE IS SUBSIDING", --Nightmare 66% +
			DAWN = "LEVELS ARE LOW AND DIMINISHING", --After nightmare
			CALM = "AT CYCLE MINIMUM",	--calm phase
			NOMAGIC = "FLUCTUATIONS AT UNDETECTABLE LEVELS", --Place with no nightmare cycle.
		},
		ORANGESTAFF = "TEMPORAL DISPLACEMENT TECHNOLOGY",	--Teleports player.
		ROOK_NIGHTMARE = "LOOSE WIRING DETECTED",
		RELIC = "I HAVE NO NEED OF THAT.",	--Fixed relic
		RUINS_RUBBLE = "REQUIRES RECONDITIONING",	--Broken relic
		RUINS_BAT = "A HIGH VELOCITY MASS INFLUENCE DEVICE",
		RUINSHAT = "A HEAD-MOUNTED DYNAMIC DAMAGE MITIGATION DEVICE",
		SPIDER_DROPPER = "VERTICAL SPIDER SOURCE DETECTED",	--White spider that comes from the roof
		THULECITE = "A MOST AESTHETICALLY PLEASING MINERAL",
		YELLOWAMULET = "INCANDESCENCE AT 5200000000000000Hz",	--Emits light, player walks faster.
		ACCOMPLISHMENT_SHRINE = "I AM GOOD AT REPEATING TASKS",
		ICESTAFF = "ITS MOLECULES ARE BARELY MOVING",
        REVIVER = "IT UNDOES MEATLING DESTRUCTION",
        SHADOWHEART = "THIS FLESHLING ORGAN PULSES WITH PURE EVIL!",
        ATRIUM_RUBBLE = 
        {
			LINE_1 = "IT DEPICTS INFERIOR CREATURES",
			LINE_2 = "TARGET DATA LOST",
			LINE_3 = "THE CREATURES ARE SUBMERGED IN BEAUTIFUL OIL",
			LINE_4 = "THE CREATURES UPGRADE THEIR BODY PANELS",
			LINE_5 = "IT SHOWS A CITY MADE OF SHINING METAL",
		},
        ATRIUM_STATUE = "A TESTAMENT TO INFERIORITY",
        ATRIUM_LIGHT = 
        {
			ON = "LIGHT SOURCE DETECTED",
			OFF = "THEY LOOK ODD",
		},
        ATRIUM_GATE =
        {
			ON = "POWERED ON",
			OFF = "ERROR 502",
			CHARGING = "GATEWAY CHARGING",
            DESTABILIZING = "IT WAS A DEATHTRAP ALL ALONG",
            COOLDOWN = "COOLDOWN IN PROGRESS",
        },
        ATRIUM_KEY = "FOR ACTIVATING, NOT UNLOCKING",
        LIFEINJECTOR = "I HAVE MIXED FEELINGS ABOUT THIS",
        ROCK_MOON = "A ROCK. FROM THE MOON",
        MOONROCKNUGGET = "A ROCK. FROM THE MOON",
        MOONROCKCRATER = "REQUIRES PLUGIN",

        REDMOONEYE = "WARNING: DO NOT SHOVE INTO EYEHOLES",
        PURPLEMOONEYE = "MOONBASE ADDON DETECTED",
        GREENMOONEYE = "ISLAND POSITIONING SYSTEM ONLINE",
        ORANGEMOONEYE = "TRIANGULATING LENS POSITION",
        YELLOWMOONEYE = "MAJOR IMPROVEMENT ON FLESHLING EYES",
        BLUEMOONEYE = "TERRAIN MAPPING IN PROGRESS",

        --Arena Event
        LAVAARENA_BOARLORD = "YOU ARE UNFIT TO RULE",
        BOARRIOR = "YOU ARE STRONG, BUT STILL ORGANIC",
        BOARON = "LOOK AT IT. IT IS PUNY",
        PEGHOOK = "ITS ACID CORRODES METAL",
        TRAILS = "BRUTISH AND STUPID",
        TURTILLUS = "I AM THE SUPERIOR METAL BEING",
        SNAPPER = "I WILL KILL YOU FIRST",
        
        LAVAARENA_PORTAL = 
        {
        	ON = "READY FOR TRANSPORT",
        	GENERIC = "IT IS INACTIVE",
        },
        LAVAARENA_KEYHOLE = "NO POWER",
        LAVAARENA_KEYHOLE_FULL = "EXCELLENT",
        LAVAARENA_BATTLESTANDARD = "DESTROY THE ENEMY UPGRADER",
        LAVAARENA_SPAWNER = "IT'S AN ENEMY MANUFACTURER",

        HEALINGSTAFF = "KEEP ME IN MINT CONDITION, MINIONS",
        FIREBALLSTAFF = "IT IS USELESS TO ME",
        HAMMER_MJOLNIR = "I WILL SMASH ALL WHO OPPOSE ME",
        SPEAR_GUNGNIR = "AN EXCELLENT TOOL OF TERMINATION",
        BLOWDART_LAVA = "A PITIFUL WEAPON",
        BLOWDART_LAVA2 = "AN INFERIOR WEAPON",
        LAVAARENA_LUCY = "I HAVE NO USE FOR YOU, AXE",
        WEBBER_SPIDER_MINION = "HOW WILL MINISCULE, SQUISHABLE SPIDERS HELP US",
        BOOK_FOSSIL = "READING IS NOT VERY EVIL",
		LAVAARENA_BERNIE = "I WILL USE THIS BEAR TO SHIELD ME",
		SPEAR_LANCE = "I WILL DESTROY EVERYTHING",
		BOOK_ELEMENTAL = "A BOOK IS NOT A WEAPON",
		LAVAARENA_ELEMENTAL = "IT IS A MINION FOR MY MINIONS",

        LAVAARENA_ARMORLIGHT = "PATHETIC",
		LAVAARENA_ARMORLIGHTSPEED = "I HAVE NO USE FOR THAT",
		LAVAARENA_ARMORMEDIUM = "IT IS ONLY BARELY SUFFICIENT",
		LAVAARENA_ARMORMEDIUMDAMAGER = "I WILL BE POWERFUL",
		LAVAARENA_ARMORMEDIUMRECHARGER = "INITIATING OVERCLOCK PROCEDURE",
		LAVAARENA_ARMORHEAVY = "A SUITABLE SUIT OF ARMOR",
		LAVAARENA_ARMOREXTRAHEAVY = "DETECTING: CHASSIS UPGRADE",

		LAVAARENA_FEATHERCROWNHAT = "IMPROVED RUNTIME",
        LAVAARENA_HEALINGFLOWERHAT = "SURRENDER YOUR POWER TO ME, PLANT",
        LAVAARENA_LIGHTDAMAGERHAT = "IT WILL MAKE ME STRONGER",
        LAVAARENA_STRONGDAMAGERHAT = "YES. I LIKE THIS",
        LAVAARENA_TIARAFLOWERPETALSHAT = "A PATHETIC ORGANIC HAT",
        LAVAARENA_EYECIRCLETHAT = "I AM NOT PROGRAMMED FOR THAT",
        LAVAARENA_RECHARGERHAT = "IT IS A COOLING UPGRADE",
        LAVAARENA_HEALINGGARLANDHAT = "ENHANCED COOLING SYSTEMS",
        LAVAARENA_CROWNDAMAGERHAT = "CLEARLY I SHOULD WEAR IT",
	},
	DESCRIBE_GENERIC = "ERROR: UNKNOWN",
	DESCRIBE_TOODARK = "INSUFFICIENT ILLUMINATION",
	DESCRIBE_SMOLDERING = "OBJECT NEARING IGNITION POINT",

	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "TRACES OF BEAK DETECTED",
	},
}
