return {
  version = "1.1",
  luaversion = "5.1",
  orientation = "orthogonal",
  width = 38,
  height = 38,
  tilewidth = 64,
  tileheight = 64,
  properties = {},
  tilesets = {
    {
      name = "ground",
      firstgid = 1,
      filename = "../../../../tools/tiled/dont_starve/ground.tsx",
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "../../../../tools/tiled/dont_starve/tiles.png",
      imagewidth = 512,
      imageheight = 512,
      properties = {},
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "BG_TILES",
      x = 0,
      y = 0,
      width = 38,
      height = 38,
      visible = true,
      opacity = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 13, 13, 13, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0, 0, 43, 43, 0, 0, 0, 0, 0,
        13, 13, 13, 13, 13, 13, 0, 0, 0, 0, 0, 0, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0, 0, 0,
        13, 13, 13, 13, 13, 0, 0, 0, 0, 0, 0, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0, 0,
        0, 13, 13, 13, 13, 0, 0, 0, 0, 0, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0, 0,
        0, 13, 13, 13, 13, 0, 0, 0, 0, 0, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0, 0,
        0, 13, 13, 13, 13, 13, 0, 0, 0, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0, 0,
        13, 13, 13, 13, 13, 13, 0, 0, 43, 13, 13, 13, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0, 0,
        13, 13, 13, 13, 13, 13, 13, 43, 43, 13, 13, 13, 43, 43, 43, 13, 13, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0,
        13, 13, 13, 13, 13, 13, 13, 43, 13, 13, 43, 43, 43, 13, 13, 13, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0,
        13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 43, 43, 13, 13, 13, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0,
        0, 13, 13, 13, 13, 13, 13, 13, 13, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
        13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
        13, 13, 13, 13, 13, 13, 13, 43, 43, 13, 13, 13, 13, 13, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
        13, 13, 13, 13, 13, 13, 13, 13, 43, 43, 43, 13, 13, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
        13, 13, 13, 13, 13, 13, 13, 13, 13, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0,
        13, 13, 13, 13, 13, 13, 13, 43, 13, 13, 43, 43, 13, 13, 13, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0,
        13, 13, 13, 13, 13, 13, 13, 43, 13, 13, 13, 43, 43, 13, 13, 13, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0,
        13, 13, 13, 13, 13, 13, 13, 13, 13, 43, 13, 13, 13, 43, 43, 13, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0,
        0, 0, 13, 13, 13, 13, 13, 13, 13, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0, 0, 0,
        0, 0, 0, 0, 13, 13, 13, 43, 43, 43, 13, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 13, 13, 43, 43, 43, 13, 13, 13, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 43, 43, 43, 43, 13, 13, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0, 0, 43, 43, 43, 43, 43, 43, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43, 43, 43, 43, 43, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43, 43, 43, 43, 43, 43, 43, 43, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43, 43, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 0, 0, 4, 0, 0, 4, 4, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 0, 4, 4, 0, 0, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 0, 4, 4, 4, 4, 4, 0, 0, 0, 0, 4, 4, 4, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "retrofit_archiveteleporter",
          shape = "rectangle",
          x = 190,
          y = 261,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS_BLUE_MUSH",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1197,
          y = 1433,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_waterfall_small1",
          shape = "rectangle",
          x = 1964,
          y = 892,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_big",
          shape = "rectangle",
          x = 1784,
          y = 677,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_big",
          shape = "rectangle",
          x = 1792,
          y = 1302,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_big",
          shape = "rectangle",
          x = 1186,
          y = 1686,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_small",
          shape = "rectangle",
          x = 1872,
          y = 376,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_small",
          shape = "rectangle",
          x = 1528,
          y = 456,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_small",
          shape = "rectangle",
          x = 1310,
          y = 1076,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_small",
          shape = "rectangle",
          x = 1746,
          y = 1510,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_small",
          shape = "rectangle",
          x = 974,
          y = 1648,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_small",
          shape = "rectangle",
          x = 1094,
          y = 356,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_small",
          shape = "rectangle",
          x = 1236,
          y = 912,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_small",
          shape = "rectangle",
          x = 2222,
          y = 934,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_small",
          shape = "rectangle",
          x = 1504,
          y = 1728,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "grotto_pool_small",
          shape = "rectangle",
          x = 1438,
          y = 600,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1266,
          y = 1378,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1288,
          y = 1500,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2064,
          y = 1114,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1973,
          y = 1047,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2042,
          y = 992,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1772,
          y = 922,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1681,
          y = 855,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1750,
          y = 800,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1600,
          y = 1022,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1595,
          y = 955,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1664,
          y = 900,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1954,
          y = 1530,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1863,
          y = 1463,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1928,
          y = 1370,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1590,
          y = 1704,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1499,
          y = 1637,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1508,
          y = 1488,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1618,
          y = 1512,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1527,
          y = 1445,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1596,
          y = 1390,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1462,
          y = 1272,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1371,
          y = 1205,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1382,
          y = 1264,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1404,
          y = 804,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1287,
          y = 749,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1372,
          y = 712,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1178,
          y = 754,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1097,
          y = 745,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1164,
          y = 658,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1730,
          y = 398,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1639,
          y = 331,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1708,
          y = 276,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1490,
          y = 146,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1813,
          y = 313,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1882,
          y = 258,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1364,
          y = 254,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1273,
          y = 187,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1342,
          y = 132,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1166,
          y = 366,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1075,
          y = 299,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 978,
          y = 402,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 776,
          y = 1692,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 641,
          y = 1667,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 710,
          y = 1612,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1028,
          y = 1968,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 937,
          y = 1901,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1000,
          y = 1804,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2280,
          y = 1766,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2189,
          y = 1699,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2258,
          y = 1644,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2178,
          y = 1908,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2087,
          y = 1841,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2008,
          y = 1740,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2138,
          y = 1710,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2047,
          y = 1643,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2088,
          y = 1934,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1082,
          y = 1094,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 991,
          y = 1027,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1040,
          y = 910,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 688,
          y = 1100,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 597,
          y = 1033,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 666,
          y = 978,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 838,
          y = 472,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 747,
          y = 405,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 816,
          y = 350,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 616,
          y = 804,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 889,
          y = 546,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 608,
          y = 584,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1002,
          y = 1378,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 911,
          y = 1311,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 980,
          y = 1256,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2202,
          y = 530,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2111,
          y = 463,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2180,
          y = 408,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2052,
          y = 686,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2109,
          y = 626,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2030,
          y = 564,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1366,
          y = 1862,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1275,
          y = 1795,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 1494,
          y = 1894,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2194,
          y = 1850,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2216,
          y = 1942,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2318,
          y = 1824,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_moon",
          shape = "rectangle",
          x = 2284,
          y = 1860,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "lightflier_flower",
          shape = "rectangle",
          x = 1221,
          y = 1221,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "lightflier_flower",
          shape = "rectangle",
          x = 1913,
          y = 1075,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "lightflier_flower",
          shape = "rectangle",
          x = 1726,
          y = 620,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "lightflier_flower",
          shape = "rectangle",
          x = 1834,
          y = 542,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "lightflier_flower",
          shape = "rectangle",
          x = 2000,
          y = 678,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "lightflier_flower",
          shape = "rectangle",
          x = 1028,
          y = 1482,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "lightflier_flower",
          shape = "rectangle",
          x = 1352,
          y = 1636,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "lightflier_flower",
          shape = "rectangle",
          x = 772,
          y = 1762,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "lightflier_flower",
          shape = "rectangle",
          x = 842,
          y = 1804,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "lightflier_flower",
          shape = "rectangle",
          x = 930,
          y = 356,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "lightflier_flower",
          shape = "rectangle",
          x = 1126,
          y = 468,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "lightflier_flower",
          shape = "rectangle",
          x = 782,
          y = 802,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "lightflier_flower",
          shape = "rectangle",
          x = 716,
          y = 1192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "lightflier_flower",
          shape = "rectangle",
          x = 2058,
          y = 1222,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "lightflier_flower",
          shape = "rectangle",
          x = 1878,
          y = 1740,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "lightflier_flower",
          shape = "rectangle",
          x = 2242,
          y = 1748,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushgnome_spawner",
          shape = "rectangle",
          x = 1236,
          y = 1524,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushgnome_spawner",
          shape = "rectangle",
          x = 2178,
          y = 1000,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushgnome_spawner",
          shape = "rectangle",
          x = 1562,
          y = 340,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon_small",
          shape = "rectangle",
          x = 1788,
          y = 682,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon_small",
          shape = "rectangle",
          x = 1178,
          y = 1692,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon_small",
          shape = "rectangle",
          x = 1798,
          y = 1300,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon_small",
          shape = "rectangle",
          x = 1874,
          y = 380,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon_small",
          shape = "rectangle",
          x = 1530,
          y = 456,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon_small",
          shape = "rectangle",
          x = 1312,
          y = 1080,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon_small",
          shape = "rectangle",
          x = 1748,
          y = 1512,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon_small",
          shape = "rectangle",
          x = 978,
          y = 1652,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon_small",
          shape = "rectangle",
          x = 1094,
          y = 356,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon_small",
          shape = "rectangle",
          x = 1238,
          y = 908,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon_small",
          shape = "rectangle",
          x = 2226,
          y = 936,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon_small",
          shape = "rectangle",
          x = 1502,
          y = 1724,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon_small",
          shape = "rectangle",
          x = 1442,
          y = 602,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon",
          shape = "rectangle",
          x = 1382,
          y = 1468,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon",
          shape = "rectangle",
          x = 1470,
          y = 1156,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon",
          shape = "rectangle",
          x = 1788,
          y = 1090,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon",
          shape = "rectangle",
          x = 1408,
          y = 898,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon",
          shape = "rectangle",
          x = 1522,
          y = 636,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon",
          shape = "rectangle",
          x = 1224,
          y = 476,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon",
          shape = "rectangle",
          x = 866,
          y = 1662,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon",
          shape = "rectangle",
          x = 2114,
          y = 730,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon",
          shape = "rectangle",
          x = 802,
          y = 608,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavelightmoon",
          shape = "rectangle",
          x = 606,
          y = 1252,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS_MOON_MUSH",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 176,
          y = 827,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 326,
          y = 502,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 120,
          y = 570,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 271,
          y = 453,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 341,
          y = 763,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall_webbed",
          shape = "rectangle",
          x = 317,
          y = 995,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 108,
          y = 695,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 243,
          y = 720,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 276,
          y = 640,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 84,
          y = 1010,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 251,
          y = 1078,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 27,
          y = 1185,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 65,
          y = 1133,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "dropperweb",
          shape = "rectangle",
          x = 219,
          y = 958,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 298,
          y = 292,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 95,
          y = 415,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 22,
          y = 571,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 330,
          y = 590,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 130,
          y = 511,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 63,
          y = 223,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 98,
          y = 156,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 351,
          y = 692,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 228,
          y = 749,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall_webbed",
          shape = "rectangle",
          x = 152,
          y = 983,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 139,
          y = 1052,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 295,
          y = 1052,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 109,
          y = 1172,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 169,
          y = 1232,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 75,
          y = 683,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 76,
          y = 937,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 283,
          y = 343,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 141,
          y = 403,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 233,
          y = 628,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 383,
          y = 756,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 403,
          y = 931,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 27,
          y = 949,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 144,
          y = 1159,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 37,
          y = 293,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 368,
          y = 967,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 45,
          y = 849,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 993,
          y = 623,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 865,
          y = 743,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 675,
          y = 604,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 715,
          y = 936,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 783,
          y = 883,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 628,
          y = 885,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 867,
          y = 1132,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 984,
          y = 1199,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 759,
          y = 1496,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 781,
          y = 1261,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 557,
          y = 1247,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 599,
          y = 1128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 493,
          y = 1041,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 472,
          y = 755,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 503,
          y = 852,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 531,
          y = 692,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 787,
          y = 963,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 556,
          y = 1143,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 940,
          y = 1189,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 668,
          y = 676,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 731,
          y = 1085,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 787,
          y = 1360,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 515,
          y = 1419,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double",
          shape = "rectangle",
          x = 212,
          y = 1022,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double",
          shape = "rectangle",
          x = 104,
          y = 338,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double",
          shape = "rectangle",
          x = 368,
          y = 808,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave",
          shape = "rectangle",
          x = 174,
          y = 470,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave",
          shape = "rectangle",
          x = 302,
          y = 878,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave",
          shape = "rectangle",
          x = 190,
          y = 1130,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_triple",
          shape = "rectangle",
          x = 208,
          y = 680,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "blue_mushroom",
          shape = "rectangle",
          x = 146,
          y = 752,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "blue_mushroom",
          shape = "rectangle",
          x = 238,
          y = 790,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "blue_mushroom",
          shape = "rectangle",
          x = 166,
          y = 930,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "blue_mushroom",
          shape = "rectangle",
          x = 320,
          y = 928,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "blue_mushroom",
          shape = "rectangle",
          x = 298,
          y = 162,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "blue_mushroom",
          shape = "rectangle",
          x = 246,
          y = 346,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "blue_mushroom",
          shape = "rectangle",
          x = 82,
          y = 1084,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "blue_mushroom",
          shape = "rectangle",
          x = 54,
          y = 1210,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "dropperweb",
          shape = "rectangle",
          x = 344,
          y = 1230,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall_webbed",
          shape = "rectangle",
          x = 384,
          y = 1168,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall_webbed",
          shape = "rectangle",
          x = 282,
          y = 1232,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave",
          shape = "rectangle",
          x = 386,
          y = 1336,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 314,
          y = 1338,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "mushtree_tall",
          shape = "rectangle",
          x = 354,
          y = 1420,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "blue_mushroom",
          shape = "rectangle",
          x = 428,
          y = 1308,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS_BRIDGE",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1760,
          y = 2272,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1787,
          y = 2252,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1819,
          y = 2290,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1715,
          y = 2203,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1865,
          y = 2244,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1908,
          y = 2289,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1943,
          y = 2247,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1963,
          y = 2326,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1981,
          y = 2300,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1984,
          y = 2357,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1885,
          y = 2201,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1649,
          y = 2183,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1663,
          y = 2235,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 2028,
          y = 2301,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 2062,
          y = 2341,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 2053,
          y = 2255,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1543,
          y = 2261,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1569,
          y = 2315,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1509,
          y = 2247,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1647,
          y = 2351,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1565,
          y = 2360,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1514,
          y = 2353,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1610,
          y = 2197,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1473,
          y = 2316,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1490,
          y = 2357,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 2039,
          y = 2279,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1971,
          y = 2275,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 2016,
          y = 2327,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1920,
          y = 2263,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1891,
          y = 2229,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1817,
          y = 2264,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1854,
          y = 2292,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1761,
          y = 2249,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1692,
          y = 2232,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1670,
          y = 2208,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1585,
          y = 2253,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1597,
          y = 2336,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1562,
          y = 2286,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1533,
          y = 2339,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1495,
          y = 2323,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1491,
          y = 2272,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1643,
          y = 2315,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1733,
          y = 2271,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 2004,
          y = 2245,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 2133,
          y = 2221,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 2226,
          y = 2148,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 2130,
          y = 2196,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 2079,
          y = 2224,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 2157,
          y = 2181,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1426,
          y = 2331,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1369,
          y = 2294,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1358,
          y = 2373,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1380,
          y = 2352,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1335,
          y = 2289,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1430,
          y = 2367,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1391,
          y = 2253,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1358,
          y = 2328,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1459,
          y = 2421,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1409,
          y = 2406,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1455,
          y = 2385,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1190,
          y = 2343,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1200,
          y = 2314,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cavein_boulder",
          shape = "rectangle",
          x = 1217,
          y = 2345,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1263,
          y = 2321,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS_ROOF ITEMS",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "pillar_stalactite",
          shape = "rectangle",
          x = 1720,
          y = 456,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "pillar_stalactite",
          shape = "rectangle",
          x = 1614,
          y = 702,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "pillar_stalactite",
          shape = "rectangle",
          x = 1864,
          y = 790,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "pillar_stalactite",
          shape = "rectangle",
          x = 1526,
          y = 1328,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "pillar_stalactite",
          shape = "rectangle",
          x = 1952,
          y = 472,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "pillar_stalactite",
          shape = "rectangle",
          x = 1751,
          y = 1401,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "pillar_stalactite",
          shape = "rectangle",
          x = 1341,
          y = 1571,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "pillar_stalactite",
          shape = "rectangle",
          x = 1761,
          y = 1655,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "pillar_stalactite",
          shape = "rectangle",
          x = 1122,
          y = 1546,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "pillar_stalactite",
          shape = "rectangle",
          x = 2080,
          y = 845,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "pillar_cave",
          shape = "rectangle",
          x = 1630,
          y = 584,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "pillar_cave",
          shape = "rectangle",
          x = 1880,
          y = 954,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "pillar_cave",
          shape = "rectangle",
          x = 1422,
          y = 1384,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "pillar_cave",
          shape = "rectangle",
          x = 1932,
          y = 1604,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "pillar_cave",
          shape = "rectangle",
          x = 1344,
          y = 766,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "pillar_cave",
          shape = "rectangle",
          x = 1302,
          y = 338,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS_WAR",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "retrofitted_grotterwar_spawnpoint",
          shape = "rectangle",
          x = 343,
          y = 640,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "retrofitted_grotterwar_spawnpoint",
          shape = "rectangle",
          x = 273,
          y = 800,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "retrofitted_grotterwar_spawnpoint",
          shape = "rectangle",
          x = 329,
          y = 919,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "retrofitted_grotterwar_spawnpoint",
          shape = "rectangle",
          x = 379,
          y = 1049,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "retrofitted_grotterwar_spawnpoint",
          shape = "rectangle",
          x = 288,
          y = 1152,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "retrofitted_grotterwar_spawnpoint",
          shape = "rectangle",
          x = 328,
          y = 1264,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "retrofitted_grotterwar_spawnpoint",
          shape = "rectangle",
          x = 371,
          y = 1369,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "retrofitted_grotterwar_homepoint",
          shape = "rectangle",
          x = 995,
          y = 1121,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
