return {
  version = "1.1",
  luaversion = "5.1",
  orientation = "orthogonal",
  width = 20,
  height = 20,
  tilewidth = 64,
  tileheight = 64,
  properties = {},
  tilesets = {
    {
      name = "ground",
      firstgid = 1,
      filename = "../../../../tools/tiled/dont_starve/ground.tsx",
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "../../../../tools/tiled/dont_starve/tiles.png",
      imagewidth = 512,
      imageheight = 384,
      properties = {},
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "BG_TILES",
      x = 0,
      y = 0,
      width = 20,
      height = 20,
      visible = true,
      opacity = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 0, 0, 0, 0,
        0, 0, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 0, 0, 0,
        0, 18, 18, 18, 18, 18, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 0, 0,
        0, 18, 18, 18, 17, 17, 17, 41, 41, 41, 41, 41, 41, 17, 17, 17, 18, 18, 0, 0,
        18, 18, 17, 17, 17, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 17, 17, 18, 18, 0,
        18, 18, 17, 34, 34, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 17, 18, 18, 0,
        18, 18, 17, 34, 34, 41, 41, 41, 41, 41, 17, 17, 17, 41, 41, 41, 17, 18, 18, 0,
        18, 18, 17, 34, 34, 41, 41, 41, 41, 17, 17, 18, 17, 17, 41, 41, 17, 18, 18, 0,
        18, 18, 17, 34, 34, 34, 41, 41, 41, 17, 18, 18, 18, 17, 41, 41, 17, 18, 18, 0,
        18, 18, 17, 34, 34, 34, 34, 34, 41, 17, 17, 18, 18, 17, 17, 41, 17, 18, 18, 0,
        18, 18, 17, 17, 34, 34, 34, 34, 34, 34, 17, 17, 18, 18, 17, 17, 17, 18, 18, 0,
        18, 18, 18, 17, 34, 34, 34, 34, 34, 34, 34, 17, 18, 18, 18, 18, 18, 18, 0, 0,
        18, 18, 17, 17, 41, 34, 34, 34, 34, 34, 34, 17, 18, 18, 18, 18, 18, 0, 0, 0,
        18, 18, 17, 41, 41, 34, 34, 34, 34, 34, 34, 17, 18, 18, 18, 18, 0, 0, 0, 0,
        18, 18, 17, 41, 41, 41, 41, 34, 34, 41, 41, 17, 18, 18, 18, 18, 0, 0, 0, 0,
        0, 18, 17, 17, 41, 41, 41, 41, 41, 41, 17, 17, 18, 18, 18, 0, 0, 0, 0, 0,
        0, 18, 18, 17, 17, 41, 41, 41, 41, 17, 17, 18, 18, 18, 0, 0, 0, 0, 0, 0,
        0, 18, 18, 18, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 0, 0, 0, 0, 0, 0,
        0, 0, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 18, 18, 18, 18, 18, 18, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "hermithouse_construction1",
          shape = "rectangle",
          x = 444,
          y = 766,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "meatrack_hermit",
          shape = "rectangle",
          x = 383,
          y = 359,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "meatrack_hermit",
          shape = "rectangle",
          x = 517,
          y = 321,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "meatrack_hermit",
          shape = "rectangle",
          x = 395,
          y = 437,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "meatrack_hermit",
          shape = "rectangle",
          x = 491,
          y = 397,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "meatrack_hermit",
          shape = "rectangle",
          x = 435,
          y = 508,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "meatrack_hermit",
          shape = "rectangle",
          x = 523,
          y = 460,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "beebox_hermit",
          shape = "rectangle",
          x = 793,
          y = 303,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "shell_cluster",
          shape = "rectangle",
          x = 999,
          y = 771,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "shell_cluster",
          shape = "rectangle",
          x = 821,
          y = 909,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "shell_cluster",
          shape = "rectangle",
          x = 97,
          y = 505,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "shell_cluster",
          shape = "rectangle",
          x = 679,
          y = 1125,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "shell_cluster",
          shape = "rectangle",
          x = 843,
          y = 1012,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "shell_cluster",
          shape = "rectangle",
          x = 52,
          y = 638,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "singingshell_octave5",
          shape = "rectangle",
          x = 470,
          y = 318,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "singingshell_octave4",
          shape = "rectangle",
          x = 419,
          y = 958,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 608,
          y = 721,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 985,
          y = 504,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 648,
          y = 770,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 938,
          y = 515,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree",
          shape = "rectangle",
          x = 304,
          y = 549,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 320,
          y = 931,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 890,
          y = 362,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "singingshell_octave4",
          shape = "rectangle",
          x = 833,
          y = 366,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree",
          shape = "rectangle",
          x = 554,
          y = 891,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_marker",
          shape = "rectangle",
          x = 574,
          y = 640,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "shell_cluster",
          shape = "rectangle",
          x = 887,
          y = 820,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "shell_cluster",
          shape = "rectangle",
          x = 735,
          y = 542,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "shell_cluster",
          shape = "rectangle",
          x = 804,
          y = 668,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "singingshell_octave4",
          shape = "rectangle",
          x = 394,
          y = 1025,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "singingshell_octave5",
          shape = "rectangle",
          x = 852,
          y = 287,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "singingshell_octave3",
          shape = "rectangle",
          x = 615,
          y = 948,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 615,
          y = 228,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 569,
          y = 385,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 979,
          y = 414,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 908,
          y = 308,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 234,
          y = 880,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 314,
          y = 1000,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 428,
          y = 1040,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 362,
          y = 277,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 727,
          y = 347,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 487,
          y = 599,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 993,
          y = 472,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 666,
          y = 740,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree",
          shape = "rectangle",
          x = 274,
          y = 362,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree",
          shape = "rectangle",
          x = 336,
          y = 621,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree",
          shape = "rectangle",
          x = 294,
          y = 677,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree",
          shape = "rectangle",
          x = 252,
          y = 584,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree",
          shape = "rectangle",
          x = 386,
          y = 606,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree",
          shape = "rectangle",
          x = 365,
          y = 543,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_marker_fishing",
          shape = "rectangle",
          x = 805,
          y = 831,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_marker_fishing",
          shape = "rectangle",
          x = 1147,
          y = 445,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_marker_fishing",
          shape = "rectangle",
          x = 765,
          y = 575,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_marker_fishing",
          shape = "rectangle",
          x = 105,
          y = 235,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_marker_fishing",
          shape = "rectangle",
          x = 352,
          y = 61,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_marker_fishing",
          shape = "rectangle",
          x = 601,
          y = 66,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_marker_fishing",
          shape = "rectangle",
          x = 923,
          y = 69,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_marker_fishing",
          shape = "rectangle",
          x = 29,
          y = 581,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_marker_fishing",
          shape = "rectangle",
          x = 97,
          y = 1055,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_marker_fishing",
          shape = "rectangle",
          x = 236,
          y = 1184,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_marker_fishing",
          shape = "rectangle",
          x = 600,
          y = 1188,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_marker_fishing",
          shape = "rectangle",
          x = 793,
          y = 1048,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_marker_fishing",
          shape = "rectangle",
          x = 805,
          y = 701,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_marker_fishing",
          shape = "rectangle",
          x = 25,
          y = 823,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_marker_fishing",
          shape = "rectangle",
          x = 32,
          y = 379,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_marker_fishing",
          shape = "rectangle",
          x = 1088,
          y = 739,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "singingshell_octave5",
          shape = "rectangle",
          x = 769,
          y = 235,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "singingshell_octave4",
          shape = "rectangle",
          x = 985,
          y = 549,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "singingshell_octave3",
          shape = "rectangle",
          x = 555,
          y = 1011,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree",
          shape = "rectangle",
          x = 628,
          y = 829,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 543,
          y = 513,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_tall",
          shape = "rectangle",
          x = 597,
          y = 297,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_small1",
          shape = "rectangle",
          x = 909,
          y = 411,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_small2",
          shape = "rectangle",
          x = 515,
          y = 1037,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure_plugged",
          shape = "rectangle",
          x = 537,
          y = 736,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure_plugged",
          shape = "rectangle",
          x = 258,
          y = 492,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure_plugged",
          shape = "rectangle",
          x = 375,
          y = 850,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hermitcrab_lure_marker",
          shape = "rectangle",
          x = 716,
          y = 288,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flint",
          shape = "rectangle",
          x = 954,
          y = 480,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "twigs",
          shape = "rectangle",
          x = 676,
          y = 323,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 588,
          y = 814,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 229,
          y = 428,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass",
          shape = "rectangle",
          x = 591,
          y = 782,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass",
          shape = "rectangle",
          x = 552,
          y = 845,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 289,
          y = 411,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass",
          shape = "rectangle",
          x = 280,
          y = 448,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
