return {
  version = "1.1",
  luaversion = "5.1",
  orientation = "orthogonal",
  width = 18,
  height = 18,
  tilewidth = 64,
  tileheight = 64,
  properties = {},
  tilesets = {
    {
      name = "ground",
      firstgid = 1,
      filename = "../../../../tools/tiled/dont_starve/ground.tsx",
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "../../../../tools/tiled/dont_starve/tiles.png",
      imagewidth = 512,
      imageheight = 384,
      properties = {},
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "BG_TILES",
      x = 0,
      y = 0,
      width = 18,
      height = 18,
      visible = true,
      opacity = 1,
      properties = {},
      encoding = "lua",
      data = {
        18, 18, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18,
        17, 17, 17, 33, 33, 33, 34, 34, 34, 34, 34, 34, 34, 17, 17, 17, 18, 18,
        17, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 17, 17, 17,
        17, 33, 33, 34, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 17,
        17, 33, 34, 34, 33, 33, 33, 34, 34, 33, 34, 34, 34, 34, 34, 34, 34, 17,
        17, 33, 34, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17,
        17, 34, 34, 33, 34, 34, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17,
        17, 34, 34, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17, 17,
        17, 34, 33, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17, 18,
        17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17,
        17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17,
        17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17,
        17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17,
        17, 17, 33, 33, 34, 34, 34, 34, 33, 33, 34, 34, 34, 34, 34, 34, 33, 17,
        17, 17, 17, 17, 33, 33, 34, 34, 33, 33, 34, 34, 34, 34, 34, 33, 17, 17,
        18, 18, 18, 17, 33, 33, 33, 33, 33, 34, 34, 34, 34, 33, 33, 33, 33, 17,
        18, 18, 18, 17, 17, 33, 33, 33, 33, 33, 34, 34, 34, 33, 17, 17, 33, 17,
        18, 18, 18, 18, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 207,
          y = 246,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 462,
          y = 632,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 592,
          y = 698,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 450,
          y = 890,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 366,
          y = 600,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hotspring",
          shape = "rectangle",
          x = 488,
          y = 570,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hotspring",
          shape = "rectangle",
          x = 514,
          y = 456,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hotspring",
          shape = "rectangle",
          x = 630,
          y = 410,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hotspring",
          shape = "rectangle",
          x = 520,
          y = 328,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hotspring",
          shape = "rectangle",
          x = 350,
          y = 464,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hotspring",
          shape = "rectangle",
          x = 516,
          y = 706,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 544,
          y = 556,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 526,
          y = 496,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 598,
          y = 388,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 668,
          y = 354,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 926,
          y = 486,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 898,
          y = 624,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 932,
          y = 872,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 738,
          y = 1024,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 724,
          y = 128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 464,
          y = 398,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_avocado_bush",
          shape = "rectangle",
          x = 526,
          y = 628,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_avocado_bush",
          shape = "rectangle",
          x = 568,
          y = 438,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_avocado_bush",
          shape = "rectangle",
          x = 446,
          y = 682,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_avocado_bush",
          shape = "rectangle",
          x = 414,
          y = 490,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_avocado_bush",
          shape = "rectangle",
          x = 912,
          y = 160,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_avocado_bush",
          shape = "rectangle",
          x = 684,
          y = 176,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_avocado_bush",
          shape = "rectangle",
          x = 796,
          y = 654,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS_FOREST",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 838,
          y = 233,
          width = 44,
          height = 23,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 944,
          y = 237,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 850,
          y = 298,
          width = 18,
          height = 55,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 888,
          y = 317,
          width = 21,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree_blossom_worldgen",
          shape = "rectangle",
          x = 956,
          y = 374,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 936,
          y = 332,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1013,
          y = 222,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1019,
          y = 303,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 983,
          y = 368,
          width = 19,
          height = 28,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 970,
          y = 665,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 876,
          y = 726,
          width = 18,
          height = 55,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 914,
          y = 745,
          width = 21,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 935,
          y = 652,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree_blossom_worldgen",
          shape = "rectangle",
          x = 982,
          y = 802,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1039,
          y = 650,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1045,
          y = 731,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 875,
          y = 808,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1009,
          y = 796,
          width = 19,
          height = 28,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fissure_area",
          shape = "rectangle",
          x = 954,
          y = 728,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 654,
          y = 819,
          width = 44,
          height = 23,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 760,
          y = 823,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 666,
          y = 884,
          width = 18,
          height = 55,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 704,
          y = 903,
          width = 21,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree_blossom_worldgen",
          shape = "rectangle",
          x = 772,
          y = 960,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 752,
          y = 918,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 835,
          y = 889,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 665,
          y = 966,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 799,
          y = 954,
          width = 19,
          height = 28,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 696,
          y = 449,
          width = 44,
          height = 23,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 708,
          y = 514,
          width = 18,
          height = 55,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 746,
          y = 533,
          width = 21,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 767,
          y = 440,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree_blossom_worldgen",
          shape = "rectangle",
          x = 814,
          y = 590,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 794,
          y = 548,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 871,
          y = 438,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 877,
          y = 519,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 841,
          y = 584,
          width = 19,
          height = 28,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 737,
          y = 371,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 703,
          y = 689,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 647,
          y = 745,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 775,
          y = 741,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 751,
          y = 181,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 719,
          y = 271,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 593,
          y = 455,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 573,
          y = 603,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 641,
          y = 549,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 639,
          y = 103,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 437,
          y = 495,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS_BEACH",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "trap_starfish",
          shape = "rectangle",
          x = 276,
          y = 140,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "trap_starfish",
          shape = "rectangle",
          x = 404,
          y = 180,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "trap_starfish",
          shape = "rectangle",
          x = 292,
          y = 300,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "trap_starfish",
          shape = "rectangle",
          x = 328,
          y = 958,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "trap_starfish",
          shape = "rectangle",
          x = 416,
          y = 1024,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "trap_starfish",
          shape = "rectangle",
          x = 106,
          y = 208,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "dead_sea_bones",
          shape = "rectangle",
          x = 390,
          y = 296,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "dead_sea_bones",
          shape = "rectangle",
          x = 186,
          y = 158,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "dead_sea_bones",
          shape = "rectangle",
          x = 562,
          y = 216,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "dead_sea_bones",
          shape = "rectangle",
          x = 508,
          y = 1016,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "dead_sea_bones",
          shape = "rectangle",
          x = 1060,
          y = 1046,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "reeds",
          shape = "rectangle",
          x = 474,
          y = 1030,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "reeds",
          shape = "rectangle",
          x = 288,
          y = 970,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "reeds",
          shape = "rectangle",
          x = 228,
          y = 490,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "reeds",
          shape = "rectangle",
          x = 532,
          y = 178,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "reeds",
          shape = "rectangle",
          x = 238,
          y = 84,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_tall",
          shape = "rectangle",
          x = 340,
          y = 122,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_tall",
          shape = "rectangle",
          x = 580,
          y = 884,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_tall",
          shape = "rectangle",
          x = 1018,
          y = 988,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_small1",
          shape = "rectangle",
          x = 122,
          y = 166,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_small1",
          shape = "rectangle",
          x = 84,
          y = 310,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_small1",
          shape = "rectangle",
          x = 1064,
          y = 984,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_small2",
          shape = "rectangle",
          x = 360,
          y = 998,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_small2",
          shape = "rectangle",
          x = 920,
          y = 998,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 296,
          y = 100,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 92,
          y = 262,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 78,
          y = 152,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 218,
          y = 866,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 282,
          y = 918,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 450,
          y = 1054,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 860,
          y = 1034,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 1048,
          y = 1066,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS_MINE",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 166,
          y = 744,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 154,
          y = 676,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 236,
          y = 652,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 334,
          y = 796,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 284,
          y = 732,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 382,
          y = 776,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 406,
          y = 856,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 104,
          y = 732,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 202,
          y = 612,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 224,
          y = 762,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 376,
          y = 750,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 312,
          y = 862,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock2",
          shape = "rectangle",
          x = 316,
          y = 668,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock2",
          shape = "rectangle",
          x = 118,
          y = 798,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock2",
          shape = "rectangle",
          x = 102,
          y = 564,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock2",
          shape = "rectangle",
          x = 226,
          y = 552,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flint",
          shape = "rectangle",
          x = 220,
          y = 704,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flint",
          shape = "rectangle",
          x = 396,
          y = 702,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flint",
          shape = "rectangle",
          x = 452,
          y = 812,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flint",
          shape = "rectangle",
          x = 278,
          y = 802,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flint",
          shape = "rectangle",
          x = 438,
          y = 952,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_moon",
          shape = "rectangle",
          x = 284,
          y = 620,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_moon",
          shape = "rectangle",
          x = 484,
          y = 860,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS_CREATURES",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 482,
          y = 270,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 804,
          y = 800,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 978,
          y = 616,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 1038,
          y = 370,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 856,
          y = 164,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 690,
          y = 424,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 608,
          y = 990,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 606,
          y = 776,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 436,
          y = 754,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 990,
          y = 834,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonspiderden",
          shape = "rectangle",
          x = 886,
          y = 668,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fruitdragon",
          shape = "rectangle",
          x = 536,
          y = 378,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fruitdragon",
          shape = "rectangle",
          x = 486,
          y = 658,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fruitdragon",
          shape = "rectangle",
          x = 568,
          y = 758,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fruitdragon",
          shape = "rectangle",
          x = 404,
          y = 632,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fruitdragon",
          shape = "rectangle",
          x = 420,
          y = 572,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
