return {
  version = "1.1",
  luaversion = "5.1",
  orientation = "orthogonal",
  width = 48,
  height = 48,
  tilewidth = 64,
  tileheight = 64,
  properties = {},
  tilesets = {
    {
      name = "ground",
      firstgid = 1,
      filename = "E:/Klei/DST_Feature/tools/tiled/dont_starve/ground.tsx",
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "E:/Klei/DST_Feature/tools/tiled/dont_starve/tiles.png",
      imagewidth = 512,
      imageheight = 384,
      properties = {},
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "BG_TILES",
      x = 0,
      y = 0,
      width = 48,
      height = 48,
      visible = true,
      opacity = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
        0, 0, 0, 0, 0, 0, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 17, 17, 33, 17, 17, 33, 33, 33, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
        0, 0, 0, 0, 0, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 17, 33, 33, 33, 33, 33, 33, 33, 33, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 0, 0, 18, 18, 18, 18, 18, 18, 18, 18,
        0, 0, 0, 0, 0, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 17, 17, 33, 33, 33, 33, 33, 33, 33, 33, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 17, 33, 33, 33, 33, 33, 33, 33, 33, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 18, 18, 18, 18, 18, 18, 17, 17, 17, 17, 17, 17, 17, 17, 33, 33, 33, 33, 33, 33, 33, 33, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 0, 0, 0, 0, 0,
        0, 0, 0, 18, 18, 18, 18, 18, 17, 17, 33, 33, 33, 17, 17, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 0, 0, 0, 0,
        0, 0, 18, 18, 18, 18, 18, 17, 17, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 17, 17, 17, 17, 17, 34, 34, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 0, 0,
        0, 0, 18, 18, 18, 18, 17, 17, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 17, 17, 17, 17, 34, 3, 34, 34, 34, 3, 3, 3, 34, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 0,
        18, 18, 18, 18, 18, 18, 17, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 3, 3, 34, 34, 34, 34, 3, 3, 34, 34, 34, 3, 3, 34, 34, 34, 17, 18, 18, 18, 18, 18, 18, 18, 18, 0,
        18, 18, 18, 18, 18, 18, 17, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 3, 3, 3, 3, 3, 3, 3, 34, 34, 34, 3, 3, 34, 34, 34, 34, 17, 17, 18, 18, 18, 18, 18, 18, 0, 0,
        0, 18, 18, 18, 18, 18, 17, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 3, 3, 3, 3, 34, 34, 34, 34, 3, 3, 34, 34, 34, 34, 34, 3, 17, 17, 17, 18, 18, 18, 18, 0, 0,
        0, 18, 18, 18, 18, 17, 17, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 3, 3, 34, 34, 34, 34, 3, 3, 34, 34, 34, 34, 34, 3, 3, 34, 3, 17, 17, 18, 18, 18, 0, 0,
        0, 18, 18, 18, 18, 17, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 3, 3, 34, 34, 34, 34, 3, 3, 34, 34, 34, 34, 34, 3, 3, 3, 34, 3, 3, 17, 18, 18, 18, 18, 0,
        18, 18, 18, 18, 18, 17, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 3, 3, 3, 34, 34, 34, 3, 3, 3, 34, 34, 34, 34, 3, 3, 3, 34, 34, 3, 3, 17, 18, 18, 18, 18, 18,
        18, 18, 18, 18, 18, 17, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 3, 3, 3, 34, 34, 34, 3, 3, 3, 3, 34, 34, 34, 34, 17, 18, 18, 18, 18, 18,
        0, 18, 18, 18, 18, 17, 17, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34, 3, 3, 3, 34, 34, 34, 3, 3, 3, 3, 34, 34, 34, 34, 34, 17, 18, 18, 18, 18, 0,
        18, 18, 18, 18, 18, 18, 17, 17, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 34, 3, 3, 3, 3, 34, 34, 34, 3, 3, 3, 34, 34, 34, 3, 3, 17, 17, 18, 18, 18, 0, 0,
        0, 18, 18, 18, 18, 18, 17, 17, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 3, 3, 3, 34, 34, 34, 3, 3, 34, 34, 34, 3, 3, 17, 18, 18, 18, 18, 0, 0,
        0, 18, 18, 18, 18, 17, 17, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 3, 34, 34, 34, 3, 3, 34, 3, 3, 3, 34, 17, 18, 18, 18, 0, 0, 0,
        0, 0, 18, 18, 18, 17, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 3, 3, 3, 3, 34, 34, 17, 18, 18, 18, 0, 0, 0,
        0, 0, 18, 18, 18, 17, 17, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 3, 3, 34, 34, 34, 34, 34, 34, 34, 17, 18, 18, 18, 18, 0, 0,
        0, 0, 18, 18, 18, 18, 17, 17, 33, 33, 33, 17, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17, 34, 34, 3, 3, 3, 34, 34, 34, 34, 34, 17, 17, 18, 18, 18, 18, 18, 0,
        0, 0, 18, 18, 18, 18, 18, 17, 17, 17, 17, 17, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18,
        0, 0, 18, 18, 18, 18, 18, 17, 17, 17, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
        0, 18, 18, 18, 18, 18, 18, 17, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
        18, 18, 18, 18, 17, 17, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18,
        18, 18, 18, 18, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 34, 34, 34, 34, 34, 34, 17, 17, 17, 18,
        18, 18, 18, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 18,
        18, 18, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 18,
        18, 18, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 18,
        18, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 18,
        18, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 18,
        18, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17, 18,
        18, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17, 17, 18, 18,
        18, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17, 17, 18, 18, 18, 0,
        18, 18, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 18, 18, 18, 18, 0, 0,
        18, 18, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17, 17, 18, 18, 0, 0,
        18, 18, 18, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17, 18, 18, 0, 0,
        18, 18, 18, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 18, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17, 18, 18, 18, 0,
        18, 18, 18, 17, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17, 17, 17, 17, 18, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 18, 18, 18, 18,
        18, 18, 18, 18, 18, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17, 18, 18, 18, 18, 18, 18, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 17, 18, 18, 18,
        18, 18, 18, 18, 18, 17, 17, 34, 34, 34, 34, 34, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 18, 18, 18,
        0, 0, 18, 18, 18, 18, 17, 17, 34, 34, 34, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 18, 18, 18,
        0, 0, 18, 18, 18, 18, 18, 17, 17, 34, 34, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 17, 17, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 17, 18, 18, 0,
        0, 0, 18, 18, 18, 18, 18, 18, 17, 34, 34, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 17, 17, 34, 34, 34, 34, 34, 34, 17, 17, 34, 34, 34, 34, 17, 17, 18, 18, 0,
        0, 0, 0, 18, 18, 18, 18, 18, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 0, 0, 0, 0, 0, 0, 0, 0, 18, 18, 18, 18, 17, 17, 17, 34, 34, 34, 17, 17, 17, 34, 34, 34, 17, 17, 18, 18, 0, 0,
        0, 0, 0, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 18, 18, 18, 18, 17, 17, 17, 17, 17, 0, 17, 17, 17, 17, 17, 18, 18, 18, 0, 0
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 930,
          y = 1728,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 1464,
          y = 1788,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 1220,
          y = 1926,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 1542,
          y = 1484,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 1650,
          y = 1286,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 1422,
          y = 1104,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 1182,
          y = 1378,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 1442,
          y = 1550,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hotspring",
          shape = "rectangle",
          x = 1016,
          y = 1650,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hotspring",
          shape = "rectangle",
          x = 1352,
          y = 1838,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hotspring",
          shape = "rectangle",
          x = 1606,
          y = 1740,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hotspring",
          shape = "rectangle",
          x = 1270,
          y = 1652,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hotspring",
          shape = "rectangle",
          x = 1438,
          y = 1410,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hotspring",
          shape = "rectangle",
          x = 1228,
          y = 1294,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "hotspring",
          shape = "rectangle",
          x = 1056,
          y = 1484,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 706,
          y = 1664,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 1258,
          y = 1566,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 1492,
          y = 1260,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 1622,
          y = 1434,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 1468,
          y = 1704,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 868,
          y = 1616,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_avocado_bush",
          shape = "rectangle",
          x = 1364,
          y = 1700,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_avocado_bush",
          shape = "rectangle",
          x = 1480,
          y = 1420,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_avocado_bush",
          shape = "rectangle",
          x = 1098,
          y = 1592,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS_HOTSPRING_CREATURES",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 1558,
          y = 1642,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 1214,
          y = 1476,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 1304,
          y = 1156,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 1002,
          y = 1384,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fruitdragon",
          shape = "rectangle",
          x = 948,
          y = 1622,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fruitdragon",
          shape = "rectangle",
          x = 1018,
          y = 1620,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fruitdragon",
          shape = "rectangle",
          x = 1302,
          y = 1692,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fruitdragon",
          shape = "rectangle",
          x = 1344,
          y = 1660,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fruitdragon",
          shape = "rectangle",
          x = 1544,
          y = 1410,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fruitdragon",
          shape = "rectangle",
          x = 1540,
          y = 1356,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fruitdragon",
          shape = "rectangle",
          x = 1344,
          y = 1320,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS_FOREST_EXTRAS",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "moonspiderden",
          shape = "rectangle",
          x = 773,
          y = 2233,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonspiderden",
          shape = "rectangle",
          x = 2079,
          y = 2124,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 1524,
          y = 2248,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 2086,
          y = 2564,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 2620,
          y = 2622,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 2612,
          y = 1948,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 1760,
          y = 1860,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 1222,
          y = 2022,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 1028,
          y = 1906,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 534,
          y = 2222,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 338,
          y = 1942,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "carrat_planted",
          shape = "rectangle",
          x = 622,
          y = 2844,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 1678,
          y = 2204,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 2062,
          y = 1952,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 1762,
          y = 2006,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 1044,
          y = 2086,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 684,
          y = 1856,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 296,
          y = 2194,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 456,
          y = 2362,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 924,
          y = 2554,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 1084,
          y = 2460,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 1914,
          y = 2630,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 2512,
          y = 2334,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "sapling_moon",
          shape = "rectangle",
          x = 2780,
          y = 1914,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_avocado_bush",
          shape = "rectangle",
          x = 1326,
          y = 2146,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_avocado_bush",
          shape = "rectangle",
          x = 666,
          y = 2252,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_avocado_bush",
          shape = "rectangle",
          x = 642,
          y = 2008,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_avocado_bush",
          shape = "rectangle",
          x = 2400,
          y = 2102,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_avocado_bush",
          shape = "rectangle",
          x = 2114,
          y = 2190,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_avocado_bush",
          shape = "rectangle",
          x = 2566,
          y = 2624,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS_FOREST_TREES",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2094,
          y = 2644,
          width = 44,
          height = 23,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2192,
          y = 2743,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree_blossom_worldgen",
          shape = "rectangle",
          x = 2212,
          y = 2785,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2106,
          y = 2709,
          width = 18,
          height = 55,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2144,
          y = 2728,
          width = 21,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2105,
          y = 2791,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2269,
          y = 2633,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2239,
          y = 2779,
          width = 19,
          height = 28,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2275,
          y = 2714,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2200,
          y = 2648,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2165,
          y = 2635,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fissure_area",
          shape = "rectangle",
          x = 2184,
          y = 2711,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2515,
          y = 2665,
          width = 44,
          height = 23,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2613,
          y = 2764,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree_blossom_worldgen",
          shape = "rectangle",
          x = 2633,
          y = 2806,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2527,
          y = 2730,
          width = 18,
          height = 55,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2565,
          y = 2749,
          width = 21,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2526,
          y = 2812,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2690,
          y = 2654,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2660,
          y = 2800,
          width = 19,
          height = 28,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2696,
          y = 2735,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2621,
          y = 2669,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2586,
          y = 2656,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fissure_area",
          shape = "rectangle",
          x = 2605,
          y = 2732,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2561,
          y = 2008,
          width = 44,
          height = 23,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2659,
          y = 2107,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree_blossom_worldgen",
          shape = "rectangle",
          x = 2679,
          y = 2149,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2573,
          y = 2073,
          width = 18,
          height = 55,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2611,
          y = 2092,
          width = 21,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2572,
          y = 2155,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2736,
          y = 1997,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2706,
          y = 2143,
          width = 19,
          height = 28,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2742,
          y = 2078,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2667,
          y = 2012,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2632,
          y = 1999,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fissure_area",
          shape = "rectangle",
          x = 2651,
          y = 2075,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2218,
          y = 1841,
          width = 44,
          height = 23,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2316,
          y = 1940,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree_blossom_worldgen",
          shape = "rectangle",
          x = 2336,
          y = 1982,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2230,
          y = 1906,
          width = 18,
          height = 55,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2268,
          y = 1925,
          width = 21,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2229,
          y = 1988,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2393,
          y = 1830,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2363,
          y = 1976,
          width = 19,
          height = 28,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2399,
          y = 1911,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2324,
          y = 1845,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2289,
          y = 1832,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fissure_area",
          shape = "rectangle",
          x = 2308,
          y = 1908,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2209,
          y = 2369,
          width = 44,
          height = 23,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2307,
          y = 2468,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree_blossom_worldgen",
          shape = "rectangle",
          x = 2327,
          y = 2510,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2221,
          y = 2434,
          width = 18,
          height = 55,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2259,
          y = 2453,
          width = 21,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2220,
          y = 2516,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2384,
          y = 2358,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2354,
          y = 2504,
          width = 19,
          height = 28,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2390,
          y = 2439,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2315,
          y = 2373,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2280,
          y = 2360,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fissure_area",
          shape = "rectangle",
          x = 2299,
          y = 2436,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1818,
          y = 2084,
          width = 44,
          height = 23,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1916,
          y = 2183,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree_blossom_worldgen",
          shape = "rectangle",
          x = 1936,
          y = 2225,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1830,
          y = 2149,
          width = 18,
          height = 55,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1868,
          y = 2168,
          width = 21,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1829,
          y = 2231,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1993,
          y = 2073,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1963,
          y = 2219,
          width = 19,
          height = 28,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1999,
          y = 2154,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1924,
          y = 2088,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1889,
          y = 2075,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fissure_area",
          shape = "rectangle",
          x = 1908,
          y = 2151,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1185,
          y = 2269,
          width = 44,
          height = 23,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1283,
          y = 2368,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree_blossom_worldgen",
          shape = "rectangle",
          x = 1303,
          y = 2410,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1197,
          y = 2334,
          width = 18,
          height = 55,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1235,
          y = 2353,
          width = 21,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1196,
          y = 2416,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1360,
          y = 2258,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1330,
          y = 2404,
          width = 19,
          height = 28,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1366,
          y = 2339,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1291,
          y = 2273,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1256,
          y = 2260,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fissure_area",
          shape = "rectangle",
          x = 1275,
          y = 2336,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 521,
          y = 2465,
          width = 44,
          height = 23,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 619,
          y = 2564,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree_blossom_worldgen",
          shape = "rectangle",
          x = 639,
          y = 2606,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 533,
          y = 2530,
          width = 18,
          height = 55,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 571,
          y = 2549,
          width = 21,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 532,
          y = 2612,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 696,
          y = 2454,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 666,
          y = 2600,
          width = 19,
          height = 28,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 702,
          y = 2535,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 627,
          y = 2469,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 592,
          y = 2456,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fissure_area",
          shape = "rectangle",
          x = 611,
          y = 2532,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 821,
          y = 2196,
          width = 44,
          height = 23,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 919,
          y = 2295,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree_blossom_worldgen",
          shape = "rectangle",
          x = 939,
          y = 2337,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 833,
          y = 2261,
          width = 18,
          height = 55,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 871,
          y = 2280,
          width = 21,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 832,
          y = 2343,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 996,
          y = 2185,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 966,
          y = 2331,
          width = 19,
          height = 28,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1002,
          y = 2266,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 927,
          y = 2200,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 892,
          y = 2187,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fissure_area",
          shape = "rectangle",
          x = 911,
          y = 2263,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 373,
          y = 1856,
          width = 44,
          height = 23,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 471,
          y = 1955,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree_blossom_worldgen",
          shape = "rectangle",
          x = 491,
          y = 1997,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 385,
          y = 1921,
          width = 18,
          height = 55,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 423,
          y = 1940,
          width = 21,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 384,
          y = 2003,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 548,
          y = 1845,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 518,
          y = 1991,
          width = 19,
          height = 28,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 554,
          y = 1926,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 479,
          y = 1860,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 444,
          y = 1847,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fissure_area",
          shape = "rectangle",
          x = 463,
          y = 1923,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 742,
          y = 1887,
          width = 44,
          height = 23,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 840,
          y = 1986,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree_blossom_worldgen",
          shape = "rectangle",
          x = 860,
          y = 2028,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 754,
          y = 1952,
          width = 18,
          height = 55,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 792,
          y = 1971,
          width = 21,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 753,
          y = 2034,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 917,
          y = 1876,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 887,
          y = 2022,
          width = 19,
          height = 28,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 923,
          y = 1957,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 848,
          y = 1891,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 813,
          y = 1878,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fissure_area",
          shape = "rectangle",
          x = 832,
          y = 1954,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1382,
          y = 1975,
          width = 44,
          height = 23,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1480,
          y = 2074,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_tree_blossom_worldgen",
          shape = "rectangle",
          x = 1500,
          y = 2116,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1394,
          y = 2040,
          width = 18,
          height = 55,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1432,
          y = 2059,
          width = 21,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1393,
          y = 2122,
          width = 79,
          height = 30,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1557,
          y = 1964,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1527,
          y = 2110,
          width = 19,
          height = 28,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1563,
          y = 2045,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1488,
          y = 1979,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1453,
          y = 1966,
          width = 15,
          height = 59,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "fissure_area",
          shape = "rectangle",
          x = 1472,
          y = 2042,
          width = 54,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1672,
          y = 2278,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1915,
          y = 2451,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2248,
          y = 2169,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2554,
          y = 2508,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2388,
          y = 2666,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 2730,
          y = 1808,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1663,
          y = 1863,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1121,
          y = 1754,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 1169,
          y = 2084,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_area",
          shape = "rectangle",
          x = 457,
          y = 2172,
          width = 25,
          height = 50,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS_BEACH",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "trap_starfish",
          shape = "rectangle",
          x = 632,
          y = 1206,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "trap_starfish",
          shape = "rectangle",
          x = 694,
          y = 808,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "trap_starfish",
          shape = "rectangle",
          x = 1348,
          y = 418,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "trap_starfish",
          shape = "rectangle",
          x = 1434,
          y = 202,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "trap_starfish",
          shape = "rectangle",
          x = 892,
          y = 594,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "trap_starfish",
          shape = "rectangle",
          x = 666,
          y = 504,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "dead_sea_bones",
          shape = "rectangle",
          x = 732,
          y = 1340,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "dead_sea_bones",
          shape = "rectangle",
          x = 462,
          y = 976,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "dead_sea_bones",
          shape = "rectangle",
          x = 750,
          y = 660,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "dead_sea_bones",
          shape = "rectangle",
          x = 994,
          y = 948,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "dead_sea_bones",
          shape = "rectangle",
          x = 788,
          y = 1026,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "dead_sea_bones",
          shape = "rectangle",
          x = 1190,
          y = 520,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "dead_sea_bones",
          shape = "rectangle",
          x = 1260,
          y = 210,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "reeds",
          shape = "rectangle",
          x = 616,
          y = 632,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "reeds",
          shape = "rectangle",
          x = 1172,
          y = 390,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "reeds",
          shape = "rectangle",
          x = 1460,
          y = 90,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "reeds",
          shape = "rectangle",
          x = 1528,
          y = 414,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "reeds",
          shape = "rectangle",
          x = 866,
          y = 852,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "reeds",
          shape = "rectangle",
          x = 558,
          y = 1362,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_tall",
          shape = "rectangle",
          x = 1040,
          y = 1022,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_tall",
          shape = "rectangle",
          x = 610,
          y = 938,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_tall",
          shape = "rectangle",
          x = 1204,
          y = 638,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_tall",
          shape = "rectangle",
          x = 1494,
          y = 294,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_small1",
          shape = "rectangle",
          x = 1296,
          y = 326,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_small1",
          shape = "rectangle",
          x = 1022,
          y = 578,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_small1",
          shape = "rectangle",
          x = 546,
          y = 1112,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_small2",
          shape = "rectangle",
          x = 900,
          y = 730,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_small2",
          shape = "rectangle",
          x = 488,
          y = 892,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "driftwood_small2",
          shape = "rectangle",
          x = 772,
          y = 410,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 1592,
          y = 186,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 1192,
          y = 176,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 996,
          y = 412,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 718,
          y = 406,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 552,
          y = 576,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 530,
          y = 808,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 430,
          y = 920,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 518,
          y = 972,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "bullkelp_beachedroot",
          shape = "rectangle",
          x = 494,
          y = 1366,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonspiderden",
          shape = "rectangle",
          x = 1420,
          y = 274,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "twigs",
          shape = "rectangle",
          x = 1060,
          y = 812,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "twigs",
          shape = "rectangle",
          x = 752,
          y = 1032,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "twigs",
          shape = "rectangle",
          x = 774,
          y = 744,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "twigs",
          shape = "rectangle",
          x = 1202,
          y = 332,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rocks",
          shape = "rectangle",
          x = 1088,
          y = 664,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rocks",
          shape = "rectangle",
          x = 656,
          y = 1026,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rocks",
          shape = "rectangle",
          x = 636,
          y = 700,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rocks",
          shape = "rectangle",
          x = 908,
          y = 1112,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rocks",
          shape = "rectangle",
          x = 736,
          y = 1228,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS_MINE_SPECIAL",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 1706,
          y = 918,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 1938,
          y = 704,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 2356,
          y = 1114,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 2462,
          y = 1080,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 2214,
          y = 804,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 2160,
          y = 1312,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 2528,
          y = 1370,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 1406,
          y = 798,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_fissure",
          shape = "rectangle",
          x = 2032,
          y = 1132,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS_MINE_BOULDERS",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1822,
          y = 1072,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1908,
          y = 950,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 2060,
          y = 742,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1662,
          y = 738,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 1474,
          y = 678,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 2114,
          y = 1434,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 2442,
          y = 1270,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock1",
          shape = "rectangle",
          x = 2318,
          y = 924,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock2",
          shape = "rectangle",
          x = 2238,
          y = 1174,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock2",
          shape = "rectangle",
          x = 1910,
          y = 1184,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock2",
          shape = "rectangle",
          x = 1522,
          y = 896,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock2",
          shape = "rectangle",
          x = 2618,
          y = 872,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_moon",
          shape = "rectangle",
          x = 2302,
          y = 1042,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_moon",
          shape = "rectangle",
          x = 1816,
          y = 822,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_moon",
          shape = "rectangle",
          x = 1852,
          y = 624,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "rock_moon",
          shape = "rectangle",
          x = 2270,
          y = 1328,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 2520,
          y = 1032,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 2364,
          y = 1164,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 2264,
          y = 740,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 2132,
          y = 906,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 2152,
          y = 818,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 2020,
          y = 606,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 1762,
          y = 780,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 1660,
          y = 1020,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 1996,
          y = 1350,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 2090,
          y = 1256,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moonglass_rock",
          shape = "rectangle",
          x = 2432,
          y = 1422,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS_MINE_EXTRAS",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "flint",
          shape = "rectangle",
          x = 1970,
          y = 878,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flint",
          shape = "rectangle",
          x = 2134,
          y = 690,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flint",
          shape = "rectangle",
          x = 2180,
          y = 572,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flint",
          shape = "rectangle",
          x = 1758,
          y = 668,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flint",
          shape = "rectangle",
          x = 1554,
          y = 692,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flint",
          shape = "rectangle",
          x = 1836,
          y = 1140,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flint",
          shape = "rectangle",
          x = 2166,
          y = 1408,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flint",
          shape = "rectangle",
          x = 2434,
          y = 1278,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flint",
          shape = "rectangle",
          x = 2270,
          y = 1052,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flint",
          shape = "rectangle",
          x = 2588,
          y = 1168,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_altar_rock_seed",
          shape = "rectangle",
          x = 2094,
          y = 998,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_altar_rock_idol",
          shape = "rectangle",
          x = 1990,
          y = 672,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "moon_altar_rock_glass",
          shape = "rectangle",
          x = 2460,
          y = 1022,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
