-- AUTOGENERATED CODE BY export_accountitems.lua

EMOJI_ITEMS =
{
	emoji_abigail =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "abigail",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_abigail",
			requires_validation = true,
			utf8_str = "󰀜",
		},
		release_group = 43,
	},
	emoji_alchemyengine =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "alchemy",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_alchemyengine",
			requires_validation = true,
			utf8_str = "󰀝",
		},
		release_group = 43,
	},
	emoji_arcane =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "arcane",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_arcane",
			requires_validation = true,
			utf8_str = "󰀀",
		},
		release_group = 32,
	},
	emoji_backpack =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "backpack",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_backpack",
			requires_validation = true,
			utf8_str = "󰀞",
		},
		release_group = 43,
	},
	emoji_battle =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "battle",
		type = "emoji",
		skin_tags = { "VARG", "EMOJI", },
		data =
		{
			item_type = "emoji_battle",
			requires_validation = true,
			utf8_str = "󰀘",
		},
		release_group = 40,
	},
	emoji_beefalo =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "beefalo",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_beefalo",
			requires_validation = true,
			utf8_str = "󰀁",
		},
		release_group = 32,
	},
	emoji_beehive =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "beehive",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_beehive",
			requires_validation = true,
			utf8_str = "󰀟",
		},
		release_group = 43,
	},
	emoji_berry_bush =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "berry",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_berry_bush",
			requires_validation = true,
			utf8_str = "󰀠",
		},
		release_group = 43,
	},
	emoji_carrot =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "carrot",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_carrot",
			requires_validation = true,
			utf8_str = "󰀡",
		},
		release_group = 43,
	},
	emoji_chest =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "chest",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_chest",
			requires_validation = true,
			utf8_str = "󰀂",
		},
		release_group = 32,
	},
	emoji_chester =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "chester",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_chester",
			requires_validation = true,
			utf8_str = "󰀃",
		},
		release_group = 32,
	},
	emoji_crockpot =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "crockpot",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_crockpot",
			requires_validation = true,
			utf8_str = "󰀄",
		},
		release_group = 32,
	},
	emoji_egg =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "egg",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_egg",
			requires_validation = true,
			utf8_str = "󰀢",
		},
		release_group = 43,
	},
	emoji_eyeball =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "eyeball",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_eyeball",
			requires_validation = true,
			utf8_str = "󰀅",
		},
		release_group = 32,
	},
	emoji_eyeplant =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "eyeplant",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_eyeplant",
			requires_validation = true,
			utf8_str = "󰀣",
		},
		release_group = 43,
	},
	emoji_faketeeth =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "faketeeth",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_faketeeth",
			requires_validation = true,
			utf8_str = "󰀆",
		},
		release_group = 32,
	},
	emoji_farm =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "farm",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_farm",
			requires_validation = true,
			utf8_str = "󰀇",
		},
		release_group = 32,
	},
	emoji_fire =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "fire",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_fire",
			requires_validation = true,
			utf8_str = "󰀈",
		},
		release_group = 32,
	},
	emoji_firepit =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "firepit",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_firepit",
			requires_validation = true,
			utf8_str = "󰀤",
		},
		release_group = 43,
	},
	emoji_flex =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "flex",
		type = "emoji",
		skin_tags = { "VARG", "EMOJI", },
		data =
		{
			item_type = "emoji_flex",
			requires_validation = true,
			utf8_str = "󰀙",
		},
		release_group = 40,
	},
	emoji_florid_postern =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "portal",
		type = "emoji",
		skin_tags = { "EMOJI", },
		data =
		{
			item_type = "emoji_florid_postern",
			requires_validation = true,
			utf8_str = "󰀰",
		},
		release_group = 135,
	},
	emoji_ghost =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "ghost",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_ghost",
			requires_validation = true,
			utf8_str = "󰀉",
		},
		release_group = 32,
	},
	emoji_gold =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "gold",
		type = "emoji",
		skin_tags = { "VARG", "EMOJI", },
		data =
		{
			item_type = "emoji_gold",
			requires_validation = true,
			utf8_str = "󰀚",
		},
		release_group = 40,
	},
	emoji_grave =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "grave",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_grave",
			requires_validation = true,
			utf8_str = "󰀊",
		},
		release_group = 32,
	},
	emoji_hambat =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "hambat",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_hambat",
			requires_validation = true,
			utf8_str = "󰀋",
		},
		release_group = 32,
	},
	emoji_hammer =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "hammer",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_hammer",
			requires_validation = true,
			utf8_str = "󰀌",
		},
		release_group = 32,
	},
	emoji_heart =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "heart",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_heart",
			requires_validation = true,
			utf8_str = "󰀍",
		},
		release_group = 32,
	},
	emoji_horn =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "horn",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_horn",
			requires_validation = true,
			utf8_str = "󰀥",
		},
		release_group = 43,
	},
	emoji_hunger =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "hunger",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_hunger",
			requires_validation = true,
			utf8_str = "󰀎",
		},
		release_group = 32,
	},
	emoji_lightbulb =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "lightbulb",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_lightbulb",
			requires_validation = true,
			utf8_str = "󰀏",
		},
		release_group = 32,
	},
	emoji_meat_big =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "meat",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_meat_big",
			requires_validation = true,
			utf8_str = "󰀦",
		},
		release_group = 43,
	},
	emoji_pig =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "pig",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_pig",
			requires_validation = true,
			utf8_str = "󰀐",
		},
		release_group = 32,
	},
	emoji_poop =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "poop",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_poop",
			requires_validation = true,
			utf8_str = "󰀑",
		},
		release_group = 32,
	},
	emoji_redgem =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "redgem",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_redgem",
			requires_validation = true,
			utf8_str = "󰀒",
		},
		release_group = 32,
	},
	emoji_refine =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "refine",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_refine",
			requires_validation = true,
			utf8_str = "󰀧",
		},
		release_group = 43,
	},
	emoji_resurrection_stone =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "resurrection",
		type = "emoji",
		skin_tags = { "EMOJI", },
		data =
		{
			item_type = "emoji_resurrection_stone",
			requires_validation = true,
			utf8_str = "󰀱",
		},
		release_group = 135,
	},
	emoji_salt =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "salt",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_salt",
			requires_validation = true,
			utf8_str = "󰀨",
		},
		release_group = 43,
	},
	emoji_sanity =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "sanity",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_sanity",
			requires_validation = true,
			utf8_str = "󰀓",
		},
		release_group = 32,
	},
	emoji_sciencemachine =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "sciencemachine",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_sciencemachine",
			requires_validation = true,
			utf8_str = "󰀔",
		},
		release_group = 32,
	},
	emoji_shadowmanipulator =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "shadow",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_shadowmanipulator",
			requires_validation = true,
			utf8_str = "󰀩",
		},
		release_group = 43,
	},
	emoji_shovel =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "shovel",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_shovel",
			requires_validation = true,
			utf8_str = "󰀪",
		},
		release_group = 43,
	},
	emoji_skull =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "skull",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_skull",
			requires_validation = true,
			utf8_str = "󰀕",
		},
		release_group = 32,
	},
	emoji_thumbsup =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "thumbsup",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_thumbsup",
			requires_validation = true,
			utf8_str = "󰀫",
		},
		release_group = 43,
	},
	emoji_tophat =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "tophat",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_tophat",
			requires_validation = true,
			utf8_str = "󰀖",
		},
		release_group = 32,
	},
	emoji_torch =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "torch",
		type = "emoji",
		skin_tags = { "VARG", "EMOJI", },
		data =
		{
			item_type = "emoji_torch",
			requires_validation = true,
			utf8_str = "󰀛",
		},
		release_group = 40,
	},
	emoji_trap =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "trap",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_trap",
			requires_validation = true,
			utf8_str = "󰀬",
		},
		release_group = 43,
	},
	emoji_trophy =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "trophy",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_trophy",
			requires_validation = true,
			utf8_str = "󰀭",
		},
		release_group = 43,
	},
	emoji_wave =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "wave",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_wave",
			requires_validation = true,
			utf8_str = "󰀮",
		},
		release_group = 43,
	},
	emoji_web =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "web",
		type = "emoji",
		skin_tags = { "LAVA", "EMOJI", },
		data =
		{
			item_type = "emoji_web",
			requires_validation = true,
			utf8_str = "󰀗",
		},
		release_group = 32,
	},
	emoji_wormhole =
	{
		rarity = "Common",
		rarity_modifier = "Woven",
		input_name = "wormhole",
		type = "emoji",
		skin_tags = { "VICTORIAN", "EMOJI", },
		data =
		{
			item_type = "emoji_wormhole",
			requires_validation = true,
			utf8_str = "󰀯",
		},
		release_group = 43,
	},
}

-- AUTOGENERATED CODE BY export_accountitems.lua

