-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/amulet_red_occulteye.zip"),
}

return CreatePrefabSkin("amulet_red_occulteye",
{
	base_prefab = "amulet",
	type = "item",
	assets = assets,
	build_name = "amulet_red_occulteye",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	init_fn = function(inst) amulet_init_fn(inst, "amulet_red_occulteye") end,
	skin_tags = { "AMULET_RED", "LAVA", "CRAFTABLE", },
	release_group = 32,
})
