-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/armor_marble_chainmail.zip"),
}

return CreatePrefabSkin("armor_marble_chainmail",
{
	base_prefab = "armormarble",
	type = "item",
	assets = assets,
	build_name = "armor_marble_chainmail",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	init_fn = function(inst) armormarble_init_fn(inst, "armor_marble_chainmail") end,
	skin_tags = { "ARMORMARBLE", "LAVA", "CRAFTABLE", },
	release_group = 32,
})
