-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/armor_wood_fangedcollar.zip"),
}

return CreatePrefabSkin("armor_wood_fangedcollar",
{
	base_prefab = "armorwood",
	type = "item",
	assets = assets,
	build_name = "armor_wood_fangedcollar",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	init_fn = function(inst) armorwood_init_fn(inst, "armor_wood_fangedcollar") end,
	skin_tags = { "ARMORWOOD", "LAVA", "CRAFTABLE", },
	release_group = 32,
	granted_items = { "armor_dragonfly_fangedcollar", },
})
