-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/armor_dragonfly_haramaki.zip"),
}

return CreatePrefabSkin("armor_dragonfly_haramaki",
{
	base_prefab = "armordragonfly",
	type = "item",
	assets = assets,
	build_name = "armor_dragonfly_haramaki",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	init_fn = function(inst) armordragonfly_init_fn(inst, "armor_dragonfly_haramaki") end,
	skin_tags = { "ARMORDRAGONFLY", "LAVA", "CRAFTABLE", },
	release_group = 32,
})
