-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/armor_grass_woven.zip"),
}

return CreatePrefabSkin("armor_grass_woven",
{
	base_prefab = "armorgrass",
	type = "item",
	assets = assets,
	build_name = "armor_grass_woven",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	init_fn = function(inst) armorgrass_init_fn(inst, "armor_grass_woven") end,
	skin_tags = { "ARMORGRASS", "LAVA", "CRAFTABLE", },
	release_group = 32,
})
