-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/swap_backpack_buckle_grey_pewter.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/swap_backpack_mushy.zip"),
}

return CreatePrefabSkin("backpack_buckle_grey_pewter",
{
	base_prefab = "backpack",
	type = "item",
	assets = assets,
	build_name = "swap_backpack_buckle_grey_pewter",
	rarity = "Spiffy",
	init_fn = function(inst) backpack_init_fn(inst, "swap_backpack_buckle_grey_pewter") end,
	skin_tags = { "BACKPACK", "GREY", "CRAFTABLE", },
	marketable = true,
	release_group = 0,
})
