-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/swap_backpack_rabbit.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/swap_backpack_mushy.zip"),
}

return CreatePrefabSkin("backpack_rabbit",
{
	base_prefab = "backpack",
	type = "item",
	assets = assets,
	build_name = "swap_backpack_rabbit",
	rarity = "Elegant",
	init_fn = function(inst) backpack_init_fn(inst, "swap_backpack_rabbit") end,
	skin_tags = { "BACKPACK", "CRAFTABLE", },
	marketable = true,
	release_group = 0,
})
