-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/swap_backpack_basic_blue_catcoon.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/swap_backpack_mushy.zip"),
}

return CreatePrefabSkin("backpack_basic_blue_catcoon",
{
	base_prefab = "backpack",
	type = "item",
	assets = assets,
	build_name = "swap_backpack_basic_blue_catcoon",
	rarity = "Spiffy",
	init_fn = function(inst) backpack_init_fn(inst, "swap_backpack_basic_blue_catcoon") end,
	skin_tags = { "BACKPACK", "BLUE", "CRAFTABLE", },
	marketable = true,
	release_group = 1,
})
