-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/swap_backpack_deerclops.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/swap_backpack_mushy.zip"),
}

return CreatePrefabSkin("backpack_deerclops",
{
	base_prefab = "backpack",
	type = "item",
	assets = assets,
	build_name = "swap_backpack_deerclops",
	rarity = "ProofOfPurchase",
	init_fn = function(inst) backpack_init_fn(inst, "swap_backpack_deerclops") end,
	skin_tags = { "BACKPACK", "CRAFTABLE", },
	release_group = 13,
})
