-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/swap_bedroll_furry_quilt_blue_frost.zip"),
}

return CreatePrefabSkin("bedroll_furry_quilt_blue_frost",
{
	base_prefab = "bedroll_furry",
	type = "item",
	assets = assets,
	build_name = "swap_bedroll_furry_quilt_blue_frost",
	rarity = "Distinguished",
	init_fn = function(inst) bedroll_furry_init_fn(inst, "swap_bedroll_furry_quilt_blue_frost") end,
	skin_tags = { "BEDROLL", "BLUE", "CRAFTABLE", },
	marketable = true,
	release_group = 20,
})
