-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/book_brimstone_gilded.zip"),
}

return CreatePrefabSkin("book_brimstone_gilded",
{
	base_prefab = "book_brimstone",
	type = "item",
	assets = assets,
	build_name = "book_brimstone_gilded",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	init_fn = function(inst) book_brimstone_init_fn(inst, "book_brimstone_gilded") end,
	skin_tags = { "BOOK_BRIMSTONE", "LAVA", "CRAFTABLE", },
	release_group = 32,
})
