-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/cane_ancient.zip"),
}

return CreatePrefabSkin("cane_ancient",
{
	base_prefab = "cane",
	type = "item",
	assets = assets,
	build_name = "cane_ancient",
	rarity = "Timeless",
	prefabs = { "cane_ancient_fx", },
	init_fn = function(inst) cane_init_fn(inst, "cane_ancient") end,
	skin_tags = { "CANE", "ANCIENT", "CRAFTABLE", },
	fx_prefab = { "cane_ancient_fx", },
	release_group = 25,
	granted_items = { "orangestaff_ancient", },
})
