-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/cookpot_survival.zip"),
}

return CreatePrefabSkin("cookpot_survival",
{
	base_prefab = "cookpot",
	type = "item",
	assets = assets,
	build_name = "cookpot_survival",
	rarity = "Elegant",
	init_fn = function(inst) cookpot_init_fn(inst, "cookpot_survival") end,
	skin_tags = { "CROCKPOT", "SURVIVOR", "CRAFTABLE", },
	marketable = true,
	release_group = 4,
})
