-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/cookpot_cauldron.zip"),
}

return CreatePrefabSkin("cookpot_cauldron",
{
	base_prefab = "cookpot",
	type = "item",
	assets = assets,
	build_name = "cookpot_cauldron",
	rarity = "Elegant",
	init_fn = function(inst) cookpot_init_fn(inst, "cookpot_cauldron") end,
	skin_tags = { "CROCKPOT", "COSTUME", "CRAFTABLE", },
	marketable = true,
	release_group = 31,
})
