-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/dragonling_bat.zip"),
}

return CreatePrefabSkin("dragonling_bat",
{
	base_prefab = "critter_dragonling",
	type = "item",
	assets = assets,
	build_name = "dragonling_bat",
	rarity = "Elegant",
	init_fn = function(inst) pet_init_fn(inst, "dragonling_bat", "dragonling_build" ) end,
	skin_tags = { "PET", "COSTUME", "CRAFTABLE", },
	marketable = true,
	release_group = 31,
})
