-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/dragonling_bat.zip"),
}

return CreatePrefabSkin("dragonling_bat_builder",
{
	base_prefab = "critter_dragonling_builder",
	type = "item",
	assets = assets,
	build_name = "dragonling_bat",
	rarity = "Common",
	init_fn = function(inst) critter_builder_init_fn(inst, "dragonling_bat" ) end,
	skin_tags = { "CRAFTABLE", },
	release_group = 31,
})
