-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/dragonling_wyvern.zip"),
}

return CreatePrefabSkin("dragonling_wyvern",
{
	base_prefab = "critter_dragonling",
	type = "item",
	assets = assets,
	build_name = "dragonling_wyvern",
	rarity = "Elegant",
	init_fn = function(inst) pet_init_fn(inst, "dragonling_wyvern", "dragonling_build" ) end,
	skin_tags = { "PET", "CRAFTABLE", },
	marketable = true,
	release_group = 17,
})
