-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/firestaff_meteor.zip"),
}

return CreatePrefabSkin("firestaff_meteor",
{
	base_prefab = "firestaff",
	type = "item",
	assets = assets,
	build_name = "firestaff_meteor",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	init_fn = function(inst) firestaff_init_fn(inst, "firestaff_meteor") end,
	skin_tags = { "STAFF", "LAVA", "CRAFTABLE", },
	release_group = 32,
})
