-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/firestaff_rose.zip"),
}

return CreatePrefabSkin("firestaff_rose",
{
	base_prefab = "firestaff",
	type = "item",
	assets = assets,
	build_name = "firestaff_rose",
	rarity = "Elegant",
	init_fn = function(inst) firestaff_init_fn(inst, "firestaff_rose") end,
	skin_tags = { "STAFF", "CRAFTABLE", },
	release_group = 27,
})
