-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/firepit_stonehenge.zip"),
}

return CreatePrefabSkin("firepit_stonehenge",
{
	base_prefab = "firepit",
	type = "item",
	assets = assets,
	build_name = "firepit_stonehenge",
	rarity = "Loyal",
	init_fn = function(inst) firepit_init_fn(inst, "firepit_stonehenge", Vector3(0, -28, 0)) end,
	skin_tags = { "FIREPIT", "CRAFTABLE", },
	release_group = 5,
})
