-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/firepit_fanged.zip"),
}

return CreatePrefabSkin("firepit_fanged",
{
	base_prefab = "firepit",
	type = "item",
	assets = assets,
	build_name = "firepit_fanged",
	rarity = "Distinguished",
	init_fn = function(inst) firepit_init_fn(inst, "firepit_fanged", Vector3(0, 20, 0)) end,
	skin_tags = { "FIREPIT", "CRAFTABLE", },
	marketable = true,
	release_group = 5,
})
