-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/flowerhat_crown.zip"),
}

return CreatePrefabSkin("flowerhat_crown",
{
	base_prefab = "flowerhat",
	type = "item",
	assets = assets,
	build_name = "flowerhat_crown",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	init_fn = function(inst) flowerhat_init_fn(inst, "flowerhat_crown") end,
	skin_tags = { "FLOWERHAT", "LAVA", "CRAFTABLE", },
	release_group = 32,
})
