-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/flowerhat_ribbon_wreath.zip"),
}

return CreatePrefabSkin("flowerhat_ribbon_wreath",
{
	base_prefab = "flowerhat",
	type = "item",
	assets = assets,
	build_name = "flowerhat_ribbon_wreath",
	rarity = "Spiffy",
	init_fn = function(inst) flowerhat_init_fn(inst, "flowerhat_ribbon_wreath") end,
	skin_tags = { "FLOWERHAT", "WINTER", "CRAFTABLE", },
	marketable = true,
	release_group = 22,
})
