-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/hambat_spiralcut.zip"),
}

return CreatePrefabSkin("hambat_spiralcut",
{
	base_prefab = "hambat",
	type = "item",
	assets = assets,
	build_name = "hambat_spiralcut",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	init_fn = function(inst) hambat_init_fn(inst, "hambat_spiralcut") end,
	skin_tags = { "HAMBAT", "LAVA", "CRAFTABLE", },
	release_group = 32,
})
