-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/hat_catcoon_costume.zip"),
}

return CreatePrefabSkin("hat_catcoon_costume",
{
	base_prefab = "tophat",
	type = "item",
	assets = assets,
	build_name = "hat_catcoon_costume",
	rarity = "Elegant",
	init_fn = function(inst) tophat_init_fn(inst, "hat_catcoon_costume") end,
	skin_tags = { "TOPHAT", "COSTUME", "CRAFTABLE", },
	marketable = true,
	release_group = 15,
	granted_items = { "researchlab4_catcoon_costume", },
})
