-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/icestaff_rose.zip"),
}

return CreatePrefabSkin("icestaff_rose",
{
	base_prefab = "icestaff",
	type = "item",
	assets = assets,
	build_name = "icestaff_rose",
	rarity = "Elegant",
	init_fn = function(inst) icestaff_init_fn(inst, "icestaff_rose") end,
	skin_tags = { "STAFF", "CRAFTABLE", },
	release_group = 27,
})
