-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/lamb_winter.zip"),
}

return CreatePrefabSkin("lamb_winter",
{
	base_prefab = "critter_lamb",
	type = "item",
	assets = assets,
	build_name = "lamb_winter",
	rarity = "Elegant",
	init_fn = function(inst) pet_init_fn(inst, "lamb_winter", "sheepington_build" ) end,
	skin_tags = { "PET", "WINTER", "CRAFTABLE", },
	marketable = true,
	release_group = 22,
})
