-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/lamb_winter.zip"),
}

return CreatePrefabSkin("lamb_winter_builder",
{
	base_prefab = "critter_lamb_builder",
	type = "item",
	assets = assets,
	build_name = "lamb_winter",
	rarity = "Common",
	init_fn = function(inst) critter_builder_init_fn(inst, "lamb_winter" ) end,
	skin_tags = { "CRAFTABLE", },
	release_group = 22,
})
