-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/minerhat_floppy.zip"),
}

return CreatePrefabSkin("minerhat_floppy",
{
	base_prefab = "minerhat",
	type = "item",
	assets = assets,
	build_name = "minerhat_floppy",
	rarity = "Elegant",
	init_fn = function(inst) minerhat_init_fn(inst, "minerhat_floppy") end,
	skin_tags = { "MINERHAT", "CRAFTABLE", },
	release_group = 28,
})
