-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/perdling_rooster.zip"),
}

return CreatePrefabSkin("perdling_rooster",
{
	base_prefab = "critter_perdling",
	type = "item",
	assets = assets,
	build_name = "perdling_rooster",
	rarity = "Elegant",
	init_fn = function(inst) perdling_init_fn(inst, "perdling_rooster", "perdling_build", "dontstarve/creatures/together/rooster/distress_long" ) end,
	skin_tags = { "PET", "LUNAR", "CRAFTABLE", },
	marketable = true,
	release_group = 23,
})
