-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/puppy_winter.zip"),
}

return CreatePrefabSkin("puppy_winter_builder",
{
	base_prefab = "critter_puppy_builder",
	type = "item",
	assets = assets,
	build_name = "puppy_winter",
	rarity = "Common",
	init_fn = function(inst) critter_builder_init_fn(inst, "puppy_winter" ) end,
	skin_tags = { "CRAFTABLE", },
	release_group = 22,
})
