-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/puppy_winter.zip"),
}

return CreatePrefabSkin("puppy_winter",
{
	base_prefab = "critter_puppy",
	type = "item",
	assets = assets,
	build_name = "puppy_winter",
	rarity = "Elegant",
	init_fn = function(inst) pet_init_fn(inst, "puppy_winter", "pupington_build" ) end,
	skin_tags = { "PET", "WINTER", "CRAFTABLE", },
	marketable = true,
	release_group = 22,
})
