-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/researchlab2_pod.zip"),
}

return CreatePrefabSkin("researchlab2_pod",
{
	base_prefab = "researchlab2",
	type = "item",
	assets = assets,
	build_name = "researchlab2_pod",
	rarity = "Elegant",
	init_fn = function(inst) researchlab2_init_fn(inst, "researchlab2_pod") end,
	skin_tags = { "ALCHEMY", "CRAFTABLE", },
	marketable = true,
	release_group = 29,
})
