-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/swap_spear_rose.zip"),
}

return CreatePrefabSkin("spear_rose",
{
	base_prefab = "spear",
	type = "item",
	assets = assets,
	build_name = "swap_spear_rose",
	rarity = "Elegant",
	init_fn = function(inst) spear_init_fn(inst, "swap_spear_rose") end,
	skin_tags = { "SPEAR", "CRAFTABLE", },
	marketable = true,
	release_group = 16,
	granted_items = { "firestaff_rose", "icestaff_rose", },
})
