-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/torch_rag.zip"),
}

return CreatePrefabSkin("torch_rag",
{
	base_prefab = "torch",
	type = "item",
	assets = assets,
	build_name = "torch_rag",
	rarity = "Elegant",
	prefabs = { "torchfire_rag", },
	init_fn = function(inst) torch_init_fn(inst, "torch_rag") end,
	skin_tags = { "TORCH", "SURVIVOR", "CRAFTABLE", },
	fx_prefab = { "torchfire_rag", },
	marketable = true,
	release_group = 4,
})
