-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/treasurechest_traveltrunk.zip"),
}

return CreatePrefabSkin("treasurechest_traveltrunk",
{
	base_prefab = "treasurechest",
	type = "item",
	assets = assets,
	build_name = "treasurechest_traveltrunk",
	rarity = "Distinguished",
	init_fn = function(inst) treasurechest_init_fn(inst, "treasurechest_traveltrunk") end,
	skin_tags = { "CHEST", "CRAFTABLE", },
	marketable = true,
	release_group = 19,
})
