-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/treasurechest_poshprint.zip"),
}

return CreatePrefabSkin("treasurechest_poshprint",
{
	base_prefab = "treasurechest",
	type = "item",
	assets = assets,
	build_name = "treasurechest_poshprint",
	rarity = "ProofOfPurchase",
	init_fn = function(inst) treasurechest_init_fn(inst, "treasurechest_poshprint") end,
	skin_tags = { "CHEST", "CRAFTABLE", },
	release_group = 13,
})
