-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/treasurechest_sacred.zip"),
}

return CreatePrefabSkin("treasurechest_sacred",
{
	base_prefab = "treasurechest",
	type = "item",
	assets = assets,
	build_name = "treasurechest_sacred",
	rarity = "Timeless",
	init_fn = function(inst) treasurechest_init_fn(inst, "treasurechest_sacred") end,
	skin_tags = { "CHEST", "ANCIENT", "CRAFTABLE", },
	release_group = 25,
})
