-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/treasurechest_gingerbread.zip"),
}

return CreatePrefabSkin("treasurechest_gingerbread",
{
	base_prefab = "treasurechest",
	type = "item",
	assets = assets,
	build_name = "treasurechest_gingerbread",
	rarity = "Event",
	init_fn = function(inst) treasurechest_init_fn(inst, "treasurechest_gingerbread") end,
	skin_tags = { "CHEST", "WINTER", "CRAFTABLE", },
	release_group = 22,
})
