-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wathgrithr_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wathgrithr_gladiator.zip"),
	Asset("ATLAS_BUILD", "bigportraits/wathgrithr_gladiator.xml", 128),
}

return CreatePrefabSkin("wathgrithr_gladiator",
{
	base_prefab = "wathgrithr",
	type = "base",
	assets = assets,
	build_name = "wathgrithr_gladiator",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	skin_tags = { "LAVA", "BASE", "CHARACTER", "WATHGRITHR", },
	bigportrait = { build = "bigportraits/wathgrithr_gladiator.xml", symbol = "wathgrithr_gladiator_oval.tex"},
	skins = { ghost_skin = "ghost_wathgrithr_build", normal_skin = "wathgrithr_gladiator", },
	release_group = 32,
})
