-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wathgrithr_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wathgrithr_deerclops_d.zip"),
}

return CreatePrefabSkin("wathgrithr_deerclops_d",
{
	base_prefab = "wathgrithr",
	type = "base",
	assets = assets,
	build_name = "wathgrithr_deerclops_d",
	rarity = "Elegant",
	skin_tags = { "COSTUME", "BASE", "CHARACTER", "WATHGRITHR", },
	skins = { ghost_skin = "ghost_wathgrithr_build", normal_skin = "wathgrithr_deerclops_d", },
	marketable = true,
	release_group = 31,
})
