-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wathgrithr_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wathgrithr_formal.zip"),
}

return CreatePrefabSkin("wathgrithr_formal",
{
	base_prefab = "wathgrithr",
	type = "base",
	assets = assets,
	build_name = "wathgrithr_formal",
	rarity = "Elegant",
	skin_tags = { "FORMAL", "BASE", "CHARACTER", "WATHGRITHR", },
	skins = { ghost_skin = "ghost_wathgrithr_build", normal_skin = "wathgrithr_formal", },
	marketable = true,
	release_group = 2,
})
