-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wathgrithr_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wathgrithr_combatant.zip"),
}

return CreatePrefabSkin("wathgrithr_combatant",
{
	base_prefab = "wathgrithr",
	type = "base",
	assets = assets,
	build_name = "wathgrithr_combatant",
	rarity = "Event",
	skin_tags = { "LAVA", "BASE", "CHARACTER", "WATHGRITHR", },
	skins = { ghost_skin = "ghost_wathgrithr_build", normal_skin = "wathgrithr_combatant", },
	release_group = 32,
})
