-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_waxwell_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/waxwell_krampus.zip"),
}

return CreatePrefabSkin("waxwell_krampus",
{
	base_prefab = "waxwell",
	type = "base",
	assets = assets,
	build_name = "waxwell_krampus",
	rarity = "Event",
	skin_tags = { "COSTUME", "BASE", "CHARACTER", "WAXWELL", },
	skins = { ghost_skin = "ghost_waxwell_build", normal_skin = "waxwell_krampus", },
	release_group = 15,
})
