-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_waxwell_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/waxwell_unshadow.zip"),
}

return CreatePrefabSkin("waxwell_unshadow",
{
	base_prefab = "waxwell",
	type = "base",
	assets = assets,
	build_name = "waxwell_unshadow",
	rarity = "Elegant",
	skin_tags = { "SHADOW", "BASE", "CHARACTER", "WAXWELL", },
	skins = { ghost_skin = "ghost_waxwell_build", normal_skin = "waxwell_unshadow", },
	torso_tuck_builds = { "waxwell_unshadow", },
	marketable = true,
	release_group = 6,
})
