-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_waxwell_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/waxwell_survivor.zip"),
}

return CreatePrefabSkin("waxwell_survivor",
{
	base_prefab = "waxwell",
	type = "base",
	assets = assets,
	build_name = "waxwell_survivor",
	rarity = "Elegant",
	skin_tags = { "SURVIVOR", "BASE", "CHARACTER", "WAXWELL", },
	skins = { ghost_skin = "ghost_waxwell_build", normal_skin = "waxwell_survivor", },
	torso_tuck_builds = { "waxwell_survivor", },
	marketable = true,
	release_group = 5,
})
