-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_waxwell_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/waxwell_gladiator.zip"),
	Asset("ATLAS_BUILD", "bigportraits/waxwell_gladiator.xml", 128),
}

return CreatePrefabSkin("waxwell_gladiator",
{
	base_prefab = "waxwell",
	type = "base",
	assets = assets,
	build_name = "waxwell_gladiator",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	skin_tags = { "LAVA", "BASE", "CHARACTER", "WAXWELL", },
	bigportrait = { build = "bigportraits/waxwell_gladiator.xml", symbol = "waxwell_gladiator_oval.tex"},
	skins = { ghost_skin = "ghost_waxwell_build", normal_skin = "waxwell_gladiator", },
	release_group = 32,
})
