-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_waxwell_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/waxwell_combatant.zip"),
}

return CreatePrefabSkin("waxwell_combatant",
{
	base_prefab = "waxwell",
	type = "base",
	assets = assets,
	build_name = "waxwell_combatant",
	rarity = "Event",
	skin_tags = { "LAVA", "BASE", "CHARACTER", "WAXWELL", },
	skins = { ghost_skin = "ghost_waxwell_build", normal_skin = "waxwell_combatant", },
	release_group = 32,
})
