-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_webber_build.zip"),
	Asset("ANIM", "anim/webber.zip"),
}

return CreatePrefabSkin("webber_none",
{
	base_prefab = "webber",
	type = "base",
	assets = assets,
	build_name = "webber",
	rarity = "Common",
	skin_tags = { "BASE", "CHARACTER", "WEBBER", },
	skins = { ghost_skin = "ghost_webber_build", normal_skin = "webber", },
	release_group = 999,
})
