-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_webber_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/webber_ice.zip"),
	Asset("ATLAS_BUILD", "bigportraits/webber_ice.xml", 192),
}

return CreatePrefabSkin("webber_ice",
{
	base_prefab = "webber",
	type = "base",
	assets = assets,
	build_name = "webber_ice",
	rarity = "Elegant",
	rarity_modifier = "Seasonal",
	skin_tags = { "ICE", "BASE", "CHARACTER", "WEBBER", },
	bigportrait = { build = "bigportraits/webber_ice.xml", symbol = "webber_ice_oval.tex"},
	skins = { ghost_skin = "ghost_webber_build", normal_skin = "webber_ice", },
	torso_tuck_builds = { "webber_ice", },
	release_group = 36,
})
