-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wendy_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wendy_rose.zip"),
}

return CreatePrefabSkin("wendy_rose",
{
	base_prefab = "wendy",
	type = "base",
	assets = assets,
	build_name = "wendy_rose",
	rarity = "Elegant",
	skin_tags = { "ROSE", "BASE", "CHARACTER", "WENDY", },
	skins = { ghost_skin = "ghost_wendy_build", normal_skin = "wendy_rose", },
	torso_untuck_builds = { "wendy_rose", },
	marketable = true,
	release_group = 10,
})
