-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wendy_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wendy_ice.zip"),
	Asset("ATLAS_BUILD", "bigportraits/wendy_ice.xml", 192),
}

return CreatePrefabSkin("wendy_ice",
{
	base_prefab = "wendy",
	type = "base",
	assets = assets,
	build_name = "wendy_ice",
	rarity = "Elegant",
	rarity_modifier = "Seasonal",
	skin_tags = { "ICE", "BASE", "CHARACTER", "WENDY", },
	bigportrait = { build = "bigportraits/wendy_ice.xml", symbol = "wendy_ice_oval.tex"},
	skins = { ghost_skin = "ghost_wendy_build", normal_skin = "wendy_ice", },
	release_group = 36,
})
