-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wendy_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wendy_lureplant_d.zip"),
}

return CreatePrefabSkin("wendy_lureplant_d",
{
	base_prefab = "wendy",
	type = "base",
	assets = assets,
	build_name = "wendy_lureplant_d",
	rarity = "Elegant",
	skin_tags = { "COSTUME", "BASE", "CHARACTER", "WENDY", },
	skins = { ghost_skin = "ghost_wendy_build", normal_skin = "wendy_lureplant_d", },
	torso_untuck_builds = { "wendy_lureplant_d", },
	marketable = true,
	release_group = 31,
})
