-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wendy_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wendy_lureplant.zip"),
}

return CreatePrefabSkin("wendy_lureplant",
{
	base_prefab = "wendy",
	type = "base",
	assets = assets,
	build_name = "wendy_lureplant",
	rarity = "Event",
	skin_tags = { "COSTUME", "BASE", "CHARACTER", "WENDY", },
	skins = { ghost_skin = "ghost_wendy_build", normal_skin = "wendy_lureplant", },
	torso_tuck_builds = { "wendy_lureplant", },
	has_alternate_for_body = { "wendy_lureplant", },
	release_group = 15,
})
