-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wendy_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wendy_gladiator.zip"),
	Asset("ATLAS_BUILD", "bigportraits/wendy_gladiator.xml", 192),
}

return CreatePrefabSkin("wendy_gladiator",
{
	base_prefab = "wendy",
	type = "base",
	assets = assets,
	build_name = "wendy_gladiator",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	skin_tags = { "LAVA", "BASE", "CHARACTER", "WENDY", },
	bigportrait = { build = "bigportraits/wendy_gladiator.xml", symbol = "wendy_gladiator_oval.tex"},
	skins = { ghost_skin = "ghost_wendy_build", normal_skin = "wendy_gladiator", },
	release_group = 32,
})
