-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wes_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wes_gladiator.zip"),
	Asset("ATLAS_BUILD", "bigportraits/wes_gladiator.xml", 192),
}

return CreatePrefabSkin("wes_gladiator",
{
	base_prefab = "wes",
	type = "base",
	assets = assets,
	build_name = "wes_gladiator",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	skin_tags = { "LAVA", "BASE", "CHARACTER", "WES", },
	bigportrait = { build = "bigportraits/wes_gladiator.xml", symbol = "wes_gladiator_oval.tex"},
	skins = { ghost_skin = "ghost_wes_build", normal_skin = "wes_gladiator", },
	torso_tuck_builds = { "wes_gladiator", },
	has_alternate_for_body = { "wes_gladiator", },
	has_alternate_for_skirt = { "wes_gladiator", },
	release_group = 32,
})
