-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wes_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wes_survivor.zip"),
}

return CreatePrefabSkin("wes_survivor",
{
	base_prefab = "wes",
	type = "base",
	assets = assets,
	build_name = "wes_survivor",
	rarity = "Elegant",
	skin_tags = { "SURVIVOR", "BASE", "CHARACTER", "WES", },
	skins = { ghost_skin = "ghost_wes_build", normal_skin = "wes_survivor", },
	torso_tuck_builds = { "wes_survivor", },
	has_alternate_for_body = { "wes_survivor", },
	has_alternate_for_skirt = { "wes_survivor", },
	marketable = true,
	release_group = 4,
})
