-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wickerbottom_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wickerbottom_survivor.zip"),
}

return CreatePrefabSkin("wickerbottom_survivor",
{
	base_prefab = "wickerbottom",
	type = "base",
	assets = assets,
	build_name = "wickerbottom_survivor",
	rarity = "Elegant",
	skin_tags = { "SURVIVOR", "BASE", "CHARACTER", "WICKERBOTTOM", },
	skins = { ghost_skin = "ghost_wickerbottom_build", normal_skin = "wickerbottom_survivor", },
	torso_tuck_builds = { "wickerbottom_survivor", },
	has_alternate_for_body = { "wickerbottom_survivor", },
	has_alternate_for_skirt = { "wickerbottom_survivor", },
	marketable = true,
	release_group = 4,
})
