-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wickerbottom_build.zip"),
	Asset("ANIM", "anim/wickerbottom.zip"),
}

return CreatePrefabSkin("wickerbottom_none",
{
	base_prefab = "wickerbottom",
	type = "base",
	assets = assets,
	build_name = "wickerbottom",
	rarity = "Common",
	skin_tags = { "BASE", "CHARACTER", "WICKERBOTTOM", },
	skins = { ghost_skin = "ghost_wickerbottom_build", normal_skin = "wickerbottom", },
	torso_tuck_builds = { "wickerbottom", },
	has_alternate_for_body = { "wickerbottom", },
	has_alternate_for_skirt = { "wickerbottom", },
	feet_cuff_size = { wickerbottom = 3, },
	release_group = 999,
})
