-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wickerbottom_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wickerbottom_rose.zip"),
}

return CreatePrefabSkin("wickerbottom_rose",
{
	base_prefab = "wickerbottom",
	type = "base",
	assets = assets,
	build_name = "wickerbottom_rose",
	rarity = "Elegant",
	skin_tags = { "ROSE", "BASE", "CHARACTER", "WICKERBOTTOM", },
	skins = { ghost_skin = "ghost_wickerbottom_build", normal_skin = "wickerbottom_rose", },
	torso_tuck_builds = { "wickerbottom_rose", },
	has_alternate_for_body = { "wickerbottom_rose", },
	has_alternate_for_skirt = { "wickerbottom_rose", },
	feet_cuff_size = { wickerbottom_rose = 3, },
	marketable = true,
	release_group = 10,
})
