-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_willow_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/willow_ice.zip"),
	Asset("ATLAS_BUILD", "bigportraits/willow_ice.xml", 192),
}

return CreatePrefabSkin("willow_ice",
{
	base_prefab = "willow",
	type = "base",
	assets = assets,
	build_name = "willow_ice",
	rarity = "Elegant",
	rarity_modifier = "Seasonal",
	skin_tags = { "ICE", "BASE", "CHARACTER", "WILLOW", },
	bigportrait = { build = "bigportraits/willow_ice.xml", symbol = "willow_ice_oval.tex"},
	skins = { ghost_skin = "ghost_willow_build", normal_skin = "willow_ice", },
	release_group = 36,
})
