-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_willow_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/willow_dragonfly_d.zip"),
}

return CreatePrefabSkin("willow_dragonfly_d",
{
	base_prefab = "willow",
	type = "base",
	assets = assets,
	build_name = "willow_dragonfly_d",
	rarity = "Elegant",
	skin_tags = { "COSTUME", "BASE", "CHARACTER", "WILLOW", },
	skins = { ghost_skin = "ghost_willow_build", normal_skin = "willow_dragonfly_d", },
	marketable = true,
	release_group = 31,
})
