-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_willow_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/willow_combatant.zip"),
}

return CreatePrefabSkin("willow_combatant",
{
	base_prefab = "willow",
	type = "base",
	assets = assets,
	build_name = "willow_combatant",
	rarity = "Event",
	skin_tags = { "LAVA", "BASE", "CHARACTER", "WILLOW", },
	skins = { ghost_skin = "ghost_willow_build", normal_skin = "willow_combatant", },
	release_group = 32,
})
