-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_willow_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/willow_gladiator.zip"),
	Asset("ATLAS_BUILD", "bigportraits/willow_gladiator.xml", 128),
}

return CreatePrefabSkin("willow_gladiator",
{
	base_prefab = "willow",
	type = "base",
	assets = assets,
	build_name = "willow_gladiator",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	skin_tags = { "LAVA", "BASE", "CHARACTER", "WILLOW", },
	bigportrait = { build = "bigportraits/willow_gladiator.xml", symbol = "willow_gladiator_oval.tex"},
	skins = { ghost_skin = "ghost_willow_build", normal_skin = "willow_gladiator", },
	release_group = 32,
})
