-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wilson_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wilson_pigguard.zip"),
}

return CreatePrefabSkin("wilson_pigguard",
{
	base_prefab = "wilson",
	type = "base",
	assets = assets,
	build_name = "wilson_pigguard",
	rarity = "Event",
	skin_tags = { "COSTUME", "BASE", "CHARACTER", "WILSON", },
	skins = { ghost_skin = "ghost_wilson_build", normal_skin = "wilson_pigguard", },
	torso_tuck_builds = { "wilson_pigguard", },
	release_group = 15,
})
