-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wilson_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wilson_gladiator.zip"),
	Asset("ATLAS_BUILD", "bigportraits/wilson_gladiator.xml", 192),
}

return CreatePrefabSkin("wilson_gladiator",
{
	base_prefab = "wilson",
	type = "base",
	assets = assets,
	build_name = "wilson_gladiator",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	skin_tags = { "LAVA", "BASE", "CHARACTER", "WILSON", },
	bigportrait = { build = "bigportraits/wilson_gladiator.xml", symbol = "wilson_gladiator_oval.tex"},
	skins = { ghost_skin = "ghost_wilson_build", normal_skin = "wilson_gladiator", },
	release_group = 32,
})
