-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wilson_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wilson_ice.zip"),
	Asset("ATLAS_BUILD", "bigportraits/wilson_ice.xml", 192),
}

return CreatePrefabSkin("wilson_ice",
{
	base_prefab = "wilson",
	type = "base",
	assets = assets,
	build_name = "wilson_ice",
	rarity = "Elegant",
	rarity_modifier = "Seasonal",
	skin_tags = { "ICE", "BASE", "CHARACTER", "WILSON", },
	bigportrait = { build = "bigportraits/wilson_ice.xml", symbol = "wilson_ice_oval.tex"},
	skins = { ghost_skin = "ghost_wilson_build", normal_skin = "wilson_ice", },
	release_group = 36,
})
