-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wilson_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wilson_combatant.zip"),
}

return CreatePrefabSkin("wilson_combatant",
{
	base_prefab = "wilson",
	type = "base",
	assets = assets,
	build_name = "wilson_combatant",
	rarity = "Event",
	skin_tags = { "LAVA", "BASE", "CHARACTER", "WILSON", },
	skins = { ghost_skin = "ghost_wilson_build", normal_skin = "wilson_combatant", },
	release_group = 32,
})
