-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wilson_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wilson_survivor.zip"),
}

return CreatePrefabSkin("wilson_survivor",
{
	base_prefab = "wilson",
	type = "base",
	assets = assets,
	build_name = "wilson_survivor",
	rarity = "Elegant",
	skin_tags = { "SURVIVOR", "BASE", "CHARACTER", "WILSON", },
	skins = { ghost_skin = "ghost_wilson_build", normal_skin = "wilson_survivor", },
	marketable = true,
	release_group = 4,
})
