-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_winona_build.zip"),
	Asset("ANIM", "anim/winona.zip"),
}

return CreatePrefabSkin("winona_none",
{
	base_prefab = "winona",
	type = "base",
	assets = assets,
	build_name = "winona",
	rarity = "Common",
	skin_tags = { "BASE", "CHARACTER", "WINONA", },
	skins = { ghost_skin = "ghost_winona_build", normal_skin = "winona", },
	release_group = 999,
})
