-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_winona_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/winona_shadow.zip"),
}

return CreatePrefabSkin("winona_shadow",
{
	base_prefab = "winona",
	type = "base",
	assets = assets,
	build_name = "winona_shadow",
	rarity = "Elegant",
	skin_tags = { "SHADOW", "BASE", "CHARACTER", "WINONA", },
	skins = { ghost_skin = "ghost_winona_build", normal_skin = "winona_shadow", },
	marketable = true,
	release_group = 30,
})
