-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_winona_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/winona_gladiator.zip"),
	Asset("ATLAS_BUILD", "bigportraits/winona_gladiator.xml", 192),
}

return CreatePrefabSkin("winona_gladiator",
{
	base_prefab = "winona",
	type = "base",
	assets = assets,
	build_name = "winona_gladiator",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	skin_tags = { "LAVA", "BASE", "CHARACTER", "WINONA", },
	bigportrait = { build = "bigportraits/winona_gladiator.xml", symbol = "winona_gladiator_oval.tex"},
	skins = { ghost_skin = "ghost_winona_build", normal_skin = "winona_gladiator", },
	release_group = 32,
})
