-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_winona_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/winona_formal.zip"),
}

return CreatePrefabSkin("winona_formal",
{
	base_prefab = "winona",
	type = "base",
	assets = assets,
	build_name = "winona_formal",
	rarity = "Elegant",
	skin_tags = { "FORMAL", "BASE", "CHARACTER", "WINONA", },
	skins = { ghost_skin = "ghost_winona_build", normal_skin = "winona_formal", },
	marketable = true,
	release_group = 30,
})
