-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_winona_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/winona_grassgecko_d.zip"),
}

return CreatePrefabSkin("winona_grassgecko_d",
{
	base_prefab = "winona",
	type = "base",
	assets = assets,
	build_name = "winona_grassgecko_d",
	rarity = "Elegant",
	skin_tags = { "COSTUME", "BASE", "CHARACTER", "WINONA", },
	skins = { ghost_skin = "ghost_winona_build", normal_skin = "winona_grassgecko_d", },
	marketable = true,
	release_group = 31,
})
