-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_winona_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/winona_grassgecko.zip"),
}

return CreatePrefabSkin("winona_grassgecko",
{
	base_prefab = "winona",
	type = "base",
	assets = assets,
	build_name = "winona_grassgecko",
	rarity = "Event",
	skin_tags = { "COSTUME", "BASE", "CHARACTER", "WINONA", },
	skins = { ghost_skin = "ghost_winona_build", normal_skin = "winona_grassgecko", },
	torso_tuck_builds = { "winona_grassgecko", },
	release_group = 31,
})
