-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/winterhat_black_davys.zip"),
}

return CreatePrefabSkin("winterhat_black_davys",
{
	base_prefab = "winterhat",
	type = "item",
	assets = assets,
	build_name = "winterhat_black_davys",
	rarity = "ProofOfPurchase",
	init_fn = function(inst) winterhat_init_fn(inst, "winterhat_black_davys") end,
	skin_tags = { "WINTERHAT", "CRAFTABLE", },
	release_group = 12,
})
