-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/winterhat_plum_pudding.zip"),
}

return CreatePrefabSkin("winterhat_plum_pudding",
{
	base_prefab = "winterhat",
	type = "item",
	assets = assets,
	build_name = "winterhat_plum_pudding",
	rarity = "Event",
	init_fn = function(inst) winterhat_init_fn(inst, "winterhat_plum_pudding") end,
	skin_tags = { "WINTERHAT", "WINTER", "CRAFTABLE", },
	release_group = 22,
})
