-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/winterhat_stocking_cap_green_forest.zip"),
}

return CreatePrefabSkin("winterhat_stocking_cap_green_forest",
{
	base_prefab = "winterhat",
	type = "item",
	assets = assets,
	build_name = "winterhat_stocking_cap_green_forest",
	rarity = "Spiffy",
	init_fn = function(inst) winterhat_init_fn(inst, "winterhat_stocking_cap_green_forest") end,
	skin_tags = { "WINTERHAT", "WINTER", "GREEN", "CRAFTABLE", },
	marketable = true,
	release_group = 22,
})
