-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wolfgang_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wolfgang_mighty_walrus_d.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wolfgang_walrus_d.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wolfgang_skinny_walrus_d.zip"),
}

return CreatePrefabSkin("wolfgang_walrus_d",
{
	base_prefab = "wolfgang",
	type = "base",
	assets = assets,
	build_name = "wolfgang_walrus_d",
	rarity = "Elegant",
	skin_tags = { "COSTUME", "BASE", "CHARACTER", "WOLFGANG", },
	skins = { ghost_skin = "ghost_wolfgang_build", mighty_skin = "wolfgang_mighty_walrus_d", normal_skin = "wolfgang_walrus_d", wimpy_skin = "wolfgang_skinny_walrus_d", },
	torso_tuck_builds = { "wolfgang_walrus_d", "wolfgang_skinny_walrus_d", "wolfgang_mighty_walrus_d", },
	marketable = true,
	release_group = 31,
})
