-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wolfgang_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wolfgang_mighty_gladiator.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wolfgang_gladiator.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wolfgang_skinny_gladiator.zip"),
	Asset("ATLAS_BUILD", "bigportraits/wolfgang_gladiator.xml", 128),
}

return CreatePrefabSkin("wolfgang_gladiator",
{
	base_prefab = "wolfgang",
	type = "base",
	assets = assets,
	build_name = "wolfgang_gladiator",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	skin_tags = { "LAVA", "BASE", "CHARACTER", "WOLFGANG", },
	bigportrait = { build = "bigportraits/wolfgang_gladiator.xml", symbol = "wolfgang_gladiator_oval.tex"},
	skins = { ghost_skin = "ghost_wolfgang_build", mighty_skin = "wolfgang_mighty_gladiator", normal_skin = "wolfgang_gladiator", wimpy_skin = "wolfgang_skinny_gladiator", },
	release_group = 32,
})
