-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wolfgang_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wolfgang_mighty_rose.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wolfgang_rose.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wolfgang_skinny_rose.zip"),
}

return CreatePrefabSkin("wolfgang_rose",
{
	base_prefab = "wolfgang",
	type = "base",
	assets = assets,
	build_name = "wolfgang_rose",
	rarity = "Elegant",
	skin_tags = { "ROSE", "BASE", "CHARACTER", "WOLFGANG", },
	skins = { ghost_skin = "ghost_wolfgang_build", mighty_skin = "wolfgang_mighty_rose", normal_skin = "wolfgang_rose", wimpy_skin = "wolfgang_skinny_rose", },
	torso_tuck_builds = { "wolfgang_rose", "wolfgang_skinny_rose", "wolfgang_mighty_rose", },
	marketable = true,
	release_group = 10,
})
