-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_woodie_build.zip"),
	Asset("ANIM", "anim/ghost_werebeaver_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/woodie_shadow.zip"),
	Asset("ANIM", "anim/werebeaver_build.zip"),
}

return CreatePrefabSkin("woodie_shadow",
{
	base_prefab = "woodie",
	type = "base",
	assets = assets,
	build_name = "woodie_shadow",
	rarity = "Elegant",
	skin_tags = { "SHADOW", "BASE", "CHARACTER", "WOODIE", },
	skins = { ghost_skin = "ghost_woodie_build", ghost_werebeaver_skin = "ghost_werebeaver_build", normal_skin = "woodie_shadow", werebeaver_skin = "werebeaver_build", },
	marketable = true,
	release_group = 6,
})
