-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_woodie_build.zip"),
	Asset("ANIM", "anim/ghost_werebeaver_build.zip"),
	Asset("ANIM", "anim/woodie.zip"),
	Asset("ANIM", "anim/werebeaver_build.zip"),
}

return CreatePrefabSkin("woodie_none",
{
	base_prefab = "woodie",
	type = "base",
	assets = assets,
	build_name = "woodie",
	rarity = "Common",
	skin_tags = { "BASE", "CHARACTER", "WOODIE", },
	skins = { ghost_skin = "ghost_woodie_build", ghost_werebeaver_skin = "ghost_werebeaver_build", normal_skin = "woodie", werebeaver_skin = "werebeaver_build", },
	feet_cuff_size = { woodie = 3, },
	release_group = 999,
})
