-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wx78_build.zip"),
	Asset("ANIM", "anim/wx78.zip"),
}

return CreatePrefabSkin("wx78_none",
{
	base_prefab = "wx78",
	type = "base",
	assets = assets,
	build_name = "wx78",
	rarity = "Common",
	skin_tags = { "BASE", "CHARACTER", "WX78", },
	skins = { ghost_skin = "ghost_wx78_build", normal_skin = "wx78", },
	has_alternate_for_body = { "wx78", },
	feet_cuff_size = { wx78 = 3, },
	release_group = 999,
})
