-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wx78_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wx78_formal.zip"),
}

return CreatePrefabSkin("wx78_formal",
{
	base_prefab = "wx78",
	type = "base",
	assets = assets,
	build_name = "wx78_formal",
	rarity = "Elegant",
	skin_tags = { "FORMAL", "BASE", "CHARACTER", "WX78", },
	skins = { ghost_skin = "ghost_wx78_build", normal_skin = "wx78_formal", },
	has_alternate_for_body = { "wx78_formal", },
	feet_cuff_size = { wx78_formal = 3, },
	marketable = true,
	release_group = 2,
})
