-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wx78_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wx78_rose.zip"),
}

return CreatePrefabSkin("wx78_rose",
{
	base_prefab = "wx78",
	type = "base",
	assets = assets,
	build_name = "wx78_rose",
	rarity = "Elegant",
	skin_tags = { "ROSE", "BASE", "CHARACTER", "WX78", },
	skins = { ghost_skin = "ghost_wx78_build", normal_skin = "wx78_rose", },
	has_alternate_for_body = { "wx78_rose", },
	feet_cuff_size = { wx78_rose = 3, },
	marketable = true,
	release_group = 10,
})
