-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wx78_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wx78_rhinorook.zip"),
}

return CreatePrefabSkin("wx78_rhinorook",
{
	base_prefab = "wx78",
	type = "base",
	assets = assets,
	build_name = "wx78_rhinorook",
	rarity = "Event",
	skin_tags = { "COSTUME", "BASE", "CHARACTER", "WX78", },
	skins = { ghost_skin = "ghost_wx78_build", normal_skin = "wx78_rhinorook", },
	feet_cuff_size = { wx78_rhinorook = 10, },
	release_group = 15,
})
